### ISSUE TITLE
Is there a way to access parent QueryBuilder from $relatedQuery?

### ISSUE THREAD

**Issue by escobar5** [Vincit/objection.js#1073]
I extended Model and QueryBuilder to always set the tenant_id in the queries for my multi-tenant application (one db for all tenants):

```
class BaseQueryBuilder extends QueryBuilder {
  setUserContext(user) {
    this.context({
      user,
      onBuild: builder => {
        if (builder._modelClass.tenantSpecific) {
          builder.where('tenant_id', '=', user.tenant_id);
        }
      }
    });

    return this;
  }
}

class BaseModel extends Model {
  static get QueryBuilder() {
    return BaseQueryBuilder;
  }

  static query(user) {
    return super.query().setUserContext(user);
  }
}
```

Then I always call `Model.query(user)` to pass the user to all `QueryBuilder`s I create.

Now I have a problem with `upsertGraph`, it internally calls `$relatedQuery`, I tried overriding `$relatedQuery`, but I cannot seem to find out how to access the user I set in the context of the parent `QueryBuilder`.

Is there anyway to do that?

**Comment by koskimas** [comment]
**First** of all, you should never use properties that start with `_`. They are private and may be removed at any point. You an use `builder.modelClass()` instead.

**Second**, you should not override `static query()` to take anything as an argument like that. The first argument of `query()` is a transaction or a knex instance, and it may be used internally, which will break some features if you override it like that. You should instead create some other function like `userQuery(user)` and call `this.query` from there.

**Third**, you should use `mergeContext` instead of `context`.  `context` always overrides the whole context, and you may end up removing some context if you later use it for something else.

Now to the actual question:

The context is inherited, so you can access it through the context. Now you are simply using the scoped variable. Try this instead:

```js
    this.mergeContext({
      user,
      onBuild: builder => {
        if (builder.modelClass().tenantSpecific) {
          builder.where('tenant_id', '=', builder.context().user.tenant_id);
        }
      }
```

**Comment by koskimas** [comment]
Oh, and you may need to add a check if the query is an insert query. You cannot add a `where` statement to an insert query. You can check it through `builder.isInsert()`

**Comment by escobar5** [comment]
@koskimas thank you very much, I've implemented those fixes, and I got it working, one last question, is there a way to specify the context or the builder from a transaction?
