### ISSUE TITLE
Async validation ?

### ISSUE THREAD

**Issue by yachaka** [Vincit/objection.js#113]
In the model $validate hook.
I digged a little bit into the code but seems to be fairly complicated to implement.

**Comment by koskimas** [comment]
Making the validation async would make a huge amount of other code async also and I don't want to do that. For example, every time you would create a model instance using `Model.fromJson({foo: 'bar'})` you would get a promise instead of a model instance.

You can add async validation on `insert` and `update` operations by implementing the `$beforeUpdate` and `$beforeInsert` hooks:

```js
class Person extends Model {
  $beforeInsert() { return this.$asyncValidate(); }
  $beforeUpdate() { return this.$asyncValidate(); }

  $asyncValidate() {
    return doSomethingAsync();
  }
}
```

**Comment by yachaka** [comment]
I'll go with that.
Would be a nice feature, though !
Thanks!
