### ISSUE TITLE
Clarification on upsert graph options and through relations

### ISSUE THREAD

**Issue by kennyist** [Vincit/objection.js#1132]
I currently have 3 tables, games, platforms and games_platforms to join both. These have been related through models Games and Platforms like so: 

```
static get relationMappings() {

    const Games = require('./games');

    return {
      games: {
       relation: Model.ManyToManyRelation,
       modelClass: Games,
       join: {
         from: 'platforms.id',
         through: {
           from: 'games_platforms.platform_id',
           to: 'games_platforms.game_id'
         },
         to: 'games.id'
       }
     }
    }
  }
```
and 

```
static get relationMappings() {

    const Platforms = require('./platforms');

    return {
      platforms: {
       relation: Model.ManyToManyRelation,
       modelClass: Platforms,
       join: {
         from: 'games.id',
         through: {
           from: 'games_platforms.game_id',
           to: 'games_platforms.platform_id'
         },
         to: 'platforms.id'
       }
     }
    }
  }
```

This seems to be working fine but when it comes to graph upserting im running into issues, for example if i use the options `insertmissing: true, relate: true, unrelate: true, nodelete: true` this will create the games entry and games_platform join entry but does not create the platforms row. If i just use `insertmissing: true` this will create both but will run into a duplication error when a game using the same platform as any game before it. Also if i run it again using this setting it will error at the same place even though the entrys are already in the database, so shouldnt it break on the first upsert attempt?  

I have tried a few combinations like this `insertMissing: ['games', 'games.platforms'],relate: ['games.platforms'], unrelate: ['games.platforms'], nodelete: ['games', 'games.platforms']` but i am still unsure how to get the desired output where games are upserted, releations in game_platforms are added or deleted if not in object and platforms are upserted, and games and platforms are not deleted.

To clarify, games and platforms always have an ID before being inserted or updated using upsertgraph, games_platform uses auto increment ID. sample game:

```
{
    id: "304",
    name: "game name",
    platforms: [
        {
           id: "7",
           name: "PC"
        },
       {
          id: "12",
          name: "PS4"
        }
    ]
}
```

The duplication error: `error: duplicate key value violates unique constraint "platforms_pkey"`

**Comment by koskimas** [comment]
Ok, so the confusion here comes from the fact that `insertMissing` doesn't mean "insert if not found in the database" but "insert if not found in the **relation**".

So if you have `insertMissing` enabled for some relation, it only means that "insert those rows that have an id and don't exist currently in the relation of the parent object".

Supporting this use case would require a bunch more select queries to be made. `upsertGraph` would need to try to fetch all rows that have an `id` specified, just to make sure they don't exist in the db. Now `upsertGraph` only fetches the input tree.

I need to update `insertMissing` documentation since currently it's clearly misleading. I'll leave this open, as this may be something I'd like to add in the future, but unfortunately it's not going to happen any time soon.

**Comment by danielvy** [comment]
> Two thumbs up for this issue? People in your team maybe?

Now it has 3 thumbs up 😄

He raises a legitimate point because the `upsertGraph/insertMissing` is somewhat confusing both in the implementation and documentation. What he is trying to do is probably the most common use case when using many-to-many relation. Of course there will be duplicate keys when dealing with the _"other"_ table, that's the entire point of this type of relation.

The common scenario and expected behavior when doing an "upsert" to a table with many-to-many relation is:

- Insert a record to the **base** table (the _"from"_ side of the relation), if doesn't exist or update it.
- Insert/remove/update the actual relations in the **through** table.
- Insert a record to the **other** table (the _"to"_ side of the relation) if doesn't exist. Optionally update it if it does (no by default).
- Never remove records from the  **other** table.

Is there a way to achieve this with the current implementation of `graphUpsert`? Or can it only be achieved by separate manual queries?

Thanks.

**Comment by koskimas** [comment]
@danielvy That's only a problem when you provide you own identifiers and don't generate them in the db. So, not really that common.

**Comment by davidmwhynot** [comment]
Is there a workaround if we are using our own identifiers? For various reasons, I'm locked into UUID as the PK for the related table.

**Comment by davidmwhynot** [comment]
> @koskimas Is there a workaround if we are using our own identifiers? For various reasons, I'm locked into UUID as the PK for the related table.

Nevermind, I was able to resolve my issue by using:
```ts
{
	insertMissing: true,
	update: true,
	relate: true
}
```
