### ISSUE TITLE
How to query name without specifying details?

### ISSUE THREAD

**Issue by oipewr** [Vincit/objection.js#1139]
I'm playing with express-ts example. I'd like to know how to query user's product by name without specifying details, such as capital letters or numbers.

For example: User has four items (name), **Jacket**, **Shirt**, **shOes** and **Jack45**. Query like `http://localhost:8641/users/3/products/?name=jAc5` can get both **Jack** and **Jack45**, and query like `http://localhost:8641/users/3/products/?name=sH` can get both **Shirt** and **shOes**.

```ts
  router.get("/users/:id/products", async (req, res) => {
    const user = await User.query().findById(req.params.id);

    if (!user) {
      throw createStatusCodeError(404);
    }

    const products = await user
      .$relatedQuery<Product>("products")
      .skipUndefined()
      .where("name", "like", req.query.name)
      .where("category", req.query.category)
      .where("price", ">=", req.query.minPrice)
      .where("price", "<", req.query.maxPrice);

    res.send(products);
  });
```

Please help.

**Comment by koskimas** [comment]
Objection is a query builder, so you should always search for your db documentation for an answer for questions like these. I don't know which db you are using, but at least with postgres, this would work:

```js
      .where("name", "ilike", `${req.query.name}%`)
```

notice the wildcard `%` and `ilike` instead of `like`. I usually try to avoid `ilike` because it cannot be indexed (if you later need indexes). This is equivalent and can be indexed

```js
      .where(raw("lower(name)"), "like", `${req.query.name.toLowerCase()}%`)
```

**Comment by koskimas** [comment]
`raw` comes from `const { raw } = require('objection')`

**Comment by oipewr** [comment]
Thanks for the quick reply.
