### ISSUE TITLE
patch method is updating more fields than are specified

### ISSUE THREAD

**Issue by jsumners** [Vincit/objection.js#114]
Consider the model:

```javascript
function MyModel() {
  Model.apply(this, arguments);

  this.generatedHash = someMethodGeneratingAUniqueHash();
  this.somePropertyToBePatched = null;
}

Model.extend(MyModel);
MyModel.tableName = 'my_model';
```

Each time the model is instantiated, and Objection does this even for non-instance operations, the `generatedHash` property is populated.

If an instance is created, `somePropertyToBePatched` is set to a value, inserted, and then patched, the `generatedHash` value gets modified during the patch operation.

```javascript
const myModel = new MyModel();
myModel.somePropertyToBePatched = 'foo';
MyModel.query().insert(myModel);
// record => { id: 1, generatedHash: '123abc', somePropertyToBePatched: 'foo' }

// do some other things
MyModel.query().patch({somePropertyToBePatched: 'bar'}).where('id', 1);
// record in the database is now:
// { id: 1, generatedHash: '456def', somePropertyToBePatched: 'bar' }
```

This is with version 0.4.0.

**Comment by koskimas** [comment]
This is intentional. You should not do stuff like this in the constructor. You want the the hash to be created when the model is first inserted to the database, right? You should generate it in the `$beforeInsert` hook.

**Comment by jsumners** [comment]
No, I want it created when I create my instance of the model. I have work to do with it before it goes to the database.

**Comment by koskimas** [comment]
The patch object is converted into a model so that we can call the `$beforeUpdate` and `$afterUpdate` hooks for it. It also ensures that the `$parseJson` and `$formatDatabaseJson` methods are invoked and the the conversions defined in them are executed. It is a very common practice to define a camelCase to snake_case conversion in the `$formatDatabaseJson` method.

The model constructor is not very useful in objection models because of this. You can skip all this and use a pure knex update like this:

```
MyModel.knexQuery().patch({somePropertyToBePatched: 'bar'}).where('id', 1);
```

**Comment by jsumners** [comment]
I suppose I'll just have to keep that in mind for future projects. For the one this was affecting me, I have switched the db to mongo for now. The snake/camel case conversion was way too expensive (no matter the implementation I chose, and `ModelBase.js:454:37` was using a significant number of ticks as well.

**Comment by koskimas** [comment]
About the expensive line in ModelBase.js.. What version were you using? Is that a line in the transpiled code or in source code?

**Comment by jsumners** [comment]
Version 0.4.0.

In the attached profiling trace, you can ignore the camel case stuff. It's lines 40 and 2617 that are specific to ModelBase.js.

The model in question -- https://github.com/jscas/cas-server-registries-db/blob/master/lib/dbModels/_base.js

[processed.txt](https://github.com/Vincit/objection.js/files/248707/processed.txt)

**Comment by koskimas** [comment]
The line 2617 is caused by the `string.replace` method that is probably called inside the sentence-case method. It doesn't come from objection.js code since `string.replace` is not called once in the codebase. V8 does some heavy inlining and the profile shows the inlined operations as if they are a part of the function that called the inlined functions.

Is the performance is bad even if you memoize the sentence-case and camel-case operations? Doing the conversion without memoizing/caching will be too slow no matter how you implement it. With propert memoizing they shouldn't be a bottleneck.

**Comment by jsumners** [comment]
I used two different external modules for case conversion. I don't think either cached the results.
