### ISSUE TITLE
Ignore results by specifying conditions on relations when using eager.

### ISSUE THREAD

**Issue by abhyuditjain** [Vincit/objection.js#1157]
For example, I have this: https://gist.github.com/abhyuditjain/662bd103706a9fdb8457faadb9bbe79f
In this I am trying to fetch all the `flightSchedules` but only want results where `departureAirport.iata` is `"DEL"`.  I have defined the models, query and the output in the gist.

But I get `flightSchedules` with `flight` and `arrivalAirport` where the `departureAirport` didn't meet the criteria.

The models, query and the output are in the gist.

_Originally posted by @abhyuditjain in https://github.com/Vincit/objection.js/issues/1146#issuecomment-439899950_

**Comment by koskimas** [comment]
The default eager algorithm doesn't use joins. Therefore you cannot filter by relations (the relations are fetched using separate queries). You can use the join based `joinEager` method instead of `eager`. Then you can filter the root query using the relations. Something like:

```js
await Person.query()
  .joinEager('[pets, children.pets]')
  .where('pets.name', 'Fluffy')
  .orWhere('children:peys.name', 'Fluffy')
```

This would return all `Person`s that have a pet named `Fluffy` AND the `Person`s whose some child has a pet named `Fluffy`.

You can always chain `.debug()` to queries to see what gets executed. There you'll also see where `filterEager` query gets added.

You can read more about the default eager algorith [here](https://www.vincit.fi/blog/nested-eager-loading-and-inserts-with-objection-js/)
