### ISSUE TITLE
where() and joinEager() with $modify for selecting some fields not giving correct results

### ISSUE THREAD

**Issue by abhyuditjain** [Vincit/objection.js#1158]
Hi.

I have models: Flight, Airport and FlightSchedule. I have set the modifier in Airport model to select certain fields, among them is `st.asGeoJSON('location').as('location')`.

Now I am using `joinEager()` and `where` to select based on certain criteria.

I am not getting the location.

Models, query and output are in the gist.
https://gist.github.com/abhyuditjain/662bd103706a9fdb8457faadb9bbe79f

**Comment by abhyuditjain** [comment]
Hi @koskimas 

I think the issue is with `joinEager` as the `defaultSelects` is working with `eager`.

Regards

**Comment by koskimas** [comment]
What is `st`?

**Comment by abhyuditjain** [comment]
`st` is `knex-postgis` package.

**Comment by koskimas** [comment]
Does `st.asGeoJSON('location').as('location')` return a knex `raw` instance? The problem is that objection doen't know how to handle that object. The only way objection can select the column correctly is by knowing the alias of the field. You are only providing the name to an `as` method of some random object of which objection knows nothing about.

If that's a `knex` raw instance, I could probably write a hack that digs the alias from the object's private fields, but I don't know if I should add such a hack. It can break any time knex maintainers decide to refactor the internals of the `raw` object.

**Comment by abhyuditjain** [comment]
@koskimas Yes, it returns a `raw` instance. What should I do if I want to get the coordinates from the GEOGRAPHY as it can be done in the database only?

**Comment by koskimas** [comment]
Don't use `joinEager`. Use normal `eager` and `joinRelation` instead.

**Comment by koskimas** [comment]
This is not an objection thing you need to find from the docs. It's just a matter of knowing that an SQL join is what you want and then searching for `join` in the docs and finding that there's a `joinRelation` helper. You could do all this with normal handcrafted SQL joins, but `joinRelation' saves you some trouble.
