### ISSUE TITLE
Upsert trouble

### ISSUE THREAD

**Issue by crdil** [Vincit/objection.js#118]
I'm trying to use the upsert function from the documentation. But I do not understand how this could work.
```
class MyQueryBuilder extends QueryBuilder {
  upsert(model) {
    if (model.an_id) {
      return this.update(model).where('an_id', model.an_id).returning('an_id');
    }
    else {
      return this.insert(model).returning('an_id');
    }
  }
}
```
Since model.an_id always will exist for me, the insert query will never run.
What I want is that the insert query shall run if the record with an_id does not exist in the db.

Is there anyway I can solve this?

**Comment by koskimas** [comment]
The `upsert` method in the documentation is just a simple example of a custom query builder method.

`upsert` method is pretty difficult to implement correctly and needs to be written separately for each database. Knex doesn't have an upsert method. I think this is something that should be added to knex instead of objection. As soon as that happens, objection can add support.

Maybe you can work around this by checking some other property that is only added on insert, such as `inserted_at`?

**Comment by crdil** [comment]
I solved it by sending a value from the frontend app to the route, which i then use in the upsert method to return query depending on that value.
Thanks
