### ISSUE TITLE
Suggestion: allow return empty result with skipUndefined 

### ISSUE THREAD

**Issue by s123121** [Vincit/objection.js#1186]
First of all, thanks for the wonderful library. It helps me a lot in my job
Well, now to the main point, I think the default behavior of `skipUndefined` is quite liberating. Rather than ignore the undefined variable, I want to return empty result. Consider this case:
```
const result = await Person.query().skipUndefined().where('id', req.query.id)
```
If `req.query.id` is not available, `result` will contain all the Person data (which could potential leak unnecessary data into frontend)

Or consider this case: 
```
const result = await Job
  .query()
  .skipUndefined()
  .where('id', req.query.id)
  .andWhere('status', req.query.status)
  .andWhere('location', req.query.location)
  .eager('applicants(onlyMe)', {
     onlyMe: builder => {
        builder.skipUndefined().where('userId', req.user.id)
   })
```
If `req.user.id` is not available, `result` will contain all the applicants data for that job (which is not desirable result). I know I can conditionally check the availability of those variables, but this is such a common use case that I wish it would be integrated to the library

I don't know if this is technical feasible or not but  here is my suggestion: have skipUndefined accept an optional config, something like `skipUndefined({ returnEmpty: true })`

**Comment by koskimas** [comment]
Couldn't you simply do something like this in that case:

```
builder.where('userId', req.user.id || 0)
```

?

**Comment by s123121** [comment]
Yeah, that is what I am current doing right now. However, seeing this as a common use case, maybe it is better built-in function instead of a workaround. Moreover, the default behavior of skipUndefined is quite dangerous that could potential lead to information leakage. The built in option can be something as a reminder to encourage people to code correctly

**Comment by elhigu** [comment]
Sounds like this boils down to basic design principles of this library if we want to add kind of redundant functionality (actually having that option would not be completely redundant, since it would prevent launching any queries to the DB) for library, which is maybe more informative and opinionated to the end user or keep API smaller and prefer all the users to make sure that undefined are not passed to the API if they don't want exceptions to be thrown. 

Anyways, always returning an empty array would cause inconsistent return type for some queries, which naturally doesn't return an array as a result, so instead returnEmpty... actual empty result should be given to the option (e.g. if it is 0, null or []).

**Comment by koskimas** [comment]
@s123121 You alreary "opt in" for the dangerous functionality by calling `skipUndefined`, so it's not a surprise. I don't think this would be useful enough compared to how difficult it would be to implement consistently across all methods.

**Comment by koskimas** [comment]
And what i suggested (userId || 0) actually causes a zero result since there cannot be an id 0.
