### ISSUE TITLE
[Docs] The term "JSON object" in the API reference for "$toJSON" and "toJSON" misleading

### ISSUE THREAD

**Issue by k-j-kleist** [Vincit/objection.js#1190]
The _Objection.js_ docs are generally very well written, with lots of useful examples. The "Model lifecycle" chapter (https://github.com/Vincit/objection.js/blob/master/doc/includes/API.md#model-lifecycle) feels accurate, as does the description of the most of the JSON function. (As far as I can tell, still being an Objection rookie.)

However: The wording "JSON object" in https://github.com/Vincit/objection.js/blob/master/doc/includes/API.md#tojson and https://github.com/Vincit/objection.js/blob/master/doc/includes/API.md#tojson-1 is misleading. The exported object is not json:ish, it's a normal [object Object]. Javascript has no such thing as a "JSON object", aside from the global JSON object that provides parse() and stringify().

**Comment by koskimas** [comment]
`toJSON` is method that `JSON.stringify` calls on objects the method exists, and instead of the original object, stringifies the returned object. `$toJson` is just an alias for that to match the other hook names.

JSON object is a real thing. JSON is a subset of javascript, and a JSON object is an object with only JSON compatible keys and properties. For `$toJson` and `toJSON` the wording makes complete sense, because the result of those should be in a format that can be stringified using `JSON.stringify`.

For `$toDatabaseJson`, `$formatDatabaseJson` and `$parseDatabaseJson` it makes less sense, because you can actually return for example `knex.raw` instances, knex query builders, Date objects etc. from those.

Maybe POJO (Plain Old Javascript Object) would make more sense in all of these? (even though that's not true either for the sub objects of the POJO returned from `$fromatDatabaseJson`).

**Comment by k-j-kleist** [comment]
Sami, thanks for elaborating on this. What you wrote makes, of course, complete sense.

It seems that the somewhat loose term "JSON object" has (at least) four different meanings:

1. as in the "official" definition of the JSON text format (http://json.org): "an unordered set of name/value pairs. An object begins with { (left brace) and ends with } (right brace)"

2. as synonym for a text string or file, a so called "JSON document"

3. "an object with only JSON compatible keys and properties [---] that can be stringified using JSON.stringify", as you wrote above, and as discussed thoroughly here: https://derickbailey.com/2015/10/26/dont-return-a-json-document-from-the-tojson-method/

4. the global JSON object in ECMAScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON

I incorrectly interpreted the term, as used in the Objection.js documentation, according to item 2.

It's all pretty confusing, eh?

**Comment by elhigu** [comment]
I've been using those terms like: 

json object = javascript object containing only json compliant keys and values
json string = string containing serialized json content
json file = duh
json document = when talking about json contents without making claims of its storage format

I have never heard that anyone would have confused those with the global JSON object. 

I don't know if docs should have any separate definitions section for defining used terms the same way that research papers does.

**Comment by koskimas** [comment]
Yeah, the names are not the best, but they are consistent and in line with the same concepts in other node ORMs like bookshelf. Could you provide an idea for improving this?  The names need to clearly communicate the current intent (converting outside world / database representations to the model instance format).

**Comment by koskimas** [comment]
Also `toJSON` is not invented by me. It's a standard hook that `JSON.stringify` uses, and the method DOES return an object and not a string. So even the person who wrote the JSON spec for javascript seems to agree that `JSON` can mean an object (or an array) in addition to any json value.

**Comment by koskimas** [comment]
@k-j-kleist Also the documentation for `$toJson` and friends clearly states the return and input types to be `Object` and not `string`.
