### ISSUE TITLE
Pick return virtual attributes?

### ISSUE THREAD

**Issue by tuurbo** [Vincit/objection.js#1252]
Would be sweet if ```pick``` could work similar to ```virtualattributes``` http://vincit.github.io/objection.js/#virtualattributes wihout the need to defined virtualAttributes and call ```.json()```

```ts
class Person extends Model {
  firstName: string;
  lastName: string;

  fullName() {
    return `${this.firstName} ${this.lastName}`;
  }
}

Person.query().pick(Person, ['id', 'fullName']).first();
```
or even a way to append virtual attributes per query. Something like
```ts
Person.query().append(Person, ['fullName']).first();
```

Thanks!

**Comment by koskimas** [comment]
I don't think this is a good idea. First of all, you can define your virtual attributes as getters, so that they are immediately useful without any picking:

```js
class Person extends Model {
  firstName: string;
  lastName: string;

  get fullName() {
    return `${this.firstName} ${this.lastName}`;
  }
}

const person = await Person.query().first();
console.log(person.fullName)
```

That doesn't include them in the output of `toJSON` though, and therefore you need the `virtualAttributes` array. You can currently pass the `virtuals` boolean option to `toJSON` methods to tell it whether to include the virtuals in the json or not. You could omit all virtuals using `person.toJSON({ virtuals: false })`. That means that you have to call `toJSON` explicitly though (for example `res.send(person)` calls it automatically).

I could consider allowing the `virtuals` option to be an array, so that you could only include a limited set of virtuals. It could even work for properties that are not in `virtualAttributes`. You could do this:

```js
class Person extends Model {
  firstName: string;
  lastName: string;

  fullName() {
    return `${this.firstName} ${this.lastName}`;
  }
}

const person = await Person.query().first();
res.send(person.toJSON({ virtuals: ['fullName'] })
```

Would that be helpful?

**Comment by tuurbo** [comment]
Thanks! That was fast. ```person.toJSON({ virtuals: ['fullName'] })``` should work for me
