### ISSUE TITLE
Dynamic models based on temp views

### ISSUE THREAD

**Issue by jeff3yan** [Vincit/objection.js#1255]
I'm creating an endpoint which calls a postgres function (which is basically just a parameterized query). However, I'd like to use the results of that query as if it were a model (for filtering, eager loading etc).

The function looks something like this:
`get_report(group_id INTEGER, date DATE)`

If I were to wrap this in a _temp view_ and return it as a new _model class_, is there anything wrong with this? For example from a garbage collection perspective or anything else?

I'm thinking something like this:

```
function createModel(groupId, date, trx) {
    await knex.raw('create temp view "report_view" as get_report(?, ?);', [groupId, date]);

    return class ReportModel extends objection.Model {
        static get tableName() {
            return 'report_view'
        }
        
        static get relationMappings() {
          ...
        }
    }
}
```

**Comment by koskimas** [comment]
I see nothing in your code that would prevent you from defining that model outside that function instead of always creating a new class. Does the model definition depend on the function inputs somehow?

If it does, and you need to define the model class dynamically, you will see a (significant?) performance drop for couple of reasons:

1. objection models do a bunch of initialization the first time you use them (creates the internal representation of relations etc.) and then caches it.
2. AFAIK v8 creates a new hidden map for each class and creating alot of Model subclasses will make all Model's methods megamorphic (slow). This probably isn't a huge deal, if even true anymore.

Measure the performance, and if it's good enough, there shouldn't be any other problems with this.

**Comment by jeff3yan** [comment]
Thanks for clearing that up. Yes I don't think there needs to be anything dynamic. The temp view will always have the same name but the view query will differ per-transaction.

**Comment by TimNZ** [comment]
Dynamic class generation from a schema is a winner feature of ORM e.g. Prisma.
I'll do some testing to see if there is any performance hit in latest Node.js.
Though I don't think it's a real world concern for most situations if there is, even 2-3x

**Comment by calebeaires** [comment]
Hey @TimNZ, did you had some progress at your proposal?

**Comment by chief-austinc** [comment]
bump @jeff3yan - curious how you solved this.

**Comment by jeff3yan** [comment]
@chief-austinc just ended up using postgres views and the typical models, rather than doing anything dynamic.
