### ISSUE TITLE
eager loading off two possible 'from' fields?

### ISSUE THREAD

**Issue by briankmetz** [Vincit/objection.js#1264]
Hi, first time posting. Objection has been super useful for the project I'm working on but I'm wondering if there's a way to solve this issue I'm having without using a workaround?

I have a User model and a Meeting model where Meetings foreign key to Users twice. Every meeting has a sender_user_id and a recipient_user_id. I want to write a query to get all meetings a given user is a member of (as either the sender or recipient) and I want to eager load the other user as part of the query. Something like:

```
	const meetings = await Meeting.active()
		.where(function (builder) {
			builder
				.where('meeting.sender_user_id', user_id)
				.orWhere('meeting.recipient_user_id', user_id)
		})
		.context({userId: user_id})
		.eager('[other_user]')
```

I cannot figure out a way to write a relationMapping where 'other_user' relates from sender_user_id and recipient_user_id to user.id at the same time. Something like:

```
	other_user: {
		relation: Model.HasOneRelation,
		modelClass: User,
		modify: 'not_me',
		join: {
			from: ['meeting.recipient_user_id', 'meeting.sender_user_id'],
			to: 'user.id'
		}
	}
```

Where 'not_me' is a User modifier that keeps the eager relation from returning the given user's own profile: 
	`builder.where('user.id', '!=', builder.context().userId)`

The best I can think to do is to create two separate relations: 'sender' and 'recipient' which each map from one of the Meeting user fields to the user table. Eager load both of these relations and then iterate through the result set and choose the correct one to be the other_user object. Basically like the original query but with:

```
	const meetings = await Meeting.active()
		.where(function (builder) {
			builder
				.where('meeting.sender_user_id', user_id)
				.orWhere('meeting.recipient_user_id', user_id)
		})	
		.eager('[sender, recipient]')

	for(var i = 0; i < meetings.length; i++){
		meetings[i].other_user = (meetings[i].sender_user_id != user_id) ? meetings[i].sender : meetings[i].recipient;
	}
```

Which shouldn't be a big deal but I was wondering if objection could handle this itself.

**Comment by koskimas** [comment]
Unfortunately you need two separate relations. There's no way to create a single relation like that. You could create a pivot table and a many-to-many relation with a something like a `meeting_user_type` `extra` column though.

So instead of having `sender_user_id` and `recipient_user_id` you could create a pivot table with columns `{ user_id, meeting_id, meeting_user_type }`. `meeting_user_type` should be a required enum type with two possible values `'recipient'` and `'sender'`. Then you could create a many-to-many relationship through that pivot table:

```js
class Meeting extends Model {
  static relationMappings = {
    users: {
      modelClass: User,
      relation: Model.ManyToManyRelation,
      join: {
        from: 'meeting.id',
        to: 'user.id',
        through: {
          from: 'meeting_user.meeting_id',
          to: 'meeting_user.user_id',
          extra: ['meeting_user_type']
        }
      }
    }
  }
}
```

Then you can do things like this:

```js
const meetings = await Meeting.query()
  .whereExists(Meeting.relatedQuery('users').where('id', user_id))
  .eager('users')

console.log(meetings[0].users[0].meeting_user_type) // --> 'sender'
console.log(meetings[0].users[1].meeting_user_type) // --> 'recipient'
```

```js
const meeting = await Meeting.query().findById(meeting_id)

meeting.$relatedQuery('users').relate({
  id: user_id,
  meeting_user_type: 'recipient'
})
``` 

And so on. You could even add a constraint to the db, only allowing one item per type per `user_id`, `meeting_id` pair so that you don't end up with multiple recipients and senders per meeting.

I don't know if this makes sense in your application, but that's pretty much the only way to get the users in an array.

**Comment by briankmetz** [comment]
Okay thank you! The many to many pivot table could work. There's a chance the application would want to support more than two users per meeting in the future anyways.
