### ISSUE TITLE
Question: json query syntax

### ISSUE THREAD

**Issue by anhvutnu** [Vincit/objection.js#128]
Hello,

I have a question regarding syntax. Suppose I have a database of objects that look like these;

[
{
“name” : “a”,
“properties” : [ {“name” : “p1”, “description” : “this is p1”}, {“name” : “p2”, “description” : “this is p2”}]
},

{
“name” : “b”,
“properties” : [{“name” : “p1”, “description” : “this is p1”}]
]

how do I form a json query that selects all objects that have properties with name “p1”?

Thanks

**Comment by elhigu** [comment]
I actually already answered to blog post comment... but I'll copy-paste it here too:

I think you can use superset operator for that.

Since `[1,2,3]` is superset of `[1]` and `{name: ’p1’, description: ’this is p1’}` is superset of `{name : ’p1’}` you should be able to check that your `properties` array is superset of `[{ name: ’p1’ }]`

```js
.whereJsonIsSupersetOf(’columnName:properties’, [{ name: ’p1’ }])
````

**Comment by yucigou** [comment]
`whereJsonIsSupersetOf` is now `whereJsonSupersetOf` for Objection.js v1.4.0
