### ISSUE TITLE
Isn't #ref{...} a security risk?

### ISSUE THREAD

**Issue by phormio** [Vincit/objection.js#1296]
Isn't `#ref{...}` (for example, `#ref{jenni.firstName}` as used [here](https://github.com/Vincit/objection.js/blob/4659ea339d5a1e1b615e59ab5645bfb5a0f9da3a/doc/guide/query-examples.md#examples-7)) a security risk?  What if it appears in untrusted data?

One workaround for this problem is to disable `#ref{...}` entirely by:
* defining a class `BaseModel` that extends `Model`;
* setting `BaseModel.propRefRegex` to a regex that cannot match any string.

**Comment by phormio** [comment]
I can't think of a way to exploit this, so I'm closing the issue.

**Comment by koskimas** [comment]
You can only reference the items inside the same graph, which you should be able to control anyway since the same client sent the whole thing. You can, however, create very unsafe code with `insertGraph` and `upsertGraph` if you just blindly allow things like `relate` and `$dbRef` references. People can take ownership of items they are not supposed to if you don't check the references and ids. The solution is to use `insertGraph` and `upsertGraph` very carefully.

**Comment by javiertury** [comment]
@phormio, I am also worried about this issued. I found out that you can change the keys used for referencing as a workaround: [uidProp](https://vincit.github.io/objection.js/api/model/static-properties.html#static-uidprop),  [uidRefProp](https://vincit.github.io/objection.js/api/model/static-properties.html#static-uidrefprop), [dbRefProp](https://vincit.github.io/objection.js/api/model/static-properties.html#static-dbrefprop) and [propRefRegex](https://vincit.github.io/objection.js/api/model/static-properties.html#static-proprefregex).

@koskimas, perhaps objection could use ES6 Symbols instead of strings. Then the use them as `QueryBuilder.dbRef` or `import { dbRef } from 'objection'`. It will improve security, since they cannot be faked by end clients.

Replacing `propRefRegex` is more difficult. Perhaps provide a way to disable referencing the properties of other models for text properties?

**Comment by javiertury** [comment]
Example

```
class BaseModel extends Model {
  static get uidProp() { return Symbol(); }
  static get uidRefProp() { return Symbol(); }
  static get dbRefProp() { return Symbol(); }
  // Disable #ref{...} in property strings
  static get propRefProp() { return { exec: _str => null }; }
}
```
