### ISSUE TITLE
`this` context not bound to `JoinClause` equivalent (v0.3.3)

### ISSUE THREAD

**Issue by jacksonrayhamilton** [Vincit/objection.js#131]
Hi, we are currently using objection `v0.3.3`, as `v0.4.0` had a breaking change where several parts of the API, e.g. `objection.Model`, now must be accessed via `import {Model} from 'objection';`, and we just haven't got around to refactoring our code to use the new API. So we'd like to know if the following issue has been fixed in a recent version:

Knex has support for grouped joins via `this.on` ([see here](http://knexjs.org/#Builder-join)):

> For grouped joins, specify a function as the second argument for the join query, and use `on` with `orOn` or `andOn` to create joins that are grouped with parentheses.
> ```js
> knex.select('*').from('users').join('accounts', function() {
>   this.on('accounts.id', '=', 'users.account_id').orOn('accounts.owner_id', '=', 'users.id')
> })
> ```

However, in objection `v0.3.3`, neither `this` nor the first argument to the function is a `JoinClause` (unlike [in Knex](https://github.com/tgriesser/knex/blob/89fe76faa30ec2064ef13faf1a37cb4b0af9004d/lib/query/builder.js#L102)). Rather, a `QueryBuilderBase` without an `on` method [is bound](https://github.com/Vincit/objection.js/blob/61e36984da02b8a39d83665cb7405322c02a262e/lib/queryBuilder/QueryBuilderBase.js#L1131), so I get a `TypeError` due to "'on' is not a function."

As usual, we can work around this with a raw query, but we'd rather not for security reasons.

**Comment by koskimas** [comment]
I assume you use babel to transpile your code? I switched to ES7 + babel in version 0.4.0 and that causes your babel to recognize the root object as module.

Isn't it really easy to fix the imports? You could even write a regex in like 30 seconds to do the refactoring for you? There shouldn't be any other breaking changes. You can the whole root object of objection using

```js
import * as objection from 'objection';
```

I'm sorry, but I don't want to start maintaining old versions at this point, since there are no major breaking changes between the versions.

**Comment by jacksonrayhamilton** [comment]
Great, looks like it's time for us to upgrade. Or would you recommend we wait for `v0.5.0`?

**Comment by koskimas** [comment]
The current RC version (0.5.0-rc.5) is most probably the 0.5.0 release version, so you can already try that one. I'd recommend 0.5.0 if there is no problems. If there is, please let me know.

**Comment by jacksonrayhamilton** [comment]
Thanks!
