### ISSUE TITLE
How to gracefully  close connection when using serverless lambas (e.g. now.sh) 

### ISSUE THREAD

**Issue by reetou** [Vincit/objection.js#1319]
Hello, I was wondering is there a way to use Objection.js + Knex.js along with serverless lambdas. All I achieved is closing instance in `BaseModel` and creating it on each request in middleware but seems like it does not work correctly in my case because lambdas create too many connections on each request (or probably I missed something). Could you please guide me to something? 
Thanks in advance.

**Comment by koskimas** [comment]
All you should need to do is call `await knex.destroy()`. Are. You doing that?

**Comment by reetou** [comment]
@koskimas I do, but if I do next request in the same time looks like sometimes machine where I called `knex.destroy()` received that request and request fails because models don't have knex instance.

**Comment by reetou** [comment]
Sorry, looks like I used connection pool and that's was the issue.

**Comment by marceliwac** [comment]
I know this is a fairly old post, but it came up when I was trying to debug a very similar issue.

The problem I have ran into had to do with running serverless offline (serverless-offline) and a custom logic that binds the database on the start of every execution, and destroys the connection at the end. The problem I faced, specifically, had to do with models losing the connection binding, when multiple calls to the API (or invocations of serverless lambdas) would take place simultaneously. The connection would be bound when the first lambda starts, and destroyed after the handler completes, but the other lambda running at the same time would successfully start (verifying that connection is indeed present), only to throw an error when attempting to execute a query once, because the first lambda destroyed its connection when it finished.

It took me embarassingly long to figure out what was happening, but when I finally did, I realised that this can be fixed by using the `--useChildProcesses` flag for serverless offline, which seems to isolate the lambda executions, preventing the connection binding and destruction from interfering between lambdas which are ran simultaneously.
