### ISSUE TITLE
insertWithRelated should rollback when error on child insert

### ISSUE THREAD

**Issue by rafaljanicki** [Vincit/objection.js#133]
Hello,

Currently, `insertWithRelated` does not rollback data when there is an error on child insert (e.g. missing required field) what leads to invalid state of a database. Shouldn't this rollback by default (or at least have an option for that)? Right now, I'm forced to make a transaction out of it what makes it more complex

Best,
Rafal

**Comment by koskimas** [comment]
Hi,

While you almost always should perform an `insertWithRelated` operation in a transaction, I don't think it's a good idea for objection to start a transaction implicitly behind the scenes. This is because you may want to control the transaction parameters (like isolation) and add other queries to it besides the insert. 

Transactions are the only rational way to performa a rollback, so doing a non-database rollback doesn't make sense. So, just use a transaction 😄

**Comment by rafaljanicki** [comment]
Ok, it makes sense. I was thinking about `insertWithRelated` as an isolated block of tasks, but you're right with other queries :)
