### ISSUE TITLE
TypeScript Model extends fails to include static functions

### ISSUE THREAD

**Issue by jocull** [Vincit/objection.js#136]
I'm not exactly sure of why this fails. When extending a new model with TypeScript, static functions like `query()` are missing.

Here is the TypeScript:

```
import { Model } from 'objection'

export class UserAccount extends Model<UserAccount> {
    public static get tableName() { return 'user_accounts'; }

    constructor() {
        super();
    }
}
```

Here is the compiled JS:

```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var objection_1 = require('objection');
var UserAccount = (function (_super) {
    __extends(UserAccount, _super);
    function UserAccount() {
        _super.call(this);
    }
    Object.defineProperty(UserAccount, "tableName", {
        get: function () { return 'user_accounts'; },
        enumerable: true,
        configurable: true
    });
    return UserAccount;
}(objection_1.Model));
exports.UserAccount = UserAccount;
```

You can fix this by adding a call to `extend` after defining the class, but I don't believe this should be required in ES6 style.

```
Model.extend(UserAccount);
```

**Comment by koskimas** [comment]
This is a problem in the typescript compiler that doesn't produce ES6 compatible code. In ES6 the static property inherticance is done by setting the `__proto__` of the subclass to point to the parent class constructor. This way everything is inherited using prototypal inheritance. What typescript does here is this:

```js
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
```

which doesn't copy the inherited properties, but only own properties. We use typescript successfully by compiling to ES6 instead of ES5.

**Comment by jocull** [comment]
Thank you! I will check out the ES6 compile target.

**Comment by jocull** [comment]
Looks like this was hotly debated and reached an unfortunately incompatible conclusion :(

https://github.com/Microsoft/TypeScript/issues/1601

**Comment by jocull** [comment]
When targeting ES5, it's actually more effective to use this:

Object['setPrototypeOf'](UserCustomer, Model);

// Below will not pick up instance methods, e.g. $beforeInsert
//

**Comment by jocull** [comment]
When targeting ES5, I found it's actually more effective to use this:

```
import { Model } from 'objection'

export class UserAccount extends Model<UserAccount> {
    public static get tableName() { return 'user_accounts'; }

    constructor() {
        super();
    }
}

Object['setPrototypeOf'](UserAccount, Model);

// Below will not pick up instance methods, e.g. $beforeInsert
// Model.extend(UserAccount);
```

You can use `Object['setPrototypeOf']` instead of `Object.setPrototypeOf` to work around TypeScript's definition issues in Node.js.

This way we get all the correct typing information, but we don't have some of the missing ES6 features not implemented in Node.js without special flags (e.g. default parameters)

**Comment by charlescapps** [comment]
Neither of these suggestions work for me.
* `TypeError: _objection.Model.extend is not a function`
* Calling `Object.setPrototypeOf` breaks everything because we have mixins (Objection Plugins) and those are lost when we call that.

So I'm kinda screwed for getting typescript to work properly with Objection right now...

**Comment by morsaPT** [comment]
@charlescapps Any luck on solving this? I'm having the same issue here and have no clue how to solve them.
