### ISSUE TITLE
runBefore unexpected behaviour

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#143]
Hi,

I'm experimenting with `runBefore` and `context` (v0.5.0-rc.5).

After starting server, on my first request server logs 'NaN' 'NaN'. However on subsequent requests server logs 5 5 as expected.

Is there something I miss?

```js
    query
        .context({
            onBuild: function(builder) {
                console.log(builder.context.xname);
            }
        })
        .where(function(b) {
            b.context.xname = 4;
        })
        .runBefore(function(data, qb) {
            qb.context.xname++;
            console.log(qb.context.xname);
        })
        .then((result) => {
        })
        .catch((err) => { throw err; });
```

Regards,

**Comment by koskimas** [comment]
`context` is a function, so you should be using it like this

```js
builder.context().xname = 'blaa';
console.log(builder.context().xname)
```

This line causes the `nan` since `xname` is undefined when the control reaches `runBefore`.

```js
qb.context.xname++;
```

It works for the subsequent calls because you set the `xname` property of the method `context` that is in the prototype :smile:

What are you trying to achieve with the call:

```js
.where(function(b) {
    b.context.xname = 4;
})
```

or is it just a test to see if the same context is passed there also?

**Comment by ozum** [comment]
This code was just for testing.

In real application I have several functions which modifies query dynamically according to configuration in hapi. I need to store data related to query, so that functions can make decisions based on situation.

**Comment by koskimas** [comment]
Can I close this or are there still some problems?

**Comment by ozum** [comment]
Thank you. Everything is clear now.
