### ISSUE TITLE
This query cannot be built synchronously. Consider using debug() method instead.

### ISSUE THREAD

**Issue by NajwaSM** [Vincit/objection.js#1474]
Hi, I try to query my statement and see how its written in mysql using to.sql() like this:
    const result = await TwoFactor.query()
      .findOne({
        userId: newUser.id,
        type: body.twoFactor,
        enabled: true,
      })
      .toSql();
    console.log(result);

but I get the error: This query cannot be built synchronously. Consider using debug() method instead.

what does it mean?..

**Comment by koskimas** [comment]
Some objection queries actually execute multiple database queries. For example `eager` can execute multiple querties, one after another. It first executes the first query (the root models) and then based on the result of the first one, it executes the second query (the relations of the root models) and so on. That's why `toSql` cannot synchronously return all the SQL that will be executed because we would actually need to execute the queries to know what the next ones will be.

Try to avoid `toSql`. it's broken in many ways in ojection. If you want to see what SQL gets executed, `.debug()` is a better method.

**Comment by koskimas** [comment]
In this case, only one query would be executed, and I don't really know why that fails :smile: I don't have any tests for `toSql` because I mean to get rid of it (or change the behavior completely) in 2.0.

**Comment by NajwaSM** [comment]
yes, true that. appreciate your reply :) thank you so muchhh
