### ISSUE TITLE
Override select statement at model level

### ISSUE THREAD

**Issue by thonythony** [Vincit/objection.js#1491]
Hello,

I try to use objection with knex-postgis. The insert is ok but when I do a select, my column geometry is not converted into geojson because I can't apply the postgis function into select statement... 
My question is quite simple. At model level, how or where can I tell objection to apply postgis function when selecting model ?

The current query generated by objection is : 
```
select "locations".* from "locations" where "locations"."event_id" in (?)
```

My target query : 
```
select st_asgeojson(geojson) as geojson from "locations"
```

Thanks for your help

**Comment by koskimas** [comment]
There's no way or place to modify a selection in the model level. That's because objection allows any query, subquery, join, CTE and whatever else to be executed. For objection to reliably hook into all selects, we would need to implement all database engines in javascript side :smile:

Depending on your use cases, you could add default selects using by overriding the query builder or the static `query` method of a model. Something like this

```js
class Location extends Model {
  static query(...args) {
    const query = super.query(...args)
    query.select('locations.*', raw('st_asgeojson(geojson)').as('geojson'))
    return query
  }
}
```

But that way you always get all columns because of the hardcoded `locations.*`. You could leave that out, but then you need to explicitly add it to all queries where you **do** want all other columns.

Another option is to always add `geojson` but only add `locations.*` if no other selects have been explicitly done. You can do that by utilizing the `onBuild` hook

```js
class Location extends Model {
  static query(...args) {
    const query = super.query(...args)

    return query.onBuild(builder => {
      query.select(raw('st_asgeojson(geojson)').as('geojson'))

      if (!builder.hasSelects()) {
        query.select('locations.*')
      }
    })
  }
}
```

Another option is to simple always explicitly select the `geojson`, you can add it as a modifier so that you don't have to repeat yourself.

```js
class Location extends Model {
  static modifiers = {
    selectGeoJson: query = query.select(raw('st_asgeojson(geojson)').as('geojson'))
  }
}
```

```js
Location.query().modify('selectGeoJson')
```

Let me know if any of these work for you

**Comment by koskimas** [comment]
Actually I'm not sure if the `onBuild` will work because it will be added as the first operation. Instead you could do that in `queryBuilder.execute`

```js
class LocationQueryBuilder {
  execute(...args) {
    if (!this.hasSelects()) {
      this.select('locations.*')
    }

    this.select(raw('st_asgeojson(geojson)').as('geojson'))
    return super.execute(...args)
  }
}

class Location extends Model {
  static QueryBuilder = LocationQueryBuilder
}
```

**Comment by thonythony** [comment]
Thanks a lot for your precious information about library mechanism and examples !

I used your `LocationQueryBuilder` and it works !
