### ISSUE TITLE
Why is .eager decpreciated in favor of .withGraphFetched / .withGraphJoined?

### ISSUE THREAD

**Issue by jdolearydl** [Vincit/objection.js#1619]
I would assume to allow for the split behavior (Fetched vs. Joined) but I'm wondering if there are any other reasons or if the functionality changed in any significant way?

**Comment by koskimas** [comment]
The motivation was to make it obvious that they are two different methods that do very different things. Before, we had the `eagerAlgorithm` method (and static model property) that made it possible to modify how `eager` worked. That lead to a lot of confusion, because modifiers, among other things, work differently with different algorithms. People assumed that everything would just work if they switched the algorithm, but it often broke something because of the small differences.

Also IMO `withGraphFetched` is more descriptive than `eager` which isn't really a verb.

**Comment by jdolearydl** [comment]
Great explanation, thank you
