### ISSUE TITLE
Getting props from a related model class via relations

### ISSUE THREAD

**Issue by johanneslumpe** [Vincit/objection.js#163]
I have two models `A` and `B`, which are related to each other. When inserting a model `A` i'd like to fetch a static value from model `B`. @koskimas What's the best way to achieve this? I saw that we have access to a `getRelation` method, which I could use to get the prop like this:

```js
this.getRelation('something').relatedModelClass.someStaticProp
```
Would you consider this acceptable and bless the usage of `getRelation` and `relatedModelClass`? Or are those internals which might just change at any given time?

**Comment by koskimas** [comment]
Anything that is not documented in the API docs can change at any given time. I'm hesitant to add the `getRelation` method to public API since that would pull a huge hairball of other classes with it that would also need to be documented and their API locked.

`getRelation` most likely won't change any time soon, but you cannot trust this 100%.

**Comment by johanneslumpe** [comment]
@koskimas I understand. Do you have a better idea how to achieve the above?

**Comment by koskimas** [comment]
Even if I change its name or otherwise refactor it, there will always be similar way to get the related model class. Maybe you could create your own utility method that calls `getRelation` and if `getRelation` is ever removed or changed, all you need to do is to change your utility method?

**Comment by johanneslumpe** [comment]
@koskimas That's what i already did :) Good to know, I'll close this for now then 👍
