### ISSUE TITLE
Since 2.0 `ModelClass` does not have `#query` In typings

### ISSUE THREAD

**Issue by francocorreasosa** [Vincit/objection.js#1638]
In version `1.x` `ModelClass<T>` works fine.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4152942/71771763-5da7ef80-2f1f-11ea-9cfb-30543a4078ed.png">

Now, in `2.0+` an typing error is thrown on the exact same code.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4152942/71771785-9942b980-2f1f-11ea-9d75-3fa7b3752b86.png">

Is this expected, what would be the correct usage?

Thanks a lot 😄

**Comment by koskimas** [comment]
The `ModelClass` type isn't really useful in 2.0 anymore. It's used only internally. You can use `typeof Model`

**Comment by francocorreasosa** [comment]
@koskimas Sounds good, thanks a lot!

**Comment by patricklol22** [comment]
since I have updated to version 2 I have a similar error

![image](https://user-images.githubusercontent.com/16104507/71786302-2eba7800-300a-11ea-9be8-04e6e385c7eb.png)

I used to have a workaround with `ModelClass<any>` inside the constructor but with `typeof Model` i get  `'Model' is assignable to the constraint of type 'M', but 'M' could be instantiated with a different subtype of constraint 'Model'`.

**Comment by koskimas** [comment]
@patricklol22 you would need to use `typeof M` but typescript doesn't support it. We may need to bring back the old `ModelClass` type for this. I haven't considered generic usage like this.

**Comment by koskimas** [comment]
@francocorreasosa @patricklol22 a new version 2.1.0 has been released and the old `ModelClass` type is back. Let me know if you run in to trouble with it.

**Comment by MatiasMinian** [comment]
@rathax Did you manage to solve this?
I'm trying something pretty similar than you but seems it doesn't work, even when using `ModelClass<M>`

```
export class BaseService<M extends Model> {
  constructor(protected readonly modelClass: ModelClass<M>) {}

  async findById(id: number): Promise<M> {
    return this.modelClass.query().findById(id)
  }
}
```

This is throwing this error:
```
Type 'Model' is not assignable to type 'M'.
  'Model' is assignable to the constraint of type 'M', but 'M' could be instantiated with a different subtype of constraint 'Model'.
```

But AFAIK my function should be able to return `Promise<M>` instead of `Promise<Model>`. If not I lose the types when extending this `BaseService`

Not sure if this is a bug or I'm missing something relate to Objection and/or TS

**Comment by rathax** [comment]
> @rathax Did you manage to solve this?

not really, sorry.

had to use modelClass: any
