### ISSUE TITLE
default array type column to empty array "[ ]" instead of null

### ISSUE THREAD

**Issue by adprajwol** [Vincit/objection.js#1715]
For an array type column, currently I am using default in jsonSchema to insert empty array instead of the usual **null**

            properties: {
                name: { type: 'string', minLength: 5 },
                email: { type: 'array', uniqueItems: true, items: {
                        type: 'string',
                        format: 'email'
                    },
                    default: []
                },

Is there a way to check if the column type is array in $beforeInsert or $beforeUpdate hooks and set default from there?

**Comment by koskimas** [comment]
You can access the json schema through `this.constructor.jsonSchema` in the hooks.

**Comment by TimNZ** [comment]
@koskimas 

Is {default:[] } for arrays supposed to work in jsonSchema, because it is generating SQL that Postgres doesn't like for an array column:

partial schema:
```
properties: {
   tags: {type: array, default: [], items: { type: 'string' } },
   ...
}
```

```
models.Connection.query()..insert({type: 'admin', from: 1, to: 2})
```

```
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, '[]', 2, 'admin' ],
  __knexQueryUid: 's4jcp_JbCzeoijJ00UXI-',
  sql: 'insert into "connection" ("from", "tags", "to", "type") values (?, ?, ?, ?) returning "id"',
  returning: 'id'
}
```

Error:
```
DataError: insert into "connection" ("from", "tags", "to", "type") values ($1, $2, $3, $4) returning "id" - malformed array literal: "[]"
```
I can't see a clean way of doing what @adprajwol wanted as by the the time you get to $beforeInsert and check for null and set a value on the column, you must have already used val() to cast a javascript array to a ValueBuilder instance, and the bindings have already been defined.
You can see the $$queryProps is set on the model instance passed into $beforeInsert in the below screenshot.

This works as expected using val() ValueBuilder helper in the original insert(), you can see bindings for each item in the array:

```
models.Event.query().insert({name: 'Test event',status: 'planning',tags: val(['tag1','tag2']).asArray()})
```

```
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '{}', 'Test event', 'planning', 'tag1', 'tag2' ],
  __knexQueryUid: 'dJFQtmHDPSH1JGyjNyxuZ',
  sql: 'insert into "event" ("data", "name", "status", "tags") values (?, ?, ?, ARRAY[?, ?]) returning *',
  returning: [ '*' ]
}
```
![image](https://user-images.githubusercontent.com/1051701/104085599-affbb900-52b5-11eb-91ef-eb6ee6a99155.png)
