### ISSUE TITLE
ModelClass.relatedQuery() does not set alias anymore in Objection 2

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#1720]
I'm seeing a difference in `ModelClass.relatedQuery()` between Objection 1 and 2, and it looks like it may be a bug in Objection 2. I've managed to narrow it down to this:

Objection 1

```js
console.log(ModelClass.relatedQuery('relationName').tableRefFor(ModelClass))
-> 'relationName'
```

Objection 2

```js
console.log(ModelClass.relatedQuery('relationName').tableRefFor(ModelClass))
-> 'ModelClass'
```

For now I'm working around it by overriding `relatedQuery()` in my base `ModelClass`, but Objection 2 should probably not change its behavior here?

```js
  static relatedQuery(relationName, trx) {
    return super.relatedQuery(relationName, trx).alias(relationName)
  }
```

**Comment by wswoodruff** [comment]
I also ran into this issue — 

The use-case that brought it up was writing a `relatedQuery` with a modifier that used `tableRefFor`

**Comment by koskimas** [comment]
I don't think I can change this anymore. The problem is that all related queries are now built using the static `relatedQuery` method. For example

```js
const pets = await person.$relatedQuery('pets')
```

is implemented as

```js
await Person.relatedQuery('pets).for(person)
```

While the old `relatedQuery` wasn't used that much by people, but the `$relatedQuery` was, I think we need to follow the `$relatedQuery` semantics, which didn't set the alias. If we now changed `relatedQuery` to set the alias, we would break a lot of code.

I wish I had thought of this when I implemented the new `relatedQuery('pets').for(1)` API. Giving an alias would probably have been better.

**Comment by lehni** [comment]
You could introduce an internal static helper that doesn't set the alias, use that in both `$relatedQuery()` and the static `relatedQuery()`, but set the alias after the call in the static `relatedQuery()`. That way, you'd not change the behavior of `$relatedQuery()` and still remain backward compatible.
