### ISSUE TITLE
sort by and limit on n:m associations

### ISSUE THREAD

**Issue by hashcutdev** [Vincit/objection.js#1733]
First off, thanks for an awesome project! I moved over from sequelize when I ran into limitations with that ORM, and I find my queries and model code is much simpler with Objection. I'm using v2.1.3 with feathersjs and I'm wondering if it's possible to do sorts and limits through a join table. I have 3 tables, games, streamers, and highlights, along with join tables games_streamers, and highlights_streamers. Basically, each game is played by multiple streamers, who can in turn play multiple games. And each streamer has multiple highlights, and each highlight clip can involve multiple streamers.

I'd like to query games, and retrieve all streamers for each game, but then for each streamer, only retrieve the latest highlight.

The query:
``games.query().withGraphFetched('[streamers.highlights]')``
will get me all streamers, and *all* highlights that a streamer has, which is not what I want.

I've tried using modifiers e.g.:
```
games.query().withGraphFetched('[streamers.highlights(onlyOne)]')
    .modifiers({
            latestOne(query) {
                query.orderBy('created_at', 'DESC').limit(1);
            },
        });
```

However, this just finds the latest highlight from the whole DB, which means only one streamer will have a highlight record attached.

I've seen issue #1356 and I wonder if this is a related limitation? If so, is there a way around it, perhaps by manually joining through the join table? I currently have the relationships defined as ``Model.ManyToManyRelation`` but I can manually specify the hasManyRelation and belongsToOneRelation on the join table if that would help me.

**Comment by koskimas** [comment]
The problem is that `withGraphFetched` fetches the data in an optimized way. In case of your query:

1. Use 1 query to fetch all games that match the filters
2. Use 1 query to fetch all streames for **all** games using a `where in` query
3. Use 1 query to fetch all highlights for **all** streamers of **all** games using a `where in` query.

Now as you see, only three queries get executed. Only one single query is executed to fetch  all highlights and you are calling `limit(1)` for that query.

There's no easy solution for this except to do some SQL magic. This could work (on postgres):

```js
games.query()
  .withGraphFetched('[streamers.highlights(onlyOne)]')
  .modifiers({
    latestOne(query) {
      query.orderBy('created_at', 'DESC').distinctOn('highlights_streamers.streamer_id')
    },
  });
```

Note that you need the latest version of objection for `distinctOn` to work.

https://stackoverflow.com/questions/3800551/select-first-row-in-each-group-by-group
