### ISSUE TITLE
Bidirectional relationship definitions

### ISSUE THREAD

**Issue by thapar** [Vincit/objection.js#1738]
Firstly, thank you for a great library, and especially for great documentation!

Coming from Python, I used SQLAlchemy extensively and did like a particular feature for relationship definitions where it could be designated with [a `backref` argument](https://docs.sqlalchemy.org/en/13/orm/backref.html), allowing for a relationship to only need to be defined in one table and the reverse relationship would be automatically created.

Would it be possible to have a similar feature added to objection.js?

Thank you again for your great work on objection.js.

**Comment by koskimas** [comment]
Thank you!

Objection is very different from traditional ORMs lie SQLAlchemy, as you probably have noticed. There's very little magic going on and most things are very explicit, and that's by design. Objection allows you to do all kinds of weird things with your relations, like adding modifiers to them. For example, you could have a relation mapping like this:

```js
dogs: {
  relation: Model.HasManyRelation,
  modelClass: Pet,
  join: {
    from: 'person.id',
    to: 'pets.ownerId'
  },
  modify: query => query.where('species', 'dog')
}
```

Now, what would be the reverse of this relation? It would be a relation that only produces relations to `Pet`s whose species is `dog` or something like that. The modifier can have any kind of arbitrary query in it, so it wouldn't even be possible to reverse it.

This is just one example. Anyway, you only need to define the relations once. That shouldn't be a significant part of the development process for any non-trivial app.
