### ISSUE TITLE
Why is model empty in a custom Validator?

### ISSUE THREAD

**Issue by wa4-fearless-otter** [Vincit/objection.js#1759]
The [documentation](https://vincit.github.io/objection.js/recipes/custom-validation.html#examples) states that the `model` arg of the function `validate` in a custom `Validator` can be empty. Which is exactly what I'm experiencing.

But i need the model to get my custom static `validation` function. Is there some way to achieve this?

**Comment by koskimas** [comment]
The model is empty because it is not yet populated. The validation is done first, BEFORE populating the model so that you don't get a model with invalid values. That's kind of the point of validation right?

The values are in the `args.json` property as it's clearly stated in the documentation you linked:

```js
    // The properties to validate. After validation these values will
    // be merged into `model` by objection.
    const json = args.json;
```
