### ISSUE TITLE
Any examples for MariaDB/MySQL master slave replication?

### ISSUE THREAD

**Issue by brandonpsmith** [Vincit/objection.js#176]
I have resulted to having two global objection models. One for reads (slave) and one for writes (master). I did see multi-tenancy in the docs. Isn't that more for "on the fly" db connections. Any ideas on how to architect and manage read write connections with objection?

**Comment by koskimas** [comment]
Sorry I haven't answered this. I actually had to google the topic, since I have never really used MySQL in production work.

So basically you can only have one model, lets say `Movie` and then you can simply `bind` it the the given database connection. Where you do this, is up to you and objection.js has no opinions about it. Here's how it works:

```js
const master = Knex(masterConfig);
const slave = Knex(slaveConfig);

class Movie extends Model {
  static tableName = 'Movie';
}

const MasterMovie = Movie.bindKnex(master);
const SlaveMovie = Movie.bindKnex(slave); // Not the best name :|

await MasterMovie.query().insert({foo: 'bar'});
let movie = await SlaveMovie.query().where('foo', '=', 'bar');
```

What `bindKnex` actually does is that it creates a subclass of `Movie` and sets its database connection.

**Comment by koskimas** [comment]
Did you solve this? If so, please close this.

**Comment by erwaseem123** [comment]
Hi @koskimas,

Yes this is working but the server respond very slow when in heavy traffic (in case of heavy load utilization of CPU and mysql is ~16%).

Thanks

**Comment by alvin30595** [comment]
Hi @erwaseem123 may i know why it overloaded the server CPU ya?
