### ISSUE TITLE
Typescript Compiler confused about Knex import in Mixin Typings

### ISSUE THREAD

**Issue by Zuzuesque** [Vincit/objection.js#1770]
Objection 2.1.5
Typescript 3.9.3

**Issue:**
When using mixins in Typescript the compiler gets confused about the 'Knex' type, throwing the following error: `Return type of exported function has or is using name 'Knex' from external module [...] but cannot be named.ts(4058)`

**How to reproduce**
```ts
import { Model } from 'objection';

export function Mixin(options = {}) {
  return function<T extends typeof Model>(Base: T) {
    return class extends Base {
      mixinMethod() {}
    };
  };
}
```
Taking the Mixing example from the homepage, dropping it into a fresh project. (Note: the example appears to have other issues, at least in TS 3.9.3, but those I can solve... the Knex error however won't go away no matter what I do.) For all other purposes, typings appear to work, however.

Experimenting a little with Objections typings I could solve the issue by replacing:
```
import * as knex from 'knex';
import Knex = require('knex');
```
in index.d.ts with:
```
import knex from 'knex'
```

In my project that solved the issue with the Knex error without adding any others... but it is a little weird. Though I guess the second import is a strange combo of commonJS and ES Modules... so that may throw the compiler?

**Further Info**
Some background to the issue: https://github.com/microsoft/TypeScript/issues/5711

**Comment by koskimas** [comment]
Thanks for bringing this up. I don't know why we are currently importing knex like that :thinking: I'll fix this soon.

**Comment by koskimas** [comment]
@Zuzuesque could you test the master branch to see if the fix in 53e47bc works for you?

**Comment by Zuzuesque** [comment]
@koskimas I tried the latest version, but it still doesn't work.

I dug some more into the issue and found that knex itself doesn't do a proper default export of knex. It does ```export = Knex;``` rather than ``` export default Knex``` or ``` export { Knex }```. If I patch Knex to use either of them the Objection typings work for mixings too.

(The fact ```import knex from 'knex``` actually works seems to be something of a fluke.)

I am not sure why this would be an issue only for mixings... as typings seem to work in every other usecase I have. I will open an issue for Knex though, as it seems to be the real culprit.

**Comment by kibertoad** [comment]
@lorefnon

**Comment by lorefnon** [comment]
@Zuzuesque IMHO `export = Knex` is the only way to properly type the knex-style commonjs export that works irrespective of whether [esModuleInterop](https://www.typescriptlang.org/v2/tsconfig#esModuleInterop) is set to true or not in tsconfig.json (You may have it set to true but the same can't be expected of every knex consumer). 

In fact `import =` and `export =` are complementary features that were added in TS with the specific intent to model commonjs style exports and they are the [officially recommended](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) way to type commonjs modules. 

`export { Knex }` will not be correct if we don't also change the knex.js export to be `exports.Knex = Knex` instead of `module.exports = Knex`. We make that change if it makes someone's life easier but it is most certainly not an "accident" that the recommended usage works.

**Comment by berndartmueller** [comment]
I have the same issue. Is there a working fix for it?

**Comment by elby22** [comment]
@berndartmueller did you manage to find a workaround for this? I'm running into this with my mixins as well.
