### ISSUE TITLE
[docs] How to Model Schemas in typescript

### ISSUE THREAD

**Issue by panigrah** [Vincit/objection.js#1774]
Documentation suggests that we should avoid having to defined schema in the models to reduce the burden on managing schema in migrations and also in the models. 

But the examples listed seem to always have schema defined in the model also. 

1. What is best practice?

2. If I am defining schema in the model to help with typscript, then how should I be using "?" or "!" to represent nullable fields?

**Comment by koskimas** [comment]
You should define tupescript types for the fields and relations. The docs talk about objection not defining the database schema in the model. As in not generating database tables and columns based on models.

**Comment by panigrah** [comment]
@koskimas is there a preferred way to define typescript models? 

Or do I just use how the model is defined in Person.ts in the koa example?
examples/koa-ts/models/Person.ts

**Comment by jeremy-w** [comment]
i write the model properties like:

```ts
// Imports we'll need to flesh out our class definition.
import { Model, QueryBuilder, RelationMapping } from 'objection'
// Import related model type
import Whatever from './whatever'

export default class Something extends Model {
  static get tableName(): string {
    return 'something'
  }

  declare somethingKey: number
  static get idColumn(): string {
    return 'somethingKey'
  }

  // plain old not null number field
  declare something: number
  // key for a related Whatever - see |whatever| defined next, and |relationMappings| below
  declare whateverKey: number
  /** Fetched using relation 'whatever'. */
  declare whatever?: Whatever

  static get modifiers(): {
    filterSomethingIs(query: QueryBuilder<Something>, value: number): void
  } {
    return {
      filterSomethingIs(query: QueryBuilder<Something>, value: number) {
        void query.where(`${query.tableNameFor(Something)}.something`, value)
      },
    }
  }

  static get relationMappings(): {
    whatever: RelationMapping<Whatever>
  } {
    return {
      whatever: {
        relation: Model.BelongsToOne,
        from: `${Something.tableName}.whateverKey`,
        to: `${Whatever.tableName}.${Whatever.idColumn}`,
      },
    }
  }
}
```

using `declare` says "this property should be there" without generating any defineProperty calls. see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier this i see as an improvement over the example's use of properties defined on the class itself. also note that i eschew use of `!`.

whether written my way or as shown in the koa-ts example, i'm running into issues around **nullable related objects** and graph operations. the current typings for `PartialModelGraph` exclude undefined but not null in testing for `relatedPropertyType extends Model`, so if you have `declare nullablePet?: Pet | null`, it thinks the `nullablePet` property is not a Model, and instead expects a full `Expression` - so a full `Pet` or `null` (roughly), rather than the usual `PartialModelObject<Pet>`. i'm not yet clear whether we are expected to "just treat undefined as null", or if this is an overlooked case in the typings. but at runtime, a `null` (you fetched the relation, but it's set to null rather than a key for this - a Pet with no Person owner, say) vs `undefined` (you haven't even fetched that relation yet, though if it's a BelongsTo relation, you already know what you'll find when you do fetch by checking the key value on your current object) distinction _does_ exist, so i'm leaning towards "overlooked case". 😬

**Comment by falkenhawk** [comment]
@jeremy-w about `PartialModelGraph` and nullable fields like `nullablePet?: Pet | null`, this might be interesting for you: 
https://github.com/ovos/objection.js/pull/16

since we haven't published our fork to npm (might do soon, but for now you might simply point your package.json entry to github url + tag or branch) but here is a patch file at hand:
```diff
diff --git a/node_modules/objection/typings/objection/index.d.ts b/node_modules/objection/typings/objection/index.d.ts
index c7efd99..ce8b322 100644
--- a/node_modules/objection/typings/objection/index.d.ts
+++ b/node_modules/objection/typings/objection/index.d.ts
@@ -222,15 +222,19 @@ declare namespace Objection {
    * Just like PartialModelObject but this is applied recursively to relations.
    */
   type PartialModelGraph<M, T = M & GraphParameters> = {
-    [K in DataPropertyNames<T>]?: Defined<T[K]> extends Model
-      ? PartialModelGraph<Defined<T[K]>>
-      : Defined<T[K]> extends Array<infer I>
+    [K in DataPropertyNames<T>]?: null extends T[K]
+      ? PartialModelGraphField<NonNullable<T[K]>> | null // handle nullable BelongsToOneRelations
+      : PartialModelGraphField<T[K]>;
+  };
+
+  type PartialModelGraphField<F> = Defined<F> extends Model
+    ? PartialModelGraph<Defined<F>>
+    : Defined<F> extends Array<infer I>
       ? I extends Model
         ? PartialModelGraph<I>[]
-        : Expression<T[K]>
-      : Expression<T[K]>;
-  };
+        : Expression<F>
+      : Expression<F>;

   /**
    * Extracts the property names (excluding relations) of a model class.
    */
```
