### ISSUE TITLE
[TypeScript] What's the best way to type a select result?

### ISSUE THREAD

**Issue by giopetris** [Vincit/objection.js#1787]
I'm performing a select query just fetching the ID and counting the results grouping them by some logic, here's a sample code:

```
const result = ((await this.myModel
      .query()
      .select('myModel.id')
      .count('myModel.id')
      .joinRelated('fooModel')
      .where('fooModel.isActive', true)
      .groupBy('myModel.id')) as unknown) as Promise<ResultItem[]>;

...

interface ResultItem {
   id: string;
   count: number;
}
```

As you can see, I'd like to stop enforcing the type that way by casting to `as unknown` and then `as Promise<ResultItem[]>`. Is there a better way to do it? Maybe passing a generic. I really couldn't find a better solution for it, would appreciate any help on this.

**Comment by koskimas** [comment]
Objection query results are always model instances. So you only have one option if you want to use objection queries: add the `count` column to your model, even though it isn't a property on that model.

Another option is to drop down to knex. Since the result is not a model instance, it makes sense. Something like this should allow you to utilize the knex types:

```ts
const result: ResultItem = await this.myModel
      .query()
      .joinRelated('fooModel')
      .toKnexQuery()
      .select('myModel.id')
      .count('myModel.id')
      .where('fooModel.isActive', true)
      .groupBy('myModel.id')
```
