### ISSUE TITLE
[BUG] $query().patch incorrectly mutates model instance

### ISSUE THREAD

**Issue by prolificrohit** [Vincit/objection.js#1791]
Original Issue #1777 

> I am migrating my code from version 1.x to version 2.x and saw a weird problem with the patch function which looks like a breaking change but nothing seems to be mentioned about it in the migration doc
> 
> Minimal Code:
> 
> // person is a model instance
> console.log("Before", person);
> person.$query().patch({first_name: 'prolific'});
> console.log("After", person);
> Before Patch:
> 
> Before Person {
>   id: 1,
>   first_name: 'Rohit',
>   last_name: 'Agarwal'
> }
> After Patch in v1.6:
> 
> After Person {
>   id: 1,
>   first_name: 'prolific',
>   last_name: 'Agarwal'
> }
> After Patch in v2.2:
> 
> After Person {
>   id: undefined,
>   first_name: 'prolific',
>   last_name: undefined
> }
> Once the patch is executed the original model instance mutates and all the old fields are set to undefined (including the primary field 'id') while keeping only the data that is patched.
> 
> Expected Behavior:
> Either the model instance should mutate while keeping the old fields and patching the new fields (like in v1.x) OR the model should not mutate at all (which I personally would not like but makes sense if decided). Current behavior (in v2.x) seems odd because it is both mutating as well deleting the old fields.

@koskimas I am adding a new issue since the old one was closed automatically without a comment for some reason (not sure if it was intentionally closed by you or done by some automated bot). I do not know any other way to ask for help on this. Apologies in advance if this is against the rules of this repo.

Any help would be really appreciated.

**Comment by koskimas** [comment]
This is not done by objection. You probably have some 3rd party plugin enabled that does something funky, or you have overridden some hook incorrectly.

If you can provide a standalone reproduction I can easily debug, I can take a look.

**Comment by koskimas** [comment]
You can use the `reproduction_template.js` file found in the repo root as a starting point.

**Comment by prolificrohit** [comment]
@koskimas Thanks for your comment. Really appreciate it.

Since I was not using any hooks or any plugins linked to this throughout my code, i tried reproducing the bug with the template provided and to my surprise the code worked correctly. I was using typescript so I thought it has something to do with class properties. I commented them and it worked. Then I started setting up a typescript repo for you and then again to my surprise the code worked correctly even with the class properties.

After comparing my original code and the newly created ts repo, I managed to find the problem. I was using babel along with [babel-plugin-proposal-class-properties](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties) which must be causing the issue since this plugin initializes the variables with undefined by default. Removed it and everything worked as expected.

Turns out the problem was not with the code but with the compiler and I was just looking at the wrong place. Pulling my hair with this from many days. Apologies for wasting your time.

Thanks.

**Comment by IlyaSemenov** [comment]
I've stumbled upon the same problem after switching from ts-node to babel7 with typescript.

With babel (and babel-plugin-proposal-class-properties) one must explicitly _declare_ class members for relation mappings:

```ts
class PersonModel extends Model {
	static get relationMappings() {
		return {
			orgs: {
				relation: Model.ManyToManyRelation,
				modelClass: OrgModel,
				join: {
					from: 'users.id',
					to: 'orgs.id',
					through: {
						from: 'org_persons.user_id',
						to: 'org_persons.org_id',
					},
				},
			},
		}
	}

	declare orgs?: OrgModel[] // not simply orgs?: ...
}
```

For that to work, one should also enable `allowDeclareFields` in `.babelrc`:

```
{
	"presets": [
		[
			"@babel/env",
			{
				"targets": {
					"node": true
				}
			}
		]
	],
	"plugins": [
		// Must come *before* proposal-class-properties
		[
			"@babel/transform-typescript",
			{
				"allowDeclareFields": true,
			}
		],
		"@babel/proposal-class-properties"
	]
}
```

**Comment by vvo** [comment]
I am using Next.js + TypeScript and having the same issue with .patch({one: "field"}) making every other field undefined. But I can't find the root cause for that and which plugin to disable.

If someone is experiencing the same issue, let me know :)

**Comment by vvo** [comment]
Answering myself and anyone having weird behaviors when using .patch(). Please @koskimas if you can confirm/comment that would be awesome! We could maybe then update the documentation.

1/ .patch() do modify instances, so if you use const `instance = Model.query().where({id: 1});` and then `instance.$query.patch({name: "hello"})` then instance.name will be "hello". Which is handy but can be surprising because not documented at the moment (there are other methods mutating instances I believe like some after init graph fetching methods)

2/ If you're using class properties for models (like shown here: https://github.com/Vincit/objection.js/blob/master/examples/koa-ts/models/Animal.ts) and TypeScript then chances are that you'll encounter issues like:
- all non selected fields defaulting to `undefined` when using: .modifyGraph("children", builder => builder.select("name")) which may or may not be what you want
- .patch mutating the current instance with all fields (but the ones modified) being undefined

The right way to solve your problems is to ensure that you define your model classes using this syntax:

```ts
class Person {
  declare id: number;
  declare name: string;
}
```

And then configure babel this way:

```txt
{
  "presets": ["next/babel", ["@babel/preset-typescript", {"allowDeclareFields": true}]]
}
```

Whatever you do you have to ensure that `["@babel/preset-typescript", {"allowDeclareFields": true}]` runs before any of the:

```
@babel/plugin-proposal-class-properties
@babel/plugin-proposal-private-methods
@babel/plugin-proposal-decorators
```

Or you'll get this error: "TypeScript 'declare' fields must first be transformed by @babel/plugin-transform-typescript"

A few things to note:
- babel plugins runs before presets
- babel plugins order follow array order (first in the array gets to be loaded first)
- babel presets runs backwards (last preset in the array gets run in first). This shit is crazy.

Good luck!

**Comment by rclmenezes** [comment]
@vvo thanks! I wish this thread was more Google-able. I spend a lot of time on this...

This is simply a transpiling issue. `ts-node` didn't have this problem. When Babel sees:

```typescript
class User extends Model {
    id!: number;
}
```

It transpiles it to:

```javascript
...
function T(e, t, n) {
  return (
    t in e
      ? Object.defineProperty(e, t, {
          value: n,
          enumerable: !0,
          configurable: !0,
          writable: !0,
        })
      : (e[t] = n),
    e
  );
}
const w = Object(S.b)("User");
class _ extends A.b {
  constructor(...e) {
    super(...e),
      T(this, "id", void 0);
  }
}
```

void 0 is a slightly smaller way of saying "undefined" :)

`declare` tells Babel that it's simply a Type declaration to output and that the property should not be added to code.

Oof!

**Comment by waynebloss** [comment]
I could only get this working with the following babelrc:

```json
{
  "presets": [
    "@babel/preset-env",
    [
      "@babel/preset-typescript",
      {
        "allowDeclareFields": true
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    [
      "@babel/plugin-transform-typescript",
      {
        "allowDeclareFields": true
      }
    ],
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

If I take away either the preset option or the plugins option, I get the error `TypeScript 'declare' fields must first be transformed by @babel/plugin-transform-typescript.`

**Comment by danielvy** [comment]
I've spend long time trying to figure out what's going on before I found this issue.

This isn't a configuration issue. Babel's, and other tools, transpiling differences are simply the trigger but I think this is an Objection problem that needs to be addressed. 

Basically, it boils down to whether the model's class in the resulting javascript has these properties defined. For existing properties, `patch` will overwrite them on the model's instance. This can be easily reproduced with plain javascript, without any transpiling tools.

This behavior is unexpected and incorrect, in my opinion. `patch` shouldn't modify the instance beyond the properties provided to it. That is the whole point of `patch`, it doesn't update the database, why should it modify the existing model instance? 

I think this issue should be reopened, or at the very least, this behavior should be documented.

**Comment by mogzol** [comment]
Just ran into this as well, although I'm not using Babel. It turns out the issue was caused by me using a tsconfig target of `es2022`, which causes the `useDefineForClassFields` tsconfig settings to be true. See here for more info:

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

The notable point from there is:

>  - Declarations are always initialized to undefined, even if they have no initializer.

In order to fix this, you have to add a `declare` modifier to all of your model properties, which will stop them from being intialized to undefined:

```typescript
class Person extends Model {
  public declare id: number;
  public declare name: string;
  ...
}
```
