### ISSUE TITLE
Relation Mapping Filter not working as expected.

### ISSUE THREAD

**Issue by fabiomartins87** [Vincit/objection.js#182]
I have his relation set on my model: 

```
count: {
                relation: BaseModel.HasOneRelation,
                modelClass: __dirname + '/activity_count',
                filter: query => query.select('reactions_count'),
                join: {
                    from: 'activity_actions.activity_id',
                    to: 'activity_count.activity_id'
                }
}
```

Without filter property it works just fine and it returns all fields from the activity_count model.
Although, when I use the filter to select only 1 single field it always returns null, every single time. 
The output of the query is correct and I've manually tested and it should return the result, but it always returns null. Any idea?

**Comment by koskimas** [comment]
You need to also select the relation property:

```js
filter: query => query.select('reactions_count', 'activity_id')
```

otherwise the query system doesn't know to which parent the fetched child row belongs to. This could be fixed for the trivial cases when you only fetch a relation for one single parent, but it would break in more complex eager cases.

It would be possible to add the needed columns implicitly to the select clause and then remove the properties before returning the models, but that would not be easy to implement.

**Comment by fabiomartins87** [comment]
Thanks @koskimas ! It works now and makes total sense.
