### ISSUE TITLE
Migrate file empty

### ISSUE THREAD

**Issue by TechComet** [Vincit/objection.js#1836]
Migrate not work

I do migrate my project but output is empty

```
exports.up = function(knex) {
  
};

exports.down = function(knex) {
  
};
```

**Comment by koskimas** [comment]
You need to write the migration files yourself. There's no automatic migration file genwration.

**Comment by TechComet** [comment]
Ah .. why ?
I have an idea how to write it
I need some time to write automatic migration
It might need modification from you as I don't know much about jsonSchema

**Comment by koskimas** [comment]
Because it is impossible to implement well. The model doesn't describe the schema well enough, and it is impossible to create automatic migrations except for very very simple cases. As soon as you write anything more complex or use any features of the relational database, you need to write the migrations by hand anyway.

Objection doesn't implement automatic migrations by choice. If you need stuff like that, objection is not the tool you should be using.
