### ISSUE TITLE
jsonb_set - any equivalent method or drop down to raw SQL to perform?

### ISSUE THREAD

**Issue by makeitrein** [Vincit/objection.js#187]
Hey all - just sanity checking here - would love to update a postgres json column, but don't see a better way than querying my model, modifying the json object, and resaving. 

Has anyone done anything like this w/ Objection and Knex in a clean manner? Thx!

**Comment by allxie** [comment]
+1

**Comment by fl0w** [comment]
Unless I'm mistaken, object manipulation functionality was added in `postgresql 9.5`, and so the original work flow was what you just described - fetch entire object, manipulate in application and save the updated object in full. 

If anything about this gets added, I purpose adding some warning regarding compatibility for older pg servers.

**Comment by koskimas** [comment]
You have to use raw SQL or save the entire object at the moment. Is @elhigu (our jsonb mastermind) interested in taking this on?

**Comment by elhigu** [comment]
I could implement this one, but I'm not sure about the API how to support it. 

Trival way would be to just add some `.updateJsonColumn(...)` custom method, other would be to create some kind of wrapper function for JSON column update value which is interpreted as partial update and implemented with `jsonb_set`...

Any ideas?

**Comment by koskimas** [comment]
so the second option would look something like this:

```js
const jref = Person.jsonRef;

Person
  .query()
  .patch(jref('foo.bar.baz'), 100);

Person
  .query()
  .patch({
    normalCol: 'lol',
    [jref('foo.bar.baz')]: 100
  });
```

I think this would be pretty cool. Isn't a function like `jref` here something you have considered for all jsonb queries? So that we could deprecate the special `whereJson*` methods?

**Comment by fl0w** [comment]
What you described @koskimas looks to be super clean, I love it.

**Comment by elhigu** [comment]
Actually since http://vincit.github.io/objection.js/#fieldexpression which is used to refer json fields in queries is superset of knex's schema, table / column reference string we could maybe use it directly:

```js
Person
  .query()
  .patch({
    normalCol: 'lol',
    'jsonCol:foo.bar.baz': 100
  });
```

And use the `ref` syntax, when reading value from other json field (or any other column) and avoid using `knex.raw` directly:

 ```js
Person
  .query()
  .patch({
    normalCol: ref('jsonCol:foo.bar.baz'), // maybe just ref is enough to be able to use it anywhere
    'jsonCol:foo.bar.baz': ref('normalCol')
  });
```

This breaks if someone uses `:` in their column names though... but knex already breaks if `.` is used so probably its ok... any other drawback on this approach?

**Comment by koskimas** [comment]
Even better! Can't see any other drawbacks but the possible `:` in a column name. Maybe we could add a setting that disables the json column syntax for the normal methods.

**Comment by elhigu** [comment]
I started working on this + ref() support to reduce need for knex.raw everywhere.

**Comment by makeitrein** [comment]
Thx @elhigu! Definitely a boon to our company's code base.

**Comment by koskimas** [comment]
@elhigu I actually started looking into this once, but realized that the whole architecture needs to be somewhat modified. I don't remember all the obstacles, but they were related to the way objection strips all `raw` expressions, `QueryBuilders` and other "non-primitives" from the objects in the `$setJson` method of `ModelBase`. The new `raw` and `ref` wrappers need to be stripped there also, but we need the query when we merge them back to the model in `$$toJson`. There is no way to pass the query builder to that method, and I don't think we shouldn't pass it there so we need to move the stripping stuff somewhere else. I tried moving it to the `UpdateOperation` and `InsertOperation` methods, but that doesn't work because of how `insertWithRelated`.

Just remember to write tests for `insertWithRelated` as you do this and you'll find the same problems fast. The `raw`, `ref` and other wrappers should work in any object (nested or otherwise) with `insertWithRelated`.

**Comment by elhigu** [comment]
@koskimas Thanks for the heads up, I'll keep going until I hit the wall. Probably some of the stuff will be useful (like bunch of test cases I'm writing for the feature).

**Comment by koskimas** [comment]
I didn't mean you will hit a wall. I found the problems after couple of days work. I just wanted you to not waste the same time 😀

**Comment by elhigu** [comment]
implemented in https://github.com/Vincit/objection.js/pull/270

**Comment by makeitrein** [comment]
You rock! 2017 is off to a good start for my codebase... I'll start playing
around with it, see if any issues or peculiarities crop up
