### ISSUE TITLE
HasMethod typing is not matching implementation

### ISSUE THREAD

**Issue by IlyaSemenov** [Vincit/objection.js#1955]
HasMethod is currently typed very restrictively:

https://github.com/Vincit/objection.js/blob/412bb77b9cf69496e477c38fc10bca679ceca461/typings/objection/index.d.ts#L602-L604

even though the actual implementation supports other types of filters:

https://github.com/Vincit/objection.js/blob/412bb77b9cf69496e477c38fc10bca679ceca461/lib/queryBuilder/QueryBuilderOperationSupport.js#L464-L478

In particular, the following is not valid Typescript even though it's actually valid working code:

```ts
query.has((op) => op.name === "select" && op.args[0] === "id")
```

**Comment by koskimas** [comment]
It matches the public API https://vincit.github.io/objection.js/api/query-builder/other-methods.html#has.

As you know, javascript doesn't have polymorphic methods. That's why objection sometimes has extended functionality for some methods for internal use and only documents a part of it in the public API. I don't want to expose the operation classes to the outside world. Doing that would lock their API and I wouldn't be able toi change it without major version bump.
