### ISSUE TITLE
[Question] withGraphFetched behaves differently to withGraphJoined

### ISSUE THREAD

**Issue by cheynewallace** [Vincit/objection.js#2038]
Im missing something here, and its driving me nuts, i'm sure this is my code, however I cannot see what the problem is.

This a very simple eager loaded query using `withGraphFetched`, I can see the related DB query being performed correctly in my console, even tested the query in my SQL editor and its returning correct data, however Objection is not actually assigning the results to the object and i have no idea why.

In the following example, the `media` key on the response object is always an empty array.  Even though the DB query actually returns records.

Strangely enough, if I change from using `withGraphFetched` to `withGraphJoined` it will return the right data although only a single record.

```
export default class Article extends Model {
	static tableName = TABLES.ARTICLES;

	static get relationMappings() {
		return {
			media: {
				relation: Model.HasManyRelation,
				modelClass: Media,
				join: {
					from: "articles.id",
					to: "media.article_id",
				},
			}
	}
}
```

```
export default class Media extends Model {
	static tableName = TABLES.MEDIA;

	static get relationMappings() {
		return {
			article: {
				relation: Model.BelongsToOneRelation,
				modelClass: Article,
				join: {
					from: "media.article_id",
					to: "articles.id",
				},
			},
		};
	}
}
```

and the query 
```
await Article.query().withGraphFetched("media");
```

returns (note the empty `media` key)
```
    {
      "id": 1,
      "slug": "nsw-flooding",
      "title": "NSW Flooding",
      "description": "Thousands evacuated from low lying areas across Sydney and NSW",
      "media": []
    },
```

I can clearly see in my console 
```
  knex:query select "media".* from "media" where "media"."article_id" in (?, ?, ?, ?, ?, ?, ?, ?, ?) 
```  
Which when run directly on the DB, it shows the correct records... 

Oddly, when changing to a `withGraphJoined`
```
await Article.query().withGraphJoined("media");
```

It works, although only shows one record
```
    {
      "id": 1,
      "slug": "nsw-flooding",
      "title": "NSW Flooding",
      "description": "Thousands evacuated from low lying areas across Sydney and NSW.",
      "media": [
        {
          "id": 18,
          "assetId": "xxxx"
        }
      ]
    },
```

So something is happening at the objection level where its not attaching the records and for some reason `withGraphFetched` behaves in a strange way that im not understanding.  It feels as though there's something wrong with my `HasManyRelation` however, it all looks fine to me.  I was under the understanding that these two eager load methods essentially are interchangable?

Can put together a reproduction template if need be, however I was hoping someone was just point out a glaring mistake iv made, or inform me that im using something incorrectly first

**Comment by koskimas** [comment]
You are using knexSnakeCaseMappers, but not declaring things in camel case as instructed by the docs.

**Comment by cheynewallace** [comment]
Thank you so much @koskimas .. You just saved me more hours of frustration, its working now.   
The whole code base had been working as normal with snake case keys (even other ManyToMany joins), except the OneToMany joins after I switched to withGraphFetched, so I never would of guessed that was it. Thanks again.

**Comment by yannickschuchmann** [comment]
Hey guys, 
I'm running into a partially similar situation. I also use knexSnakeCaseMappers but my relationMappings work as expected.
So `withGraphFetched` spits out many items for a has-many relation. On production `withGraphJoined` is much more efficient for us, that's why I want to switch to it. But my issue is that I get only a single item for relation.

```ts
// Keyword.ts
static relationMappings = () => {
  // ...
  searchranks: {
    relation: Model.HasManyRelation,
    modelClass: SearchrankModel,
    join: {
      from: "keywords.id",
      to: "searchranks.keywordId",
    },
  },


// Searchrank.ts
static relationMappings = () => {
  // ...
  keyword: {
    relation: Model.BelongsToOneRelation,
    modelClass: Keyword,
    join: {
      from: "searchranks.keywordId",
      to: "keywords.id",
    },
  },

// Cluster.ts (for completeness)
static relationMappings = () => {
  // ...
  keywords: {
    relation: Model.ManyToManyRelation,
    modelClass: KeywordModel,
    join: {
      from: "clusters.id",
      through: {
        from: "clusters_keywords.clusterId",
        to: "clusters_keywords.keywordId",
        extra: ["active"],
      },
      to: "keywords.id",
    },
  },


// My query
await Cluster.query()
          .withGraphJoined("keywords.searchranks")
          .where("clusters.id", id);
```

The query returns an instance of a cluster with multiple keywords but each one as only 1 single searchrank. With `withGraphFetched` it contains a lot more searchranks per keyword.. like it should be. :)

@koskimas, I guess the issue with the single row result is not related to snake->camelCase, or? I think about doing the query manually and use Objection to parse it into Model Instances, didn't find the helper functions in the docs/code yet. Also not sure if it's a good idea at all. Definitely would prefer to use objection's withGraphJoined. 

And offtopic @koskimas, while searching for some info on github I saw how active you are in helping/collaborating/supporting. Thank you for that <3 Cheers

**Comment by yannickschuchmann** [comment]
**Update:**
The issue was that my `Searchrank` model does not have an 'id' column since it's just timeseries data with a composite key. 
But because I didn't tell objection about the composite key it could not do it's magic. I didn't look into why the magic is different between withGraphFetched and withGraphJoined.

Anyway I defined the composite key in the model:
```typescript
static get idColumn() {
  return ["keyword_id", "department", "time"];
}
```

It may or may not help somebody, it's a rather special case. But I wanted to share this for the sake of completeness.

Cheers :)

**Comment by samuliasmala** [comment]
I had an opposite issue than the original issue poster, i.e. `withGraphFetched` everything worked nicely but when changed to `withGraphJoined` all the relations were empty objects. I finally found the explanation and I post it here in case someone else lands here with the same issue.

The issue I had was caused by the still-open Knex bug https://github.com/knex/knex/issues/3563 which makes columnInfo fail if you use connectionString/connectString and Postgres. Below is first my problematic configuration and then fixed configuration.

```js
// withGraphJoined doesn't work
const knex = Knex({
  client: "pg",
  connection: {
    connectionString: process.env.DATABASE_URL,
  },
});

// withGraphJoined works
const knex = Knex({
  client: "pg",
  connection: process.env.DATABASE_URL,
});
```

**Comment by SebGom-03** [comment]
Hi @samuliasmala I have exactly the same issue as you. To solve it I had to create a fu*** mapper and it's working now but I don't like that solution. 

I tried to parse the config but it didn't work. 

this is my config:

const { DB_HOST, DB_USER, DB_PASSWORD, DB_NAME, DB_PORT } = process.env;

const knexConfig = {
  client: 'postgresql',
  connection: {
    host: DB_HOST,
    port: DB_PORT,
    user: DB_USER,
    password: DB_PASSWORD,
    database: DB_NAME,
    timezone: 'UTC',
  },
  pool: {
    min: 0,
    max: 30,
    idleTimeoutMillis: 30000, // Increase idle timeout for better resource utilization
    reapIntervalMillis: 1000, // More frequent reaping to clean up idle connections
    createRetryIntervalMillis: 100,
    acquireTimeoutMillis: 30000, // Allow more time to acquire a connection
    createTimeoutMillis: 30000, // Allow more time to create a connection
  },
  asyncStackTraces: true,
};

do you know what should I do here please?

I really appreciate it
