### ISSUE TITLE
Missing id attribute after patch

### ISSUE THREAD

**Issue by kimmobrunfeldt** [Vincit/objection.js#21]
After patch operation, the full model is not returned. It's missing `id` attribute:

```js
Model.query()
.patch(newObj)
.where('id', modelId)
.then(function(newModel) {
    return newModel.toJSON();
})
.then(function(json) {
    // At this point json.id === undefined ?
});
```

**Comment by juanjoLenero** [comment]
I'm having a somewhat related issue, after an insert only the inserted keys are populated in the model:

```javascript
exports.createTopic = function *() {
    let topic = this.request.body;
    topic.authorId = this.req.user.id;

    topic = yield Topic.query().insert(topic);

    this.body = {topic: topic};
};

// Schema for topic.
Topic.jsonSchema = {
    type: 'object',
    required: ['title', 'authorId'],
    properties: {
        id: {type: 'integer'},
        title: {type: 'string', minLength: 1, maxLength: 255},
        description: {type: 'string', minLength: 1, maxLength: 255},
        parentTopicId: {type: ['string', 'null']},
        authorId: {type: 'string'},
        createdAt: {type: 'string', format: 'date-time'},
        updatedAt: {type: 'string', format: 'date-time'}
    }
};
```
So for example if the request body only contains the fields for title, and author. That's the only fields that the result will contain. I would expect to receive an instance with all the fields in the database row.

**Comment by koskimas** [comment]
@kimmobrunfeldt are you using `.patch()` to insert new models or does the `newObj` have an id?

@juanjoLenero when inserting a new model, there is no cross-db way to get all columns as a response (as far as I know). We could make another query to fetch all the columns, but that is just the kind of magic I'm trying to avoid. 

Postgres has the `RETURNING *`, but I didn't want the return value to be different on different databases. You can set the default values in the jsonSchema using the default attribute like so:

```js
properties: {
  ...
  authorId: {type: 'integer', default: null},
  ...
}
```

This isn't the same thing and doesn't work for example with the `createdAt` and `updatedAt` at the moment. 

I propably could make the `QueryBuilder` work with the `returning()` method so that you could get the whole object when using postgres:

```js
topic = yield Topic.query().insert(topic).returning('Topic.*');
```

I'll have to check if knex works with multiple `returning` columns.

**Comment by kimmobrunfeldt** [comment]
@koskimas no the newObj didn't have id but I was expecting to get the full model as a response. I'm appreciate the goal to minimize magic. This is a very common use case though. Do you recommend manually fetching the patched model after the patch?

**Comment by koskimas** [comment]
At the moment, you have to manually fetch the model. I could consider adding something like this though:

```js
Model.query()
.patch(newObj, {fetch: true})
.where('id', modelId)
.then(function(allModelsThatWereUpdated) {

})
```

any thoughts?

**Comment by elhigu** [comment]
Or maybe `.patchAndFetch()`? Could be easier to find and naming of method would justice that extra fetching. 

Or is there some other options available for `.patch`.

**Comment by koskimas** [comment]
Because of the current architecture we would have to add the patchAndFetch, insertAndFetch, updateAndFetch methods to all the Relation subclasses in addition to QueryBuilder. On the good side those would be found by autocomplete.

**Comment by juanjoLenero** [comment]
Perhaps a simple `reload()` function and disclaimers specifying that insert/patch methods don't return the complete model would be good enough

**Comment by kimmobrunfeldt** [comment]
I like the fetch parameter a bit more then reload. I was just thinking about the use cases for create and update - how many times do you not need the results back? In almost all of my cases I need the results right away and I would probably override the methods to always use fetch:true param if you decide to go that route.

**Comment by koskimas** [comment]
Yeah, if you think about REST API methods, you probably always want the whole object as a response from create and update methods. But I don't think it's something an ORM should do automatically. I constantly write code where I don't want the overhead of an extra fetch when I update rows.

There is a feature that helps you write own helper query methos (for example the patchAndFetch). You can add `then` callbacks to a `QueryBuilder` without executing it using the `runAfter` method. For example:

```js
Person.patchAndFetch = function (patch) {
  return this.query().patch(patch).runAfter(function (patch) {
    return Person.query().where('id', patch.id).first();
  });
};
```

**Comment by koskimas** [comment]
@juanjoLenero If you are using postgres, you can now get all columns as a response when inserting models by calling:

```js
topic = yield Topic.query().insert(topic).returning('*');
```

This works starting from 0.2.1 version.

**Comment by koskimas** [comment]
I've given the `patchAndFetch` -kind of method some thought lately, and I think implementing it so that it works in all situations is too much of a hack. Consider this query:

```js
Person
  .query()
  .patchAndFetch({firstName: 'Foo'})
  .where('firstName', 'Bar'); 
```

We would have to make three queries to make this work:

 1. Find all Person identifiers that will be affected by the query.
 2. Update the rows.
 3. Fetch the rows.

We cannot do it using two queries (Update & Find using the same where clause) because the update operation may change the outcome of the where clause (as it does in the example above).

At least a couple of problems arise from this:

 1. What if the query affects 1000000 rows. Fetching the identifiers and making the 'where in' query  in step 3 would fail.
 2. This would all have to be done in a transaction or rows can disappear between steps 2 and 3.

So doing a generic `patchAndFetch` or `patch(obj, {fetch: true})` is not really an option.

Maybe what you actually want is something like `patchAndFetchById(req.params.id, obj)`? The name here is not the best but you get the idea. This would be trivial to implement.
