### ISSUE TITLE
Update npm package?

### ISSUE THREAD

**Issue by strues** [Vincit/objection.js#212]
First off, thanks for writing this awesome tool. Would it be possible to update the npm package, perhaps with a minor version increment so that the Knex peer dependency of up to 0.12.3 is supported?

I see the change is in place here, but still getting:
`objection@0.6.0 requires a peer of knex@>= 0.8.0 <= 0.12.1 but none was installed.`

_edit: as I write this, we're up to 0.12.5 with Knex._

**Comment by fl0w** [comment]
0.12.3 is updated in master (but not yet published on npm). 0.12.4 had build issues and had to be patched 0.12.5 just a few hours post release.

Because knex still is on sub v1 versioning, this will be a pain for a while.

You can always just "monkey patch" objections package.json yourself if you need latest of the latest.

**Comment by koskimas** [comment]
The peerdep is a bit of a PITA, but necessary because knex breaks from time to time and I don't want objection to break with it. We have couple of fixes planned for 0.6.1 so this will have to wait for  a while. Sorry about this.

With npm3 peerdep mismatches show up only as warnings right? Are you using npm2?

**Comment by Biktop** [comment]
@koskimas is there any chance to see 0.6.1 in the nearest feature?

**Comment by koskimas** [comment]
I'll release it today GMT+3.

**Comment by koskimas** [comment]
Done
