### ISSUE TITLE
Alternative to .skipUndefined?

### ISSUE THREAD

**Issue by simon-lorenz** [Vincit/objection.js#2140]
I've just upgraded to Objection 3 and I noticed that `.skipUndefined` was deprecated yesterday in 9a66f2160820d6fe4c4121c13b65591b35f2a108. 

I'm sure there are good reasons for that and I've also read that `skipUndefined` is [considered a bad feature](https://github.com/Vincit/objection.js/issues/2104#issuecomment-916020049). However, I really liked it because it spared me from a lot of duplicate code like this:

```javascript
Model.query().modify(qb => {
  if (value !== undefined) {
    qb.where('column', value)
  }
}
```

Is there any other alternative to `.skipUndefined`?

**Comment by kibertoad** [comment]
You can use copyWithoutUndefined from knex-utils library.

**Comment by simon-lorenz** [comment]
Thanks, I'll look into it!

**Comment by koskimas** [comment]
There's no additional helper for this in objection, but you should be able to create your own helpers pretty easily.

**Comment by demisx** [comment]
Could you please tell us what was the reason for removing `.skipUndefined`? Just curious. We really liked it and used it quite frequently. Thank you.

**Comment by kenbellows** [comment]
> Could you please tell us what was the reason for removing `.skipUndefined`? Just curious. We really liked it and used it quite frequently. Thank you.

See this comment: https://github.com/Vincit/objection.js/issues/2104#issuecomment-916020049

Basically it's a dangerous method to use in many cases because skipping a condition in a where clause typically ends up including far more data, which can be catastrophic for mutating commands. To quote from the above comment:

> Consider this query
>
> ```
> Person.query().delete().where('id', someId).skipUndefined()
>```
> Now if you accidentally pass undefined in someId you end up deleting the whole table.

The same goes for something like `Person.query().update({name: 'John Smith}).where({id: johnsId}).skipUndefined()`. If `johnsId` is accidentally undefined, you'll end up overwriting the `name` column for the whole table.
