### ISSUE TITLE
$relatedQuery First Parameter Strange Behaviour

### ISSUE THREAD

**Issue by jaesam** [Vincit/objection.js#2144]
(I have updated all the packages to their latest releases)

Hi I have noticed a behaviour of $relatedQuery which seems a bit off to me. 
Let's say someModel and anotherModel is in M2M relation with some extras.

`
someModel.$relatedQuery('someRelationName').relate({id: anotherModel.id, ...extras})
`

The above line of code works perfectly but,

`
const someRelationNameInString: string = 'someRelationName';
someModel.$relatedQuery(someRelationNameInString).relate({id: anotherModel.id, ...extras})
`

this now gives me error saying that the object I am passing to relate() is not assignable and id does not exist.
I couldn't find any helpful info from the doc so I am leaving this here.
Is this intended behaviour? If so, what is the reason behind this design choice?

**Comment by koskimas** [comment]
That's because the type of the `someRelationNameInString` is `string` and the type of the `'someRelationName'` literal is actually `'someRelationName'`. That's how objection is able to infer the correct relation column. It can't do that with a `string`. You can fix that particular example like this, but this probably isn't possible in your actual use case.

```ts
const someRelationNameInString = 'someRelationName' as const; 
someModel.$relatedQuery(someRelationNameInString).relate({id: anotherModel.id, ...extras})
```

You can always pass the relation type as the generic argument for `relatedQuery`.

**Comment by koskimas** [comment]
And it's not a design choice. It's just how typescript works. You need to know the types compile-time.
