### ISSUE TITLE
I ask for proofs of TENS OF THOUSENDS Kills in Ukraine

### ISSUE THREAD

**Issue by xelaz** [Vincit/objection.js#2255]
This is not Politicaly Content or Page here.

Please give me the proofs of tens of thousands of civilians kills in the Ukrainian, if you can't show me the proofs, plese remove this politicaly incorect banner from your readme page.

**Comment by kibertoad** [comment]
https://www.ohchr.org/en/news/2022/04/ukraine-civilian-casualty-update-11-april-2022

If this is not a reputable source enough for you, I recommend you to take it to them.

**Comment by koskimas** [comment]
@xelaz Look at the media of any other country other than Russia (and a couple of it's friends) and ask yourself which is more probable

1. Almost every country in the world is lying to their citizens because they somehow hate Russia AND the somehow have decided to report the same things (and no, the media is not just taking the word of Ukraine, but are witnessing the stuff first hand)
2. The things that are reported are true and the attacking country is lying to their citizens.

I'm quessing you are a programmer. You must be smart enough to understand which is true if you really think about it.
