### ISSUE TITLE
circular dependency, using string filePath for modelClass, code breaks when relying on relationMappings to provide object info in code

### ISSUE THREAD

**Issue by skn3** [Vincit/objection.js#242]
So I have a circular dependency in my object structure. A page has revisions, and each revision references the page it belongs to.

I tried swapping out the modelClass object in the relationMappings to a string instead of object. This fails in some cases where I am inspecting the relationMappings details to get the modelClass. For example I scan over the relationMAppings, figure out which relations there are then run some custom code for each one.

So as a stop gap I have created the following function:
```
function getModelClass(modelClass) {
    if (modelClass instanceof Object) {
        return modelClass;
    } else {
        return require(modelClass);
    }
}
```

This works for my purposes, but it be possible to expose Objections inbuilt model resolve routine so that we can use it as well?

**Comment by koskimas** [comment]
There is a private `getRelations()` method that returns `Relation` instances that always have the model classes and bunch of other stuff resolved. I'm thinking about making it a part of the public interface, since it would make this kind of "reflection magic" possible. My only concern is that making it all public prevents me from making changes to it in the future. On the other hand the method and the `Relation` interface has been pretty stable. And actually couple of my libraries use it anyways, so I might just as well make it public.

**Comment by skn3** [comment]
That sounds ideal :D
