### ISSUE TITLE
jsonSchema.oneOf is not supported in ModelBase mergeWithDefaults

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#243]
https://github.com/Vincit/objection.js/blob/master/src/model/ModelBase.js#L503
fails with a schema like
```
{
  type: "object",
  oneOf: [
    {properties: { what: { "enum": ["thatclass"] }, title: { type: "string"} }},
    {properties: { what: { "enum": ["thisclass"] }, body: { type: "string"} }}
  ]
}
```
because default values won't be found, while there are some.
Related a little to https://github.com/Vincit/objection.js/issues/205.

**Comment by kapouer** [comment]
It seems to me that https://github.com/epoberezkin/ajv#assigning-defaults is precisely doing what mergeWithDefaults does ?

**Comment by kapouer** [comment]
It's interesting to see it working, yet ajv has some limits too regarding defaults inside oneOf/anyOf/allOf, as explained at the bottom of the documention given above.
A workaround is to use json schema v5 switch mecanism.

**Comment by koskimas** [comment]
We should probably remove `mergeWithDefaults` and just use ajv default system. There is only one thing that needs to be solved: ajv assings the default values to the input object where as `mergeWithDefaults` creates a clone making sure the input object is never modified. With ajv we would need to take the clone each time since we don't know if some default values will be set. That probably won't matter much, since inserts are usually far less common than reads, and they take most of their time in the database anyway.

**Comment by kapouer** [comment]
Closing in favor of #244.
