### ISSUE TITLE
Limiting $loadRelated queries

### ISSUE THREAD

**Issue by lauritzsh** [Vincit/objection.js#252]
Hi, great work on this library. It has definitely simplified some of my queries.

To explain the query: I have a user that has relations with actors. These actors have starred in movies. I want to fetch the user's actors' movies but limit that to ten movies per actor. I can only manage to limit the total amount of movies, not per actor.

This is what I have tried and what seems logical for me:

```javascript
const userRelations = await user
  .$loadRelated('actors.movies(onlyTen)', {
    onlyTen(builder) {
      builder.limit(10);
    },
  })
```

So how would I get 3 actors and 30 movies instead of the 3 actors and 10 movies I am currently getting? Thanks!

**Comment by elhigu** [comment]
I'm trying to think what kind of SQL query could do that... load related indeed does apply the limit by level of nested relation, because it doesn't do separate query for every actor to get their movies with some limit per actor... 

I'm pretty sure you need to first load related actors and then separately for each actor do another query to load related movies. Something like:

```js
const userRelations = await user.$loadRelated('actors');
await Promise.all(userRelations.actors.map(actor => {
    return actor.$loadRelated('movies(onlyTen)', {
        onlyTen(builder) { builder.limit(10); }
    });
});
```

I haven't been using `$loadRelated` myself, does it patch relations to original instance, which calls it? If it doesn't patch some assigning might be needed too. 

Anyways baseline here is that I think you have to do separate query for each actor to get their 10 movies (I can't think any other simple way to do from top of my head. Many times it is easier to first think which kind of SQL you need and then think how to make objection to do that.

**Comment by lauritzsh** [comment]
Thanks for the help, I ended up using your code snippet pretty much. Why are you not using `$loadRelated` (I think it patches btw)? Can `eager` do everything that `$loadRelated` can do? I'm closing the issue as it answered my initial question but I would still like to hear the reason for not using `$loadRelated` if `eager` can always be used instead. :-)
