### ISSUE TITLE
Support for optimistic concurrency control

### ISSUE THREAD

**Issue by crisu83** [Vincit/objection.js#268]
Are there any plans for adding support for optimistic locks? We ran into a situation in one of our projects where we had to implement optimistic locks in our application, even though this is something that the ORM could handle. As an example Hibernate does support this.

**Comment by elhigu** [comment]
I suppose that keeping up consistency_version won't be too hard to implement at least for single updates... when multiple rows are updated at once I have no idea how it could be implemented.

Could this kind of feature be implemented with database triggers automatically (depends on database one is using I suppose)?

**Comment by crisu83** [comment]
@elhigu I wouldn't implement this on the database level, because I don't like magic that is easy to miss. If the support is added in the code it would be much easier to understand and use.

**Comment by elhigu** [comment]
@crisu83 I still don't think that it can be done in a performant way outside of DB server and if done in model library level, it will also break on queries which bypasses the model hooks (which fine for me, maybe that locking shouldn't work in that case).

If you are fine with locking just single updates optimistically, you might be able to do it by extending base model and check revision in model hooks before writing updated values (for example by adding `.where('rev', expectedRev)` and throwing exception if update count was 0).

However overall doing it on ORM level without triggers sounds hacky. ORM could just declare correct triggers which makes sure that `rev` is updated and respected, but it would indeed look more magical solution than complete app level solution. I would be happy to hear if someone has good idea how to implement it well without triggers.

**Comment by koskimas** [comment]
Optimistic locking is something an ORM could handle, but not objection. Traditional ORMs have an abstraction for every single thing that can be done with them and therefore can effectively implement this kind of things. 

Objection gives the user a lot of freedom to mix raw sql or even to skip the whole query builder. If we were to implement optimistic locking in objection, it would only work when the user uses objection in a certain ORMish way, and would not work in most special cases where the user bypasses the objection's abstractions. 

We can see this with the query lifecycle hooks in objection: they are a bit of a mess because they are not always called and sometimes called with unexpected places with unexpected data.

I don't think this is something we'll be adding to objection.

**Comment by crisu83** [comment]
@koskimas fair enough. 🙂
