### ISSUE TITLE
Use ES2016 instead of ES7

### ISSUE THREAD

**Issue by oliviertassinari** [Vincit/objection.js#278]
With the new process used by the [tc39](https://github.com/tc39/ecma262#ecmascript) committee, evolution to the language will be released every year.
I think that it would be better to stick to the *ES20xx* convention.

**Comment by koskimas** [comment]
Maybe we would be better off using ES5 / ES next or something since ES2016 ended up having 2 new features in comparison to ES2015:

 * Array.prototype.includes
 * Exponentiation operator

And ES2017 will probably have just as little new stuff.

ES5/ES6/ES7 version names are used mainly in the code examples and example projects. Maybe we should only divide these into ES5/ES next or even lose the ES5 alltogether and just write everything using newest shiniest node features. What do you think?

**Comment by oliviertassinari** [comment]
> Maybe we should only divide these into ES5/ES next

I like that idea.

> just write everything using newest shiniest node features

That's gonna make the examples simpler. I mean assuming that everybody is using the latest released version of node. But that's more debatable.

**Comment by devinivy** [comment]
You could write in the style of the latest node LTS version– that gives a natural progression people are already familiar with.

**Comment by fl0w** [comment]
Personally I wouldn't mind had objection.js docs only included ES next examples. But a small description of how to downgrade some ES next sugar could be useful as a minor separate segment perhaps.

**Comment by koskimas** [comment]
@devinivy That would mean constant updating and everyone hates writing docs :trollface: 
@fl0w I like that idea!

**Comment by denizdogan** [comment]
http://knexjs.org/ has a cool feature at the top right hand side where you can pick an SQL dialect. The Objection.js documentation would be much easier to navigate if visitors could switch between different ES versions for the examples!

**Comment by koskimas** [comment]
ES5 support is now removed in the master branch and will be released with 0.8.0. ES5 examples have been removed, node 4.0.0 examples are the default (the lowest supported node version) and then there are ESNext examples.
