### ISSUE TITLE
Enrich ValidationError payload with error params

### ISSUE THREAD

**Issue by zuck** [Vincit/objection.js#283]
At the moment a `ValidationError` only returns the name of the field which doesn't validate and a "default" message not very suitable for front-end. No other info about the validation context are exposed by the error class.

My proposal is to extend `ValidationError` changing the behavior and content of the `data` attribute with a more useful payload. This payload should include the validation `keyword` and `params` (returned by **Ajv** validation error in default implementation).

Something like:

**model/AjvValidatior.js**
```
function parseValidationError(errors) {
  const errorHash = {};
  let index = 0;

  for (let i = 0; i < errors.length; ++i) {
    // ...
    // Here we pass a more useful payload for each key.
    // Before was: errorHash[key] = error.message;
    errorHash[key] = {
      message: error.message,
      keyword: error.keyword,
      params: error.params
    }
  }

  return new ValidationError(errorHash);
}
```

This is necessary to avoid nasty regex matches on front-end in order to individuate the scope of the validation error and to provide custom error messages without pains, e.g.:

```
MyModel
  .query()
  .patchAndFetchById(id, values)
  .catch(function(err) {
    if (err instanceof objection.ValidationError) {
     Object.keys(err.data).forEach(function(key) {
       let keyErr = err.data[key];
       if (keyErr.keyword === 'minLength')
         console.error("The field " + key + " is too short: must be at least " + keyErr.params.limit + " chars long!");
       }
     });
    }
  });
```

I could work on a **PR** for this.

For sure, it could break something so maybe a major release is required in order to include it mainstream.

**Comment by koskimas** [comment]
Sounds good and I would love a PR for this!

This will probably break stuff, but the content of `ValidationError` isn't public API (expect for the opaque `data` field), so people should realise it's subject to change. But let's play it safe and publish this with 0.7 or 0.8 as a breaking change.

Maybe we should document and test this and make it public so that the content can be trusted and safely used in the future?

**Comment by zuck** [comment]
Yeah, I think so: with the proposed payload I think all the necessary info will be available, so I would consider it quite "future-proof"...

**Comment by devinivy** [comment]
The only thing I would add, is that sometimes there are multiple validation issues with a single field.  This could happen with joi, which we use with objection.  It would be nice if the public API could handle that!

**Comment by zuck** [comment]
It should be quite easy: we could simply transform values of error hash table returned by a validator to a list of error payloads, e.g.:

```
errorHash[key] = [{
      message: error.message,
      keyword: error.keyword,
      params: error.params
}];
```

While default **AjvValidator** will return just one error for each key at time, other validators could return more than one error...

**Comment by koskimas** [comment]
Thank you @zuck!

**Comment by jeff-kilbride** [comment]
This looks great! Would it be possible to add a `name` property to the ValidationError object? I have centralized error handling and currently, to detect a ValidationError, I have to require `objection` into my error handling script. (e.g.  `if (err instanceof objection.ValidationError)` ) 

It would be nice to be able to detect a ValidationError without having to require objection, like:
```
if (err.name === 'ValidationError')
```
or
```
if (err.name === 'ObjectionValidationError')
```
Just a thought...  I realize this issue is closed. If you're open to this, I can create a new issue.

Thanks!
