### ISSUE TITLE
modifyEager sometimes causes eager results not to be returned

### ISSUE THREAD

**Issue by lucascolvin** [Vincit/objection.js#309]
The simple eager query works well and includes all of the results. But when sometimes modifyEager causes an empty eager array to be returned;

Simple Example works well:
```javascript
const users = await User.query()
    .eager('[roles, log_auth]')
```
```json
[
    {
      "id": 1,
      "email": "test@test.com",
      "roles": [
        {
          "id": 2,
          "slug": "member-subscripted",
          "name": "Member with a paid subscription",
          "group": "MEMBER",
        }...
      ],
      "log_auth": [
        {
          "id": 1,
          "created_at": "2017-02-23T23:54:35.000Z",
          "user_id": 1
        }...
      ]
    }
  ]
```
Sometimes modifyEager works:
```javascript
const users = await User.query()
    .eager('[roles, log_auth]')
    .modifyEager('roles', builder => {
      builder.select('roles.slug');
    })
```
```json
[
    {
      "id": 1,
      "email": "test@test.com",
      "roles": [
        {
          "slug": "member-subscripted"
        }...
      ],
      "log_auth": [
        {
          "id": 1,
          "created_at": "2017-02-23T23:54:35.000Z",
          "user_id": 1
        }...
      ]
    }
  ]
```

But other times it doesn't:
```javascript
const users = await User.query()
    .eager('[roles, log_auth]')
    .modifyEager('log_auth', builder => {
      builder.select('log_auth.created_at');
    })
```
```json
[
    {
      "id": 1,
      "email": "test@test.com",
      "roles": [
        {
          "id": 2,
          "slug": "member-subscripted",
          "name": "Member with a paid subscription",
          "group": "MEMBER",
        }...
      ],
      "log_auth": []
    }
  ]
```

**Comment by lucascolvin** [comment]
environment info:
objection@0.6.2
node@6.9.4
mysql server version 5.7

**Comment by newhouse** [comment]
Can you include the relation defintion from the User to the roles and log_auth?

I've experienced issues like this when I don't select columns necessary to make the relation connection...Usually this involves omitting the id or foreign key from the select. 

Maybe this is your issue?

**Comment by lucascolvin** [comment]
That was definitely the issue. Roles is a ManyToManyRelation while log_auth is a HasManyRelation and I had been excluding the foreign key column.

Thanks for looking at this and pointing me in the right direction. The only other JS ORM I'd used was such a bad experience that I've been building JS apps with raw sql queries for years now. I'm still just starting with it but Objection has been a breath of fresh air so far.  Out of curiosity though, is there a reason the necessary join columns are not forced under the hood?

**Comment by newhouse** [comment]
@lucascolvin glad that was it and I could help...and yes, I'm really liking Objection a lot as well!

I think there are a few things at play here. As [specified in the docs](http://vincit.github.io/objection.js/#eager), the default `eagerAlgorithm` used in a an `eager` is not a `JOIN`, but actually `n` number of additional SQL calls made using `where x in (...)` to get the related records of those found during the `SELECT` on the Parent object/table. Typically the results from these queries are parsed, converted into instances and added onto the Parent record appropriately. But, as we've experienced, not selecting the required column(s) (usually `id`) from the Parent will leave Objection unable to create an appropriate `WHERE x IN (...)` for the related queries.  But that doesn't mean it won't still try 😄 Look at this info I found after setting Knex `debug` to `true` and trying to eager load a relation called `broadcasts` off of the parent `Campaign` after explicitly not selecting the `id` column from the `campaigns` table:
```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'CAMXXXXXXXXXXXXXX ],
  __knexQueryUid: 'be49bb67-8298-4d52-b7ab-e872b5fcadd4',
  sql: 'select "type" from "campaigns" where "id" = ?' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 0 ],
  __knexQueryUid: 'd52f54d4-29ec-4b64-914c-10bf9d7cffc7',
  sql: 'select * from "broadcasts" where 1 = ?' }
```
(Side note - This is an unusual 2nd query as I believe it ends up as: `select * from "broadcasts" where 1 = 0`? Why even bother to run that query? Any clue what's going on with this one, @koskimas ?)

My first thought on why Objection was not ensuring the necessary fields that define a relation between two Models were part of the `SELECT` on the Parent Model was that Objection didn't like the idea of going against the developer's _explicit_ wishes: i.e. "select this/these and only this/these, even if I'm (unintentionally) making it impossible to join relations because of it". However, when I modified the code to use the `JoinEagerAlgorithm`, things worked just fine (though I had some "ambiguity" errors I needed to address that were unexpected). Here's the knex debug:
```
{ method: 'select',
options: {},
timeout: false,
cancelOnTimeout: false,
bindings: [ 'CAMXXXXXXXXXXXXXX' ],
__knexQueryUid: 'c8dc9486-6dd9-479c-81ae-afd5668e92d1',
sql: 'select "campaigns"."type", "campaigns"."id" as "id", "campaigns"."type" as "type", "broadcasts"."id" as "broadcasts:id", "broadcasts"."type" as "broadcasts:type", "broadcasts"."content" as "broadcasts:content" from "campaigns" as "campaigns" left join (select "id", "type", "content", "campaign_id" from "broadcasts") as "broadcasts" on "broadcasts"."campaign_id" = "campaigns"."id" where "campaigns"."id" = ?' }
```
As you can see there, Objection is not shy about adding the necessary `"campaigns"."id"` to the `SELECT`. So I'm left thinking it's a bug and hoping that @koskimas can shed some light?

**Comment by lucascolvin** [comment]
@newhouse I can definitely respect the reasoning that Objection shouldn't be adding too much unneeded "helpfulness". As you say though, it does seem odd that some kinds of relations prioritize the relation and others prioritize the column filter.

Thanks for digging into it though. At very lease, knowing about it I can work around with some array.map filters after the query. Not as beautiful as having it baked in but its workable.

**Comment by fl0w** [comment]
I'm not sure overloading toJSON is a good thing, it's not public API AFAIK. I personally overload $formatJson in my base model:

```js
const { omit } = require('lodash')
class BaseModel extends objection.Model {
  $formatJson (json, options) {
    json = super.$formatJson(json, options)
    if (this.constructor.hiddenColumns)
      json = omit(json, this.constructor.hiddenColumns)
    return json
  }
}
```

And if I want to hide something, I define a static array onto said model:

```js
class User extends BaseModel {
  static get hiddenColumns () {
    return ['password']
  }
}
```

**Comment by koskimas** [comment]
This is a really common issue. I'll take a look if we could automatically select and then strip the join columns just like @lucascolvin suggested. 

The JoinEagerAlgorithm already does this because I was aware of this issue when I wrote it. It was designed to easily work like this. That's the only reason why they work differently.

@newhouse `where 1 = 0` happens when you call `.whereIn('blaa', [])` on knex.
