### ISSUE TITLE
missing asCallback

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#31]
Hi,

As documented on knexjs.org, there is an alias of `nodeify` as `asCallback`.
Is it possible to restore that alias in the promises returned by Objection ?

**Comment by koskimas** [comment]
Hi,

objection uses [bluebird promises](https://github.com/petkaantonov/bluebird/blob/master/API.md#ascallbackfunction-callback--object-options---promise) so the `asCallback` method is there. The confusion may come from the fact that the query is turned into a promise only after a call to `then()` method. You should be able to use the `asCallback` method like this:

```js
Person.query().where('x', '>', 42).then().asCalback(function (err, persons) { ... });
```

I will add `asCallback` to the `QueryBuilder` in the next version so that you can do this instead:

```js
Person.query().where('x', '>', 42).asCalback(function (err, persons) { ... });
```

**Comment by kapouer** [comment]
Right, thank you for the explanation.

**Comment by koskimas** [comment]
`asCallback` method added to `QueryBuilder` in version 0.2.3.
