### ISSUE TITLE
skipUndefined() and whereRaw()

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#318]
Hi,

Since I didn't see `skipUndefined()` in `knex` doc, I assume it is part of `Objection.js`. So I post here.

The query below throws exception:

```js
.select('*')
.skipUndefined()
.whereRaw('?? = ?', ['contact.id', undefined])
.toString()
```

`Error: Expected 1 bindings, saw 2`

Regards,

**Comment by ozum** [comment]
By the way, I realized that it may be hard to apply `.skipUndefined()` to `whereRaw()`, because there may multiple possible replacements in a complex `whereRaw()` query such as:

```js
.select(*)
.skipUndefined()
.whereRaw('EXTRACT(YEAR FROM ??) + ?? + ? > ?', ['birthdate', 'age', undefined, 25]) 
```

Should it skip entire condition or should it throw exception as it currently does?

**Comment by koskimas** [comment]
> By the way, I realized that it may be hard to apply .skipUndefined() to whereRaw(), because there may be multiple possible replacements in a complex whereRaw()

Yes exactly. The problem is that in order to make `skipUndefined` work with all methods I would have to replicate the knex API. Currently what most of the methods do is this:

```js
whereRaw() {
  return this.knex.whereRaw.apply(this, arguments);
}
```

so objection has no idea what's inside `arguments`. This is not strictly true, I already do some mapping for the arguments, but pretty basic stuff.

**Comment by fl0w** [comment]
This is highly subjective, but I think this is a slippery slope. Personally, if I work with `knex.raw` expect it to work as knex. The terminology used in `whereRaw` indicates *(to me)* that this does nothing magical and I expect it to not have side effects (i.e. it's just a shortcut to `knex.raw`).

`0.7` added ref, and reserved `objection.raw` and `objection.lit`. All are sort of magical by intentional definition.

Just adding my two cents to this discussion.

**Comment by koskimas** [comment]
Yeah, I don't think we should do this.
