### ISSUE TITLE
patch/update/del would better return the number of affected rows

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#34]
Since OINAORM (Objection is not an ORM) it would be cleaner to just not
try to return an instance after a patch ~~or update~~ call - it doesn't really make sense
as soon as we're updating multiple records.
This is related to https://github.com/Vincit/objection.js/issues/21

**Comment by koskimas** [comment]
You may be right. Returning a partial object is confusing even when patching single rows, since the whole instance is not returned as pointed out in #21. Maybe we should do this also for the `update` method since its return value doesn't contain the updates calculated in the DB?

So maybe `patch`, `update` and `delete` should all just return the count of affected rows and then we could add convenience methods like `patchAndFetchById` since that is the usual usage. `patchAndFetchById` would do a patch and also make an addition read query to fetch the fresh instance as discussed in #21.

**Comment by kapouer** [comment]
I'm reading https://github.com/Vincit/objection.js/issues/21#issuecomment-127559495 as "returning fetched/updated/deleted instance should be implemented in objection-rest, not in objection itself".
Because in the REST interface, update/patch/delete are only possible by id. A convenient method seems to be doomed by corner cases.

**Comment by koskimas** [comment]
Yes, I don't know if you misunderstood my previous post, but that is what I meant. If we add some sort of convenience methods that return the _actual_ database rows, they should be for a single id like `patchAndFetchById` as I mentioned before.

**Comment by kapouer** [comment]
Adding to the obvious, but nonetheless painful, missing number of affected rows issue: there is no simple way of knowing if a .del() was successful - besides doing a second query.

**Comment by koskimas** [comment]
As a temporary workaround you can use the `knexQuery()` method of the model:

```js
Person.knexQuery().del().where('foo', 'bar').then(function (delCount) {
  console.log(delCount, 'rows were deleted');
});
```

Same goes for `update`/`patch`.

**Comment by koskimas** [comment]
What do you think about this?

```js
Person.query().patch({a: 'b'}).where('foo', '=', 'bar').then(function (patch) {
  console.log('we just deleted, patch.$numModified, 'rows');
});

Person.query().delete().where('foo', '=', 'bar').then(function (ret) {
  console.log('we just deleted, ret.$numModified, 'rows');
});
```

The `$numModified` special property is prefixed with $ and will not appear in the object returned by `toJSON` method. We could also make the `$numModified` non-enumerable using `Object.defineProperty`.

I'd like to still return the input object as so that you can do stuff like this easily:

```js
expressApp.get('/some/path/:id, function (req, res, next) {
  Person.query().patch(req.body).where('id', req.params.id).then(function (patch) {
    res.send(patch);
  }).catch(next);
});
```

**Comment by elhigu** [comment]
IMO it would be misleading to return something that is not truth from database as a result for query. +1 to just return modified count and let user decide what to return in that case (e.g. if other query is needed)

**Comment by kapouer** [comment]
Ideas for alternatives:
* add a `function(patch, affectedCount)` parameter
* add a property (or even a method) to the current query (the one returned from `Person.query()`)

**Comment by koskimas** [comment]
Ok, everyone else but me seem to be against the "fake objects" as a result. Let's return only the affected count from the `update`, `patch` and `delete` methods as originally suggested by @kapouer. I think we should still return a fake object from `insert` though. Or do you think we should only return the identifier from that as well since the object is not a "truth from database"?

**Comment by kapouer** [comment]
Variations:
* Person.query().patch().where().fetch().then()
* Person.query().patch().where().affected().then()

**Comment by kapouer** [comment]
Youhou !
