### ISSUE TITLE
Error with transaction and promises

### ISSUE THREAD

**Issue by gustavobilert** [Vincit/objection.js#349]
We are trying to use transaction following the documentation and this question: #140 
But we always get this error:

> "insert into "tableName" (...) values (...) - InvalidStateError: DOM Exception 11: This transaction is already finalized. Transactions are committed after its success or failure handlers are called. If you are using a Promise to handle callbacks, be aware that implementations following the A+ standard adhere to run-to-completion semantics and so Promise resolution occurs on a subsequent tick and therefore after the transaction commits."

I don't quite understand this error, to me it seems like the transaction auto commits when we call .then(), but that would not make much sense.

What can we do to prevent this error?

We are using Bluebird promises.

**Comment by koskimas** [comment]
Please read and follow [these instructions](http://vincit.github.io/objection.js/#issues) about posting issues so that we are able to help you better. Only thing I can tell you based on this information is that your error doesn't come from objection but from knex or even the underlying database engine. Are you trying to use objection a browser? If so, that is completely untested and unsupported.

**Comment by gustavobilert** [comment]
Ok, we are using it on Mobile Cordova, with a home made driver for SQLite (https://github.com/tgriesser/knex/pull/1676).
So the problem is probably there.
I had tought we were using the transctions and promises in the wrong way.
Thank you for your advice.

**Comment by ChitThuShine** [comment]
we are facing the same problem like you .. can you explain detail how can we solve ?? Thank you!
