### ISSUE TITLE
modifyEager with sum?

### ISSUE THREAD

**Issue by mjyoung** [Vincit/objection.js#357]
Imagine I have a comment system with upvotes.

In my Comment model I've defined the relationship as such:
```
      votes: {
        relation: BaseModel.HasManyRelation,
        modelClass: CommentVote,
        join: {
          from: 'comments.id',
          to: 'comment_votes.comment_id'
        }
      }
```

```
  return Comment
    .query()
    .where({ id: commentId })
    .eager('votes')
    .modifyEager('votes', builder => {
      builder.sum('vote as vote_count');
    })
```

Doing this, votes always returns an empty array `[]`.  

I'm able to get the votes separately without eager loading through comments:
```
  return CommentVote
    .query()
    .where({ comment_id: commentId })
    .sum('vote as vote_count')
```

The above returns:
```
{ "vote_count": 2 }
```

I'm sure this is just user error on my part. Any idea how I can get this to work with `.modifyEager` so that I don't need to make two separate requests?

**Comment by koskimas** [comment]
Unfortunately you cannot do things like that in `modifyEager`. Objection expects the result of votes query to be an array of `CommentVote` objects that have `comment_id` property so that it can determine to which `Comment` they belong to. You seem to select only one `Comment` by id here, but there is no special treatment for such cases.

Since you are only fetching a single relation, you can do this:

```js
Comment
  .query()
  .findById(commentId)
  .then(comment => [
    comment, 
    comment.$relatedQuery('votes').sum('vote as vote_count')
  ])
  spread((comment, voteCount) => {
    comment.vote_count = voteCount.vote_count;
    return comment;
  });
```

**Comment by mjyoung** [comment]
Interesting! Thank you!
