### ISSUE TITLE
BUG Updating invalid column along with valid column does not error out in patchAndFetchByid

### ISSUE THREAD

**Issue by pavannaga** [Vincit/objection.js#379]
Updating invalid column along with valid column does not error out in patchAndFetchByid
Let say we have a table called `Users` in `db1`. 
Users schema looks like this 
```
Model.knex(knex);

class Users extends Model {
  static get tableName() {
    return 'Users';
  }
  
  static get relationMappings() {
    return {
      namespace: {
        relation: Model.HasManyRelation,
        // We use the file path version
        // here to prevent require loops.
        modelClass: __dirname + '/Employer',
        join: {
          from: 'Users.employerId',
          to: 'Employer.id'
        }
      }
    };
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['user_id', 'employerId'],

      properties: {
        user_id: {
          type: 'string'
        },
        employerId: {
          type: 'integer'
        }

      }
    };
  }
}
```

Now we try to patchAndFetchById for userid 1 whose employerId column should be updated to 3 from 2
I use this 

```
let userPatchData =  {
   non_existing_field: 'this should fail',
   employerId: 2
}
Users
  .query()
  .patchAndFetchById(1, userPatchData)
  .then((updatedUser) => {
    console.log("Updated User");
    console.log(updatedUser);
  }).catch((error) => {
    console.log(error);
  });
```
After running that program with sqlite3 or mysql2 client, I see the promise is resolved with this result

```
Updated User
Users {
non_existing_field: 'this should fail',
user_id: 1
   employerId: 2}

```
Even though the result says it has non_existing_field but the DB update did not fail. I tried using the same with knex API and knex call actually fails.

**Comment by newhouse** [comment]
My guess is that this is a "feature" and not a "bug". Because your Model has a `jsonSchema`, I think the patch data is _filtered then validated_ using that, and an error is only thrown if/when you try to pass a invalid value to a property defined in the `jsonSchema`. I'm guessing it works like that by default so as to allow for the accumulation of arbitrary data to the patch/update/insert object. Some of that data may not be relevant to the Model, but could be significant for some other part of the flow.

You might be able to get the behavior you want by adding a [$beforeValidate](http://vincit.github.io/objection.js/#_s_beforevalidate) hook to your Model(s). There you could check that there are no properties in the supplied `json` argument that are not in the supplied `jsonSchema` argument. There may be a better way, but that's my best guess.

**Comment by koskimas** [comment]
@newhouse is right. [`pickJsonSchemaProperties`](http://vincit.github.io/objection.js/#pickjsonschemaproperties) property can be used to control this behaviour. Starting from version 0.8.0 the default will be changed from true to false.
