### ISSUE TITLE
TypeError in 0.2.7 (not in 0.2.6)

### ISSUE THREAD

**Issue by fiddur** [Vincit/objection.js#38]
E.g. https://travis-ci.org/fiddur/some-comments/jobs/82571193

When downgrading to 0.2.6 it works as it should.  I haven't debugged more than that yet, coming up later…

**Comment by fiddur** [comment]
Here's the working build (0.2.6) https://travis-ci.org/fiddur/some-comments/jobs/82573166

**Comment by fiddur** [comment]
And the diff: https://github.com/Vincit/objection.js/compare/0.2.6...0.2.7#diff-6e4cbf91ee92d743b8b6cdbd265c532cR366

Key is sometimes a number… 

Ok, found the error.  The insert-statement I had for a row with url and siteId also contained a `site` (defined in relationMapping), but instead of containing the actual site object that also contained the id, so the iterator tried to iterate over the number 2.  I should clean away the bad data, but it was a quite confusing error-message.

**Comment by koskimas** [comment]
You seem to pass and array or string to the `ModelBase.prototype.$set` method. The method is called from the `fromJson` method. 

My wild quess is that you call `fromJson` for an actual model, but the model has and an array of strings (or something non-objecy) in a property that is also a the name of one of the relations. If an object given to `fromJson` method has relations, they are parsed into `Model` instances. In this case `fromJson` attempts to parse an array of strings (or something) into an array of `Model` instances, failing miserably. In 0.2.6 this just produced (weird) valid models. Now it fails since I changed the `$set` method's implementation.

**Comment by koskimas** [comment]
I will add a check that anything passed to `fromJson` is an object and throw a descriptive error.

**Comment by fiddur** [comment]
Great, thanks!  I fixed my bad data now; great with a better error message :+1:
