### ISSUE TITLE
Join table with extra columns - Patching

### ISSUE THREAD

**Issue by kdmcclel** [Vincit/objection.js#384]
#97 

Any chance we could make similar changes for patching?  This would simplify some code.  If I add a .where() it checks the related table and not the through table.  Or is there already a way to specify where() on the through table?

Example based on other post:
```
person
  .$relatedQuery('movies')
  .patch({
      name: 'The room',
      order: 1
  })
```
Result:
```
update `Movies` set `Name` = 'The room' where `Movies`.`id` in (select `Person_Movie`.`movieId` from `Person_Movie` where `Person_Movie`.`personId` = ? and `Person_Movie`.`order` = 1)
```

**Comment by kdmcclel** [comment]
Hmm I guess the workaround isn't too complex.

```
let movies = person.movies.filter(m => m.order == 1)
Movie
  .query()
  .whereIn('movieId', _.pluck('movieId')(movies))
  .patch({name: 'The room'})
```

**Comment by koskimas** [comment]
What version are you using? Patching with extra columns doesn't currently work, but the query I'm getting is

```
update `Movies` set `name` = 'The room', `order` = 1 where `Movies`.`id` in (select `Person_Movie`.`movieId` from `Person_Movie` where `Person_Movie`.`personId` = ?)
```

Was the `Result` you posted the thing you want or the thing that is currently happening?

**Comment by kdmcclel** [comment]
The result was what I am looking for.

**Comment by koskimas** [comment]
So what you actually want is this:

```js
person
  .$relatedQuery('movies')
  .patch({
      name: 'The room'
  })
  .where('order', 1)
```

to produce

```sql
update `Movies` set `Name` = 'The room' where `Movies`.`id` in (select `Person_Movie`.`movieId` from `Person_Movie` where `Person_Movie`.`personId` = ? and `Person_Movie`.`order` = 1)
```

?

In your example both `order` and `name` were in the patch object.

Unfortunately this is currently difficult to implement since objection doesn't parse `where` calls. It simply passes them to knex. We would need to parse the `where` calls and then move the ones that mention one of the extra properties to the subquery.

I will close this for now if you can live with your workaround? We may need to start parsing the `where` calls at some point and this will be supported after that.

**Comment by koskimas** [comment]
I don't know if you missed it, but there was a question in my last comment 😄 

Did you want to:

 1. update extra columns?
 2. or filter row using extra columns?

**Comment by kdmcclel** [comment]
Sorry, I read that you'd leave it since I had a workaround I was using and didn't reply.

Yeah I am just looking for a way to update related data using a where on the join table.  My actual thing is users, user_phones and phones.  My join table primary key is user_id, phone_id, type (enum: Home, Cell, etc) for fast lookups.

So I want some way to updated related phone number where the user_phones.type = 'Home'.  I wrote the proposed example as I did because that's how the insert statement works with the extra field on the relation.

**Comment by kdmcclel** [comment]
Ah to answer both your questions.  I would like number 2 but I could see my original issue post someone could want to change the movie order as well.

Either way my work around is already in place and live so this isn't a pressing issue.

**Comment by kdmcclel** [comment]
Seems like 1 would need 2 in place anyway.  So you'd end up doing:

```
person
  .$relatedQuery('movies')
  .patch({
      name: 'The room',
      order: 2
  })
  .where('order', 1)
```

**Comment by koskimas** [comment]
1 is actually already implemented.

Filtering using extra columns would be cool, but unfortunately it's currently too difficult to implement because of the things I explained in an earlier comment. If knex ever gets a "reflection" system that allows users to inspect the called methods (wheres, selects etc.), I'll add this. It may be never, so I'll close this for now.

**Comment by kdmcclel** [comment]
Sorry if this reopens the issue. How does 1 work? Does it update all
related? Wouldn't every movie be 'The room' after that and all order
columns are 1?

**Comment by koskimas** [comment]
You can filter the query based on all `Movie` fields, but not `Movie_Actor` (join table) rows:

```js
person
  .$relatedQuery('movies')
  .patch({
      name: 'The room',
      order: 2
  })
  .where('name', 'Matrix')
  .where('releaseYear', 1999)
```
