### ISSUE TITLE
required column and $relatedQuery.insert bug

### ISSUE THREAD

**Issue by jsnick** [Vincit/objection.js#393]
Three models are `User`, `UserTeam`, `Team`.

```
class User extends Model {
  static get tableName () {
    return 'users'
  },

  static get relationMappings () {
    userTeams: {
      relation: Model.HasManyRelation,
      modelClass: require('~/server/models/UserTeam'),
      join: {
        from: 'users.id',
        to: 'userTeams.userId',
    },
  },
}

class UserTeam extends Model {
  static get tableName() {
    return 'userTeams'
  },
  
  static get jsonSchema () {
    return {
      type: 'object',
      required: ['userId', 'teamId'],
    }
  }

  static get relationMappings () {
    user: {...},
    team: {...},
  },
}

class Team extends Model {
  ...
}
```

I have an error when query below
```
user.$relatedQuery('userTeams').insert({ teamId: team.id })

// errors
Error: {
  "userId": [
    {
      "message": "should have required property 'userId'",
      "keyword": "required",
      "params": {
        "missingProperty": "userId"
      }
    }
  ]
}
```

If I remove jsonSchema from UserTeam, that query works. 
(I checked userId, teamId saved is correct.)

**Comment by koskimas** [comment]
You have `userId` marked as required. Remove it from the `required` list and things will work. `jsonSchema` is not the database schema. You need to think of it as the schema for objects that can be used to create model instances. You cannot mark properties as `required` and then instantiate models without them like you do in `insert({ teamId: team.id })`. If you want to enforce that a database row is never created without `userId` or `teamId`, use database constraints.

**Comment by dhasilva** [comment]
Just hit this problem here.

I believe the OP is right to report this as a bug, since he is not using `User.query().insert({ teamId: team.id })`, he is using `user.$relatedQuery('userTeams').insert({ teamId: team.id })`. That is, the `user_id` is implicit through `user`. It seems "hacky" to remove `user_id` from the required list just to be able to accomplish this.

Great work with Objection, by the way :)

**Comment by Juanpam** [comment]
Hello @koskimas and thanks for Objection.js! Seems awesome so far.

I've also encounter this issue while attempting to create something similar to OP. Like @dhasilva , I think it would come it handy to have this feature since the jsonSchema often represents constraints from the db schema. Removing the `required` property may be a workaround but it removes the wanted validation.

To mantain some validation within the model, I think it is possible to use the hooks $beforeInsert and $beforeUpdate to do the validation in the related model. Doing so, it should be possible to generate a new instance without the reference Id but that can only be inserted/updated when the reference Id is present.
