### ISSUE TITLE
Inverted OneToOneRelation?

### ISSUE THREAD

**Issue by devoidfury** [Vincit/objection.js#40]
User.relationMappings = {
		business: {
			relation: Model.OneToOneRelation,
			modelClass: Business,
			join: { from: 'business.user_id', to: 'user.id' }
		}
	};

Is there any way to do something like this currently, where the foreign key is on the other model?

**Comment by koskimas** [comment]
Inverted OneToOne is a OneToMany so just create a OneToMany relation?

**Comment by koskimas** [comment]
Yeah I get what you mean, It would  be nice to be able to define `hasOne` and `belongsTo` relations that are both one-to-one. I'll take this into consideration.

Relation fetches are currently implemented as a separate queries instead of a joins for simplicity of implementation. Using joins (especially for many-to-many and one-to-many relations) would be a real pain in the ass because of the way the node db drivers are implemented. It would result in a huge amount of created objects with redundant properties when joining multiple relations. 

You can easily do a join in both directions using something like this:

```js
User.query().where('id', 1).join('business', 'business.user_id', 'user.id').then(function () {

});
```

but you get the joined flat row as a result instead of a nested object.

**Comment by devoidfury** [comment]
Well, it should still be one-to-one, but just switch which model the key is on.

Using OneToMany does two queries, instead of a join:


Knex debug output:

	{ method: 'select',
	  options: {},
	  bindings: [ 1 ],
	  sql: 'select * from "user" where "id" = ?' }
	{ method: 'select',
	  options: {},
	  bindings: [ 1 ],
	  sql: 'select * from "business" where "business"."user_id" in (?)' }

Resulting data:

	.then(function(user) {
		console.log(user)
	})

	>>>
		{
		  id: 1,
		  username: 'devoidfury',
		  email: '',
		  staff_level: 3,
		  created_at: 1445904873428,
		  last_seen: 1446347989822,
		  business:
		   [ Business { // will only ever be one business
		       user_id: 1,
		       next_action: 1446348033630,
		       name: "test" } 
		   ] 
		}

**Comment by devoidfury** [comment]
Nevermind, just realized that OneToOneRelation doesn't do a join automatically, either.

**Comment by devoidfury** [comment]
Thanks for the clarification. And I'm enjoying the library, appreciate your work on it!
