### ISSUE TITLE
pickJsonSchemaProperties problem

### ISSUE THREAD

**Issue by pulse14** [Vincit/objection.js#407]
Hi,
First, thank you for your work on objection. Looks very promising. 

`pickJsonSchemaProperties ` is set to true on a model, let's say `Post`. Posts have a `categories` relation. `categories` is not in my json schema.

When I insert data : 
```javascript
{title:"title", categories:"tampered data, will cause exception"}
```
It raises an exception `You should only pass objects to $setJson method. $setJson method was given an invalid value 1`.

I understand what objection try to do here, but I want him to consider relations only when I tell him to do. `pickJsonSchemaProperties ` don't omit relation fields during validation but 

> when inserting or updating a row in the database.

Is there any way to omit field from raw data passed to `update()` or `create()` before any Model instance creation ?

Thank you

**Comment by koskimas** [comment]
Hi, thank you!

Relations actually do get stripped away whether `pickJsonSchemaProperties` is true or false right before the actual insert operation, but the relations are first parsed into models in when `insert`, `update` or `patch` is called. This means that everything works if the relation property contains valid models, but if there is something else (like ids in your case?) this happens.

I cannot strip away the relation properties because some people do things like modify the object based on related models in `$beforeInsert` and `$beforeUpdate`. What I probably can do is not try to parse the relations into model instances if they contain non-objects which would fix this error.

I'll try to fix this and report my findings here.

**Comment by koskimas** [comment]
This should now be fixed in master. You can test it by putting this
```
"objection": "git://github.com/Vincit/objection.js.git#a3c84b5"
```
in your package.json.

**Comment by pulse14** [comment]
thank you !
