### ISSUE TITLE
leverage ajv cache and serialize function

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#411]
Currently objection [manages the compiled schema cache itself](https://github.com/Vincit/objection.js/blob/546e1e7ab56a9161da648ba655c9217d770826de/lib/model/AjvValidator.js#L68).
However [ajv has a cache too](https://github.com/epoberezkin/ajv/blob/fde7030a19833273b08e8de879cb2bf149adaf2f/lib/ajv.js#L298).
To avoid that redundancy, i suggest objection could use directly the ajv cache.
To keep the optimization of costly serialization of the schema to build the cache key, objection could track changes in `jsonSchema` setter, to increment a schema non-enumerable property, used by `serialize` to return a cache key.

**Comment by fl0w** [comment]
Correct me if I'm wrong, but to my recollection one simply has to pass the schema to ajv and it'll use it's cached instance if available? It's not something that has to be setup/configured by consumer, correct?

**Comment by kapouer** [comment]
The links i gave above show that objection optimizes the common case when the class schema did not change, by maintaining its own cache to avoid ajv doing a useless `json-stable-stringify(schema)` just to get a unique cache key.

**Comment by koskimas** [comment]
One of the biggest reasons to switch to AJV was performance. `JSON.stringify` is slow compared to the actual validation and AJV's serializer is even slower. The most important optimization `AjvValidator` has (on the line you linked) is that we skip the `JSON.stringify` and AJV's serializer when the `jsonSchema` is the default one (it hasn't been changed). Even if we leveraged AJV's cache, we would need to keep that optimization and the code wouldn't get that much cleaner.

I don't know how we could detect the jsonSchema changes.. A setter cannot be implemented since using ES6 the jsonSchema is defined as a gettter:

```js
class Person extends Model {
  static get jsonSchema() {
    return {...};
  }
}
```
And even if we could, that's not the place we're watching for. The schema can be changed in `$beforeValidate`. I would really like to get rid of that feature, but I don't know how many people are using it.

Is this causing you some problems or what promted this issue?

**Comment by kapouer** [comment]
Originally yes but now i don't have any issue (i'm in the `jsonSchema === ModelClass.getJsonSchema()` case). However i thought letting the user build its own cache key would be better than falling back to `JSON.stringify`.

**Comment by koskimas** [comment]
Why would a user want to build its own cache key?

**Comment by kapouer** [comment]
To avoid the call to JSON.stringify...

**Comment by koskimas** [comment]
Why should it be avoided? AJV cache basically uses a slower (but sorting) version of JSON.stringify to generate the keys (at least last I checked). Is the sorting property something you find useful here?

**Comment by kapouer** [comment]
I think what ajv is doing is worse, unless the user provides a key through the ajv's serialize option, in which case it can be much more efficient since the user knows how/when schemas were changed.
However, my point was that this last sentence is made impossible in objection since objection builds its own key, regardless of what the user wants.

**Comment by koskimas** [comment]
Ok, now I finally get it 👍 I didn't know that AJV allowed a customer serializer to be used. I'll figure something out for this.
