### ISSUE TITLE
InsertAndFetch could use pg `returning` trick under the hood ?

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#427]
It would optimize it for us !

**Comment by koskimas** [comment]
I haven't done this because I'm not 100% sure it is equivalent to fetching the row in all cases. Maybe there are some corner cases in which the name `insertAndFetch` is misleading. What's wrong with using explicit `returning('*')` instead of `insertAndFetch`? Are you using different database for testing and production or something similar?

**Comment by kapouer** [comment]
Luckily, no, i'm using postgres everywhere :)
However it would be cool.

**Comment by koskimas** [comment]
I don't see this in line with objection's philosophy of avoiding magic. I'll close this for now. I'll revisit if someone requests this again.
