### ISSUE TITLE
provide findByIds as a way of retrieving multiple items by their Id

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#544]
Objection has `findById`, IMHO it would be nice if it had `findByIds` as well.

**Comment by koskimas** [comment]
I'd accept a pull request for this. If you decide to implement it, note must work (and be tested) also with composite keys. `whereInComposite` function is probably the method you'd want to use.

**Comment by capaj** [comment]
@koskimas thanks! That was really easy. Too bad the codebase is not formatted with prettier-had to turn it off in my vscode.
BTW would that be a PR you'd accept? Codebase reformatted with prettier?

**Comment by koskimas** [comment]
@capaj maybe! That would be very beneficial if/when objection gets more contributors. I've never used prettier before. Since it's pretty opinionated, let me play around with the settings a bit first to see if I can live with its opinions 😄

Also I'd like to avoid a build phase. [A git pre-commit hook](https://medium.com/@brindelle/format-your-javascript-with-prettier-before-committing-177079ec356a) is probably the way to go? I'd also like to avoid the need to install prettier globally, so the pre-commit hook should be written using the binary from `node_modules` if possible.

**Comment by capaj** [comment]
Yeah a hook is the way to go-ideally via https://github.com/okonet/lint-staged.
I will prepare the PR. You can tweak prettier settings in there.

**Comment by capaj** [comment]
@koskimas PR is here #560, should be running a local prettier.
