### ISSUE TITLE
Add upsertGraphAndFetch() method

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#556]
`insertGraph()` and `upsertGraph()` are both extremely useful methods. `insertGraph()` has a version called `insertGraphAndFetch()`. I have a use case for `upsertGraphAndFetch()`, returning the full result of the upsert.

Would it be difficult to add this, based on the existing work on `insertGraphAndFetch()`? I am happy to help out if I can, but have yet to understand the structure of the `QueryBuilderOperation` classes.

**Comment by koskimas** [comment]
This is a good idea. Basically the implementation would be a pretty close copy of `InsertGraphAndFetchOperation`. I can implement this at some point, but I'd be happy to help you with a pull request.

**Comment by lehni** [comment]
I am happy to give this a go. I've been looking at the various `QueryBuilderOperation` classes, and one thing that had me a bit confused was the fact that there are three versions of `onBefore()` and `onAfter()` hooks. I imagine this has something to do with sequence and importance, but how do you decide which number to use in each case, and why are three enough? Is there a text somewhere perhaps that explains these operations?

**Comment by koskimas** [comment]
@lehni There are multiple `onBefore` and `onAfter` hooks so that some parts of some operations can be executed before/after all other operations have been executed. For 95% of the operations one pair of hooks would be enough, but I had to add the other two to support some of the more complex ones without changing the whole architecture. Having three hooks feels like a hack to me too, but I haven't been able to come up with a better architecture, and I have tested many. Inheritance is probably not the best tool to implement the QueryBuilderOperations, but it has been good enough.

The only documentation is in `QueryBuilderOperation` base class. Most of the time it doesn't matter which one of the hooks you use. Only if you inherit an operation from another, you need to see what the parent operation does and select the hook based on that.

**Comment by lehni** [comment]
@koskimas thanks for the explanation! I will start looking into things now, also in connection with my `insertMissing: true` discovery today (https://gitter.im/Vincit/objection.js?at=59ec67b6210ac2692017e36f)
