### ISSUE TITLE
do we have any method to generate migration file now from model?

### ISSUE THREAD

**Issue by njleonzhang** [Vincit/objection.js#575]
migration generation can be done by `knex`, do we have any method to generate migration file now from model?

**Comment by wswoodruff** [comment]
Heyo @njleonzhang and other `Objection.js` peeps! We're working on a (WIP) cool migration project called [schwifty-migration](https://github.com/BigRoomStudios/schwifty-migration) that addresses migration file generation.

Right now with this lib you can only use [schwifty](https://github.com/BigRoomStudios/schwifty) models (they have a `Joi` schema). The lib is pretty specific to our own usage, but in the future we will add support for models with Objection's default JSON schema.

Just lettin' you know we're working on it!

**Comment by koskimas** [comment]
There's no such method in objection core and I don't think there should be. I think @wswoodruff and his team is your best shot right now 😄

**Comment by njleonzhang** [comment]
Tnx for your effort. wait for new migration tool. 👍

**Comment by vjpr** [comment]
I agree it should be kept out of core.

Some thoughts on a plugin implementation:

You should maintain a "squashed" latest migration inside your models.

There should be a migration function taking `knex` as a param, inside the model file.

There would be two functions, because if you are adding references, you need the table you are referencing to have been created first, and we don't want to have to worry about ordering our model migrations. Call them `migrate` and `migrateAfter`.

You could generate these migrations in separate properties (say `generatedMigrate`), and then the user could:

a. use the generated ones by a simple reference from `latestMigration`.
b. copy-paste from the generated ones into their custom one.
c. easily compare them against their custom `latestMigration`.

Then you would custom write your alter tables and add them to knex-migrate files. (Doing this in an automated way is too much effort and would be problematic if it wasn't perfect.)

There would be a tool to run the `migrate` functions together, then in a separate stage run the `migrateAfter`.

Then to verify your "squashed" schema:

- create a database from scratch from your migration files
- create a database from the squashed migrations
- diff the databases (I'm sure someone has written a tool for this already)

```js
import {Model} from 'objection'

class Person extends Model {
  static jsonSchema = {
    properties: {id: {type: 'string'}},
  }

  static relationMappings = {
    parent: {
      relation: Model.BelongsToOneRelation,
      modelClass: Person,
      join: {
        from: 'Person.parentId',
        to: 'Person.id',
      },
    },
  }

  static migrate = async knex => {
    knex.raw('CREATE SCHEMA IF NOT EXISTS foo')
    knex.raw('ALTER DATABASE SET search_path = public,foo')
    knex.createTable('foo.Person', (table) => {
      table.increments('id').primary()
    })
  }

  static migrateAfter = async knex => {
    await Person.generatedMigrateAfter(knex)
  }

  // Generated from jsonSchema.
  static generatedMigrate = async knex => {
    knex.raw('CREATE SCHEMA IF NOT EXISTS foo')
    knex.raw('ALTER DATABASE SET search_path = public,foo')
    knex.createTable('foo.Person', (table) => {
      table.increments('id').primary()
    })
  }
  
  static generatedMigrateAfter = async knex => {
    knex.alterTable('Person', (table) => {
      table.foreign('parentId')
        .references('id')
        .inTable('Person')
    })
  }
  
}

```

### Why maintain `migrations/` and "squashed migrations"?

This is a good question, and I am not so sure about it. What I can think of though is:

- Faster testing. Avoid running time consuming data migration logic when setting up. Avoid redundant alter table commands.
- Enourages recreating databases often rather than keeping an old dev database around. Quickly create new databases for each test run.
- More convenient to visualise your table's schema - data types, references, etc.
