### ISSUE TITLE
Recommended way to run $beforeInsert/$beforeUpdate in custom QueryBuilder

### ISSUE THREAD

**Issue by mfreshy** [Vincit/objection.js#576]
I have a Model using a custom QueryBuilder (which provides an custom DB-specific operation). My model looks roughly like this:

```
export default class MyModel extends Model {

  static get QueryBuilder() {
    return MyQueryBuilder;
  }

  static query<T>(this: { new (): T }, trx?: Transaction): MyQueryBuilder<T> {
    // To satisfy typescript compiler
    return (<any>super.query(trx)) as MyQueryBuilder<T>;
  }

  $beforeInsert() {
    console.log("[beforeInsert]");
  }

  $beforeUpdate() {
    console.log("[beforeUpdate]");
  }
}
```

And MyQueryBuilder is defined as:
```
export class MyQueryBuilder<T> extends QueryBuilder<T> {
  
  customOperation<T>(model: T[] | Partial<T>[]): Promise<T[]> {
    const knexInst = knex(dbConfig);
    const query = `UPDATE value .... <custom query here>`;

    return new Promise<T[]>((resolve, reject) => {
      knexInst
        .raw(query)
        .then((result: { rows: T[] }) => {
          resolve(result.rows);
        });
    });
  }
}
```

What I'm finding is that the `$beforeInsert`/`$beforeUpdate` hooks are not called when I call the custom function (`MyModel.query().customOperation()`). I'm assuming this is because people extending QueryBuilder are responsible for calling `$beforeInsert`/`$beforeUpdate` manually. 

But what is the recommended way to do this? What are the best practices around providing a custom QueryBuilder?

**Comment by koskimas** [comment]
You can simply call the hooks. They are nothing special. You can access the context argument the hooks take using `QueryBuilder#context()` method. You also probably need to convert your input into model instances so that you can call the hooks. `QueryBuilder.fromJson` and `QueryBuilder.fromDatabaseJson` can be used for that.

There are also couple of things I would change in your method:

## 1. 
```js
const knexInst = knex(dbConfig);
```
You always create a new knex instance when the method is called. This is a very bad idea. You can use `this.knex()` to get the query builder's knex instance.

## 2.
You don't need to wrap promises into new promises. You can change this:
```js
    return new Promise<T[]>((resolve, reject) => {
      knexInst
        .raw(query)
        .then((result: { rows: T[] }) => {
          resolve(result.rows);
        });
    });
``` 

into this:

```js
    return knexInst.raw(query);
```

Casting it to `T[]` is simply wrong since the result of an update is an array of numbers. Even if it was rows, you need to first create instances of `T[]` before casting to it.
