### ISSUE TITLE
Add caveats section to docs (taking suggestions for content!)

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#580]
I'll add a caveats section to docs. Please comment in this issue if you know of a caveat in objection.

Caveats:

- Relation and a property cannot have the same name

**Comment by ncjones** [comment]
Besides the above issue with relations I also had issues with transactions - in particular the relationship between transactions and mysql connections. I assumed that a rejected promise (due to constraint violation etc) would always roll back the transaction. I also assumed that a single mysql connection would be used by multiple concurrent transactions. It seems both my assumptions were wrong and the result, unexpectedly, was that the connection pool was exhausted given enough uncommitted transactions. I had to do a lot of digging through Knex Github issues to find out what was really going on. The fix was to change `.catch(logger.error)` to `.catch(e => { tx.rollback(); logger.error(e); }`.

**Comment by koskimas** [comment]
@ncjones Transactions are committed or rolled back automatically based on the returned promise. You have probably forgotten to return the promise or done something else wrong. There is no way there's a bug in that.

Pooling and other connection management related things have nothing to do with objection and they also work as expected (except in the couple of recent buggy knex versions). There's nothing in your comment that I see as a caveat.

**Comment by koskimas** [comment]
> Relation and a property cannot have the same name

This already has an error in place. I'm closing this since it doesn't seem to gain any content
