### ISSUE TITLE
Cordova SQLite / Websql in-browser support

### ISSUE THREAD

**Issue by jimthedev** [Vincit/objection.js#6]
Hello there. 

We have relational data that we would like to be able to represent in the same way on both the server and client. The reason we want it to work in the client is that our app works offline (with a custom sync solution). It would be absolutely amazing if this library was tested again the [cordova sqlite implementation](https://github.com/litehelpers/Cordova-sqlite-storage) and the related websql browser equivalent. Would you ever consider this kind of thing as a goal of this project or is this kind of thing out of scope?

**Comment by koskimas** [comment]
Hi,

websql is already supported by [knex](http://knexjs.org) which we use for all query building and connection handling. And since websql is basically sqlite, moron.js already has tests for it. Assuming cordova's webgl implementation follows standards things should just work.

The problem is running moron.js in the browser. I'm pretty sure this cannot be done at the moment even if you use browserify. I would have to make a browser build.

If I get more requests like this in the future I will certainly consider the browser build. Until then I'll probably concentrate on other features.

**Comment by mparpaillon** [comment]
That would be great indeed

**Comment by koskimas** [comment]
It turns out, all packages moron.js uses are browser compatible. You can try running it in the browser using browserify. First create a file moron-browser.js with contents:

```js
window.moron = require('./moron.js');
```

To the root rolder of moron.js. Then install browserify:

```sh
npm install -g browserify
```

And then run it

```sh
browserify moron-browser.js -o moron-bundle.js
```

The bundle can be used in a web page:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>moron.js</title>
  <script src="lodash.js"></script>
  <script src="bluebird.js"></script>
  <!-- The knex.js browser build -->
  <script src="knex.js"></script>
  <script src="moron-bundle.js"></script>
  <script>
    var knex = Knex({
      client: 'websql',
      connection: {
        filename: 'test.db'
      },
      // Disable pool.
      pool: {
        max: 0,
        min: 0
      }
    });

    function Test() {
      moron.Model.apply(this, arguments);
    }

    moron.Model.extend(Test);
    Test.tableName = 'Test';
    Test.knex(knex);

    knex.schema.createTable('Test', function (table) {
      table.bigincrements('id');
      table.string('text');
    }).then(function () {
      return Test.query().insert({text: 'test 1'})
    }).then(function () {
      return Test.query();
    }).then(function (models) {
      console.log(models);
    });

  </script>
</head>
<body>

</body>
</html>
```

Knex throws an error with the example above. Don't know if there is something wrong with my code, or if it is a bug in knex.

**Comment by jimthedev** [comment]
@koskimas Interesting. Thanks for looking at it. I'll take a peak later today. Excited!

**Comment by jimthedev** [comment]
Potentially related to Knex error: https://github.com/tgriesser/knex/issues/877

**Comment by mparpaillon** [comment]
I'll definitely give this a try :+1: 

Thanks !

**Comment by koskimas** [comment]
There are two bugs in knex, both described in the issue @jimthedev attached. Until they are fixed you can get things running by using the version 2.9.27 of bluebird and by replacing the line:

```js
err.message = SqlString.format(obj.sql, obj.bindings) + ' - ' + err.message;
```

with

```js
try {
  err.message = SqlString.format(obj.sql, obj.bindings) + ' - ' + err.message;
} catch (ignore) {
   // `message` is sometimes a getter.
}
```

in the knex.js file. I also updated the example I posted before.

**Comment by jimthedev** [comment]
@koskimas Did you create a PR with the fix in Knex? Would this work long term?

**Comment by koskimas** [comment]
Sorry, I forgot to answer this. 

I didn't create a PR because I'm not familiar enough with knex's internals. My solution was a hack to make it work for our tests.

Unfortunately I cannot give any guarantees about this since I don't have tests for browsers. Making the integration tests run also on browsers seems like a lot of work, and I don't think I have time to do that any time soon.

**Comment by kapouer** [comment]
None of my business, but i suspect this issue would better be labelled as "won't fix" instead of being closed.

**Comment by koskimas** [comment]
I can add the wontfix label, but I don't want to keep these issues lying around forever when no-one seems to be interested in them.

**Comment by jmwolfe** [comment]
@jimthedev , did you ever get this working? I'm still looking for the best ORM for CordovaSQLite and this solution looked promising, except all the working around of the Knex defects.
