### ISSUE TITLE
Possible knexSnakeCaseMappers relations bug

### ISSUE THREAD

**Issue by sexualmaniac** [Vincit/objection.js#614]
Hello

I am waiting for [this feature](https://github.com/Vincit/objection.js/issues/472) and I tried new `knexSnakeCaseMappers` in my project, but the model relations don't work until I define them in camelCase.

Is this expected or a bug?

**Comment by koskimas** [comment]
When the mapping is done in knex, objection knows nothing about snake_case. As far as objection is concerned the database has been defined using camel case. Everything that knex returns and takes is camelCased when you use the knex's mappers. That's just how they work. So yes, it is expected.

So you would like to defined relations using snake case, but how would you like to write queries? Like this:

```js
Person.query().where('first_name', 'foo')
```

or like this:

```js
Person.query().where('firstName', 'foo')
```

?

**Comment by sexualmaniac** [comment]
@koskimas makes sense. I'm using snake_case column names in migrations, queries, relations. The camelCase conversion is used only for api input/output.

I would like to keep using snake case everywhere, this variant:

```js
Person.query().where('first_name', 'foo')
```

**Comment by koskimas** [comment]
Ok, then you can still use the old way of making the mapping using `$parseDatabaseJson` and `$formatDatabaseJson` hooks. I'll probably add helpers for that too so that you can do this:

```js
const { camelizeKeys, snakifyKeys } = require('objection');

class BaseModel extends Model {
  $parseDatabaseJson(json) {
    return camelizeKeys(json);
  }

  $formatDatabaseJson(json) {
    return snakifyKeys(json);
  }
}
```

**Comment by sexualmaniac** [comment]
@koskimas so with `super` it will look like this one?

```js
const { camelizeKeys, snakifyKeys } = require('objection');

class BaseModel extends Model {
  $parseDatabaseJson(json) {
    return super.$parseDatabaseJson(camelizeKeys(json));
  }

  $formatDatabaseJson(json) {
    return snakifyKeys(super.$formatDatabaseJson(json));
  }
}
```

**Comment by koskimas** [comment]
Yep

**Comment by sexualmaniac** [comment]
@koskimas looks great, I'm fine with this solution. Thank you!

**Comment by sexualmaniac** [comment]
@koskimas hm, from source code, there are already default [functions](https://github.com/Vincit/objection.js/blob/master/lib/model/Model.js#L147-L153) in model hooks. When [they](https://github.com/Vincit/objection.js/blob/master/lib/model/modelJsonAttributes.js#L5-L45) execute, there is an iteration over the object properties.

Maybe camel/snake case conversion can be added in this functions so we don't have to iterate over the object properties twice? To turn on/off the conversion we can use model static property like suggested in https://github.com/Vincit/objection.js/issues/472.

It looks like a really elegant solution which doesn't pollute the code and will make it possible to easily trigger efficient conversion per model. What do you think?

**Comment by sexualmaniac** [comment]
This two solutions will be added to the docs with a description about what's different so you can choose what fits you best. Both of them will be possible to trigger with just one line of code:

```js
// model conversion
static useSnakeCaseConversion = true

// knex conversion
...knexSnakeCaseMappers()
```

Looks really good to me.

**Comment by koskimas** [comment]
The whole conversation in #472 was about adding such flag and I have been against it the whole time. Now I think it's even worse idea since there are two ways to do that (hooks and knexSnakeCaseMappers).

Performance is definitely not an issue here. Iterating over the object is super fast. I have peformance tests that I run before each release (in the perf folder). You can iterate over an object that has ~10 properties millions of times a second.

**Comment by sexualmaniac** [comment]
@koskimas yep, it's mostly about convenience.

Since we'll have this two methods anyway, the idea of adding a static property for turning them on is not that bad. It's very useful when you want only some of your models to do the conversion.

I followed that issue and never understood why you were against it, this feature is very useful. I'll use it in every project. Since there will be explanation about both methods in the docs, I don't think there will be any problems with them later.

**Comment by koskimas** [comment]
I'm mostly against it because I feel like there is a way to achieve this that is only couple of lines, but that doesn't seem to be enough for people. The current solution is generic while adding a specific flag for snake_case conversion is not. I also personally feel like doing the conversion is a bit stupid. It can cause all kinds of problems and therefore more issues for me to explain/solve. There is really no reason to use different casing in db and code but some conventions from 30 years ago. People just seem to blindly follow them.

**Comment by koskimas** [comment]
But if I'm going to add the converter functions anyway, adding the flag is only a little worse, so I'm beginning to think I should just add it, no matter how stupid I think it is just to get people leave this issue alone. I'd like to actually work with some useful new stuff instead of this.

**Comment by sexualmaniac** [comment]
@koskimas this is just a personal preference, same as with semicolons or not, tabs or spaces. There'll always be people who prefer one to another and don't understand the opposite choice.

I've been using snake case in my databases for like 4 years and I just like how it works. So, although it's not a model flag yet, I'm really happy the support for  https://github.com/Vincit/objection.js/issues/472 is coming to objection.

Thank you for such a great library and support!

**Comment by koskimas** [comment]
No it is not. Semicolons or not or tabs versus spaces have no unwanted side effects. Snake case conversion has. There's alot of code to maintain just to make it work.

How would you feel about a solution like this:

const { snakeCaseMappers } = require('objection');

class BaseModel extends Model {
  static columnNameMappers = snakeCaseMappers();
}

This way the feature would still be generic and when the next group of people want an UPPER_CASE to camelCase, or a PascalCase to camelCase conversion, we can easily add it. snakeCaseMappers would be a function so that we can give it options, just like knexSnakeCaseMappers, because surely someone soon wants it to work a little different.

**Comment by sexualmaniac** [comment]
@koskimas I know about `knexSnakeCaseMappers` side effects, but what side effects does model hooks conversion has?

This solution is flexible, is it needed though, are there any requests for other conversions besides snake and camel ones?

**Comment by koskimas** [comment]
Not yet, but there surely will be at some point. If I add a `useSnakeCase` boolean we're locked with only snake case conversions and adding another will be a breaking change. Also I'm pretty sure I'll see an issue in the future about people wanting a different kind of snake_case conversion. For example by default `foo1Bar` is converted to `foo1_bar` and some people prefer `foo_1_bar` (default in lodash snakeCase). So we need options in any case, and I feel this is the simples way to enable properties.

```
static useSnakeCase = true;
```

```js
static columnNameMappers = snakeCaseMappers();
```

are both one single line, while the latter doesn't lock the API.

As for the side effects, I've had to implement the `$parseDatabaseJson` and `$formatDatabaseJson` system. Also wherever I use properties and columns in the objection codebase I need to make sure they are converted correctly. The conversions are present everywhere. Try to search `columnNameToPropertyName` and `propertyNameToColumnName` from the codebase. That's a separate issue though, since they are already implemented. I just mentioned that as an example how case conversion complicates things, while tabs vs. spaces does not.

**Comment by sexualmaniac** [comment]
@koskimas yep, you solution is actually well thought and doesn't lock us from future changes, I like and support it.
