### ISSUE TITLE
Loading related on demand

### ISSUE THREAD

**Issue by sebbarg** [Vincit/objection.js#616]
Hi,

What is the best way to do a demand-$loadRelated() ?

E.g. calling `jennifer.pets.length` would automagically call `jennifer.$loadRelated('pets')` on first access to jennifer.pets.

Or is that the wrong pattern to be using with objection.js?

Thanks!

**Comment by koskimas** [comment]
Hi,

I think possible way to implement this is using a `Proxy`. I don't know how well this would work with objection in general though. That's the kind of thing I have been trying to avoid 😄 I started using node and writing objection.js after getting frustrated with Hibernate that does exactly that.

Your example won't be possible (with any javascript ORM) since there is no way to resolve async stuff (the query) before accessing a property (.length).

**Comment by koskimas** [comment]
This is doable with proxies:

```js
const numPets = await jennifer.pets.length;
```

**Comment by koskimas** [comment]
And this you can do just by adding instance getters for models:

```js
const numPets = (await jennifer.pets).length;
```

for example this kind of magic should work:

```js
class Animal extends Model {
  ...
}

Object.keys(Animal.relationMappings).map(relName => {
  Object.defineProperty(Animal.prototype, relName, {
    get() {
      return this.$relatedQuery(relName);
    }
  });
});
```

**Comment by sebbarg** [comment]
@koskimas Thanks!

So I'm guessing that you don't advocate this kind of design - how do you go about demand loading relations yourself?

I had the same proxy-thoughts in mind as your example shows, but I can see that when I run `jennifer.$loadRelated('pets')` then property pets is created - is it then overwriting the proxy?

Either way it (as you say) becomes a bit of a mess of sync and async code...

**Comment by koskimas** [comment]
Something like this should work:

```js
class Animal extends Model {
  ...
}

Object.keys(Animal.relationMappings).forEach(relName => {
  Animal.prototype[`get${_.upperFirst(relName)}` = function () {
    if (this[relName]) {
      return Promise.resolve(this[relName]);
    } else {
      return this.$relatedQuery(relName);
    }
  }
});
```

Now you could call:

```js
const animal = await Animal.query().findById(1);

const owner1 = await animal.getOwner();
// This will not start a query.
const owner2 = await animal.getOwner();
```

You could create a common `BaseModel` super class for all your models and run the getter generation code for example in `query` method  or someplace else that always gets called before you would use the getters (maybe constructor). Just make sure you don't generate those each time.

Another option would be to add for example `rel` property and generate getters there so that you can do this:

```js
const animal = await Animal.query().findById(1);

const owner1 = await animal.rel.owner;
// This will not start a query.
const owner2 = await animal.rel.owner;
```

**Comment by koskimas** [comment]
Maybe you could run the generation code in [getRelations()](http://vincit.github.io/objection.js/#getrelations).
