### ISSUE TITLE
Why objection does not verify the schema with seed file?

### ISSUE THREAD

**Issue by slim-hmidi** [Vincit/objection.js#620]
I have this model:
```
class Product extends Model {
  static get tableName() {
    return 'product';
  }
  static get jsonSchema() {
    return {
      type: 'object',
      required: ['name'],

      properties: {
        id: { type: 'integer' },
        name: { type: 'jsonb' },
      },
    };
  }
}
```
And I put some data in the seed file:
```
knex('product').insert([
          {name: {"key1": "product1", "key2": "produit1"},{name: {"key1": "product2", "key2": "produit2"}
        ]);
```

First case: I fill the table with seed file and I run the query:
```
Product.query().where('id',1).then(prod => 
{
  console.log(prod)
}
```
I got : 
```
name: {"key1": "text1","key2": "text2"}
```

Second Case: I used a real database and I got such a result:
```
name: '{"key1": "text1","key2": "text2"}'
```
And I got such an answer [#619](https://github.com/Vincit/objection.js/issues/619) about the `jsonb` that is not type in JSON schema. When does the verification of json schema occurs and if there is an error what it should returns?

**Comment by koskimas** [comment]
You use knex to seed. There is no way objection can know what you do with knex.

**Comment by koskimas** [comment]
And also, the postgres driver returns jsonb colums as strings. Everything is as it should be here.

**Comment by koskimas** [comment]
Aaaand json schema is only validated when you insert or update using __objection__. Why would we validate data coming from the database :smile:

**Comment by slim-hmidi** [comment]
Thank you for the information.

**Comment by slim-hmidi** [comment]
with type `jsonb` I got result such as : ` name: '{ 'key1': 'text1', 'key2': 'text2' } '` and with type `object` I got : ` name: { key1: 'text1', key2: 'text2' }`?

**Comment by elhigu** [comment]
@slim-hmidi because node-postgres driver deserialises it. check pg-types.

**Comment by slim-hmidi** [comment]
@elhigu according to the previous comments the json schema is validated only for insert and update of tha data.But for my case I have data on my postgresql database that contains a column name of type `jsonb`. When I put on the json Schema the name of type jsonb I got the result like this : `name: '{ 'key1': 'text1', 'key2': 'text2' } '` changing the type to object type the result became `ame: { key1: 'text1', key2: 'text2' }`. So I didn't understand when the json schema validate occurs?

**Comment by elhigu** [comment]
Sooo... you are wondering why first letter of `name` is dropped and it becomes `ame`? Or is it unclear why setting column type to be `object` in `jsonSchema` changes parsing of `jsonb` type of column?

First one I suppose it is just typo. Second one objection **uses** `jsonSchema` also when it loads data from DB, but **it does not use it for validating read data**. 

It uses it to figure out if column is `object` type and in that case it parses also `text` type of column like there would be `json` data. So `objection` uses `jsonSchema` just to figure out which columns should be parsed to `objects`.

ps. json scehma validate happens when you insert or update data to DB
