### ISSUE TITLE
Add "as of version x.x" to documentation

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#645]
Just a thought:
I often find myself revisiting the Objection docs when I am trying to do something that's not become "routine" for me. Sometimes I find a solution, but am not sure if I missed it last time I was there or if it's relatively new. Sure, I can search the page for the thing in question until I hopefully find it in the Changelog, but it would be nice to see an "as of version x.x" listed next to any API items. Not sure if it would be easy to do this retroactively or not, too.

Thanks either way for Objection!!!

**Comment by koskimas** [comment]
It's a good idea, but it would be really difficult to do retroactively. Also I can barely make myself write the current level of documentation. I don't want make that process more complex. Writing docs sucks 😄

One way to check if a method existed in a version is to click on a tag in the [releases](https://github.com/Vincit/objection.js/releases) tab and go to the docs folder. Since the documentation is generated from markdown files, it's pretty readable there too.

**Comment by newhouse** [comment]
understood...thanks!
