### ISSUE TITLE
custom throw in model constructor

### ISSUE THREAD

**Issue by seeden** [Vincit/objection.js#665]
I am not able to see my error from constructor of the model.

I see just your error:
Model.relationMappings.role: join.from must have format TableName.columnName. For example "SomeTable.id" or in case of composite key ["SomeTable.a", "SomeTable.b"].

It is because you are catching everything in the objection/lib/relations/Relation.js  function createRelationProperty

**Comment by koskimas** [comment]
How could that be improved while keeping the current functionality? Why are you throwing from a constructor?

**Comment by koskimas** [comment]
The code path that executes `createRelationProperty` is only ran once per relation the first time you use the model. The problem is that objection cannot initialise the relation because your invalid constructor throws every time when used inside objection. 

The error message you see is correct for the errors thrown from `createRelationProperty` 99% of the time. It's not more specific because I had a lot of people filing bug reports caused their typos in relation mappings before I wrote that error message there.

We could add the actual error as a cause for the error you are seeing, but ecmascript and node.js have a support for that (that I know of.. Some libraries support a `cause` property on error, but I'm pretty sure node itself doesn't).

Your constructor is invoked in `createRelationProperty` because this function is used:

```js
function columnNameToPropertyName(ModelClass, columnName) {
  // This is your model class's constructor.
  const model = new ModelClass();
  const addedProps = Object.keys(model.$parseDatabaseJson({}));

  const row = {};
  row[columnName] = null;

  const props = Object.keys(model.$parseDatabaseJson(row));
  const propertyName = difference(props, addedProps)[0];

  return propertyName || null;
}
```

Whatever you do in your constructor, you need to prepare for no input arguments, because that's how it is sometimes used internally. You probably shouldn't do anything in your Model's constructor though.

What are you trying to do in the constructor? There probably is a better way to achieve that in objection.

**Comment by seeden** [comment]
My models need to have static property modelName and jsonSchema as well.
I added this check in the constructor of the "Base" class because I am doing a big refactor from bookshelf to objection. (You are doing same check for relations there as well) I was confused because I saw bad relation but it was caused by my throw.

```js
  constructor(...args) {
    super(...args);

    if (!this.constructor.modelName) {
      throw new Error('Model must have a static property modelName');
    } else if (!this.constructor.jsonSchema) {
      throw new Error('Model must have a static property jsonSchema');
    } else if (!this.constructor.relationMappings) {
      throw new Error('Model must have a static property relationMappings');
    }
  }
```

**Comment by koskimas** [comment]
Maybe you override `static fromJson` and move that check there?
