### ISSUE TITLE
knex: timeout connection 

### ISSUE THREAD

**Issue by slim-hmidi** [Vincit/objection.js#681]
Knex version: 0.13.0
objection: 0.8.9
OS: 17.04

I have a knexfile.js:
```
{
  client: postgres,
  connection: {
    host: postgres.host,
    database: postgres.database,
    user: postgres.user,
    password: postgres.password,
  },
  pool: {
    min: 2,
    max: 10,
  },
};
```
```
const userSave = async function userSave(user) {
const userItem = await User
    .query()
    .where('code', user.code);

  if (userItem.length === 0) {
    return User
      .query()
      .insert(user)
      .returning('*');
  }
  const userDelete = await User
    .query()
    .delete()
    .where('user.id', userItem[0].id);
  if (userDelete > 0) {
    return User
      .query()
      .insert(user)
      .returning('*');
  }
}
const users = dataMapping(JSON.parse(data).users);
users.forEach((user) => {
userSave(user);
});
```
The reproduction file:
```
let Model;

try {
  Model = require('./').Model;
} catch (err) {
  Model = require('objection').Model;
}

const Knex = require('knex');
const chai = require('chai');

async function main() {
  await createSchema(); // comment this line for the second test to verify the existence of a user.

  ///////////////////////////////////////////////////////////////
  // Your reproduction
  ///////////////////////////////////////////////////////////////
  const userSave = async (user) => {
    const userItem = await User
    .query()
    .where('code', user.code);
  if (userItem.length === 0) {
    await User
      .query()
      .insert(user)
  }
  const userDelete = await User
    .query()
    .delete()
    .where('user.id', userItem[0].id);
  if (userDelete > 0) {
    await  User
      .query()
      .insert(user)
  }    
}
userSave({name: 'test', code: 123456 });

}

///////////////////////////////////////////////////////////////
// Database
///////////////////////////////////////////////////////////////

const knex = Knex({
  client: 'sqlite3',
  useNullAsDefault: true,
  connection: {
    filename: './backend.sqlite'
  }
});

Model.knex(knex);

///////////////////////////////////////////////////////////////
// Models
///////////////////////////////////////////////////////////////

class User extends Model {
  static get tableName() {
    return 'user';
  }

  static get jsonSchema() {
    return {
      type: 'object',

      properties: {
        id: {type: 'integer'},
        name: {type: 'string', minLength: 1, maxLength: 255},
        code: { type: 'integer'},
        }
      }
    }
  };

///////////////////////////////////////////////////////////////
// Schema
///////////////////////////////////////////////////////////////

async function createSchema() {
  await knex.schema
    .dropTableIfExists('user')

  await knex.schema
    .createTable('user', table => {
      table.increments('id').primary();
      table.string('name');
      table.integer('code');
    })
}

main()
  .then(() => console.log('success'))
  .catch(console.error);
```
I have a problem when saving a huge amount of data into the database and I got this error:

```
Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

Does this due to parallel connections to database.
I'm not asking how to save the data into the database however I'm asking about the problem when there are many connections to the database.

**Comment by koskimas** [comment]
The point of a reproduction is to _reproduce_ the problem. This one doesn't.

 I'm pretty this is some kind of user error, but if that really does happen, the bug is not in objection but in knex or pg. Objection uses knex which handles pooling etc.

Anyways you shouldn't run 3000 database queries in parallel. You should run them in batches of some sensible size. And actually with postgres, you can insert multiple rows at a time.

**Comment by koskimas** [comment]
I just ran this test on all supported databases and it works just fine:

```js
      it('run a huge amount of inserts in parallel', () => {
        return Promise.all(_.range(10000).map(i => {
          return Model1.query().insert({model1Prop1: i});
        }));
      })
```

**Comment by koskimas** [comment]
Actually what I think is happening is that your inserts simply take so much time that some of the queries that are waiting for a connection from the pool simply time out. The solution is to not run all the inserts in parallel.

This is one way to do that:

```js
const _ = require('lodash');
const userBatches = _.chunk(users);

for (let batch of userBatches) {
  await Promise.all(batch.map(userSave));
}
```

**Comment by newhouse** [comment]
FWIW, I have experienced this as well when setting up some test scenarios such as enforcing limits where I need to set up the DB with "many thousands" of items before getting started. I investigated it for a while and wasn't able to 100% determine the culprit, so my memory is a little bit rusty on the subject, but it seemed to come out when there were many rows using graphInsert that I'd "queued" into an Array and then called `Promise.all(manyInserts)` on. Investigating the pool and connections on PG led me to mess around with the pool min and max size, but I found that increasing the pool size actually made the problem worse.  To me it seemed like some sloppy/lazy setup on my part that triggered some combination of deadlock and/or race condition. I realized that this would only be a problem that would occur naturally to my code under extremely high usage, and I would just deal with that when the time came, if I was so lucky, so I just lowered the "thousands" down to a more reasonable number and the problem went away.

I think there may be something to this in the "graph" area, but I could not be sure and decided to fight that battle another day so I never filed a ticket. Could also very well just be stupid user error/expected behavior given pool mins/maxes, etc, or a pg/pool issue. Figured I'd add in this color in case you were going to think about looking into it some more. My gut tells me it's not an objection issue, though.

**Comment by slim-hmidi** [comment]
@koskimas  the solution of inserting data using this example : 
```
const _ = require('lodash');
const userBatches = _.chunk(users, 10);

for (let batch of userBatches) {
  await Promise.all(batch.map(userSave));
}
```
will take so much time when I have a thousands of data to insert. I don't think this will resolve the issue.

**Comment by elhigu** [comment]
@slim-hmidi if it is properly coded it shouldn't take more than minute to run... inserting > 1000 rows per second should not be a problem even for sqlite. 

Maybe your bottle neck is somewhere else. Here is runkit example, which inserts 50k lines in a 300 milliseconds with batch size of 100 rows https://runkit.com/embed/cfwsdby24ftb

**Comment by KrisLau** [comment]
Hi I know this is an old issue but any idea what could be causing this query to timeout? It's just a select and join query:
```
const eventOccurrences = await EventOccurrence.query().alias('eo')
                .select(['eo.id', 'eo.event_id', 'e.team_id'])
                .innerJoinRelated('event as e');
```

Context:


Every time it runs I keep getting a `Timeout: Request failed to complete in 15000ms`
