### ISSUE TITLE
Change user supplied values in $beforeValidation

### ISSUE THREAD

**Issue by sebbarg** [Vincit/objection.js#698]
Say I need to trim user supplied strings before saving them to the database. It needs to happen before the validations are run.

Right now I'm doing it in $beforeValidation (changing the json members) which seems to be working. But I'm wondering if it is the right place to do it?

**Comment by koskimas** [comment]
$parseJson is a better place for that.

**Comment by vvo** [comment]
Hey there, just in case someone needs this too, usually I want to trim ALL string attributes before validation because I can't think of a good usecase for now in my app that would allow things like name: "            Hello", so in my BaseModel (https://vincit.github.io/objection.js/api/model/static-properties.html#static-modelpaths) I did this:

```js
class BaseModel extends Model {
  $parseJson(json, opt) {
    // Remember to call the super class's implementation.
    json = super.$parseJson(json, opt);

    return Object.entries(json).reduce((newJson, [property, value]) => {
      if (typeof value === "string") {
        newJson[property] = value.trim();
      } else {
        newJson[property] = value;
      }

      return newJson;
    }, {});
  }
}
```

It works for me, let me know what you think @koskimas (could this break?).
