### ISSUE TITLE
`insert` performing validations as if it was `insertGraph` when data contains property that matches a `relation`

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#721]
Happy New Year, everyone!!! 🎆 👊  Objection is still my super fave and I'm in it all day long.

I'm in the process of updating my `pg`, `knex` and `objection` (from `0.7.12` to `0.9.4`) and I came across some "unexpected behavior" that has definitely changed since `0.7.12`, although I didn't see anything in the "Breaking Changes" that I think covers it.

- If you try to perform an `insert()` query using data that contains a property that matches a `relation` that is defined on the Model class you're trying to insert, Objection will validate that property's value as if it were actual relational data on an `insertGraph` query.
- So, even though you're not using `insertGraph()`, if the value of `parentDataYouAreInserting.sameNameAsRelationButNotGraphData` doesn't pass the validation that would be enforced using an `insertGraph` query, Objection will throw an error.
- Because it's an `insert()` query, I would expect Objection to not perform any validation on any data that was not defined in the Model's `jsonSchema` (which I have done), and certainly not on portions of that data that match (on purpose, or not) a `relation` on that Model.

[Here's a working gist that reproduces it.](https://gist.github.com/newhouse/cd0f05ef83308d9972fb00df93ff2f95)

I have not tried it with any other relation types or gotten more clever with it than I've provided in my gist, but I wonder...

Nevermind the exact reasons how or why I actually came to encounter this error, because they're irrelevant...so the example may seem a bit contrived, but nontheless I believe this is what I would call "unexpected behavior".

**Comment by koskimas** [comment]
Weird, I'm pretty sure that's the way it has always worked. The reason is that some people use the relations in hooks and they need to be validated at that point. I think it is important that whenever you get your hands on a model instance, you can be sure it has been validated.

Here are the relevant places in code for 0.7.12.

1. A test that verifies, relations are parsed into model instances.
https://github.com/Vincit/objection.js/blob/0.7.12/tests/unit/model/Model.js#L899

2. Here you can see that `ensureModel` is used to do that conversion.
https://github.com/Vincit/objection.js/blob/0.7.12/src/model/Model.js#L346

3. Here's `ensureModel` that calls `fromJson` for each object, which in turn calls `$validate`.
https://github.com/Vincit/objection.js/blob/0.7.12/src/model/Model.js#L921

Anyway, this has always been around, and if it didn't work, that was a bug. I don't think this should be changed.

**Comment by koskimas** [comment]
This is not documented, but I could document it and make it public if it helps you:

```js
const person = Person.fromJson(req.body, { skipParseRelations: true });
await person.$query().insert();
await Person.query().insert(person);
```

**Comment by koskimas** [comment]
Also with objection 1.0, this is possible `const model = modelGraph.$clone({shallow: true})`

**Comment by newhouse** [comment]
Yeah, it is weird. It's definitely a change as in this branch I've literally just updated my `package.json` and then been hunting down explosions that it caused, but if this was a bug all along and is actually the expected behavior, then I can accept that answer!

Thanks for the suggestions - there are plenty of ways to solve this, so if you were hesitant to publicize the `{ skipParseRelations: true }` option for some reason, I don't think it's super helpful (at least for my scenario) to do so now. Totally up to you.

Thanks again for all the hard work done by you and the other contributors/maintainers. I, and a lot of others, really appreciate it!

**Comment by newhouse** [comment]
Again, a million ways to do this, but since in my case I was not trying to actually get an instance from JSON, merely just set up the DB with some stuff for my tests, I ended up adding a static method to my `Base` Model class that returns only the keys of the JSON schema I've defined on each Model, like so:
```
  static get jsonSchemaProperties() {
    return Object.keys(_.get(this, 'jsonSchema.properties', {}));
  }
```

And then in my code I can do:
```
const relationlessParentData = _.pick(parentDataWithUnwantedRelationData, SomeModel.jsonSchemaProperties);
```

Thanks again for everything!
