### ISSUE TITLE
Problems with eagerJoin and resultSize

### ISSUE THREAD

**Issue by desher** [Vincit/objection.js#728]
I'm trying to count total result size of query with .joinEager('file') and .eagerOptions({ joinOperation: 'innerJoin' }) by using resultSize() function. The total SQL generates with "left join".

Query:
```javascript
UserFile.query()
        .joinEager('file')
        .eagerOptions({ joinOperation: 'innerJoin' })
        .internalOptions({ debug: true })
        .resultSize();
```

total SQL:
```sql
select count(*) as `count` from (select ... from `user_file` left join `fh_file` as `file` on `file`.`id` = `fh_user_file`.`file_id`) as `temp`
```

Also I have one more question. If I run the query with .resultSize(), I will get an error with message "TypeError: Cannot read property 'columns' of undefined at RelationJoinBuilder.buildSelects". If I run the query without resultSize() and then run query again with resultSize, then that will work fine. Is it a bug?

Objection: 0.9.4

**Comment by koskimas** [comment]
I think `debug: true` is causing the error. That's a known issue, but very difficult to fix.

The query should work. I have no idea why `left join` ends up there. I'll test this and get back to you. You could use `innerJoinRelation` here though and `count` instead of `resultSize`:

```js
UserFile.query()
        .innerJoinRelation('file')
        .count();
```

**Comment by koskimas** [comment]
By the way, you shoudn't call `internalOptions`. That's a private method. You can use `.debug()` instead.

**Comment by koskimas** [comment]
Oh, it seems that `resultSize` doesn't work with `joinEager`. The error is not caused by `debug: true`. It will work if you have ever ran the `joinEager` without `resultSize` before during the lifetime of the process because the thing that blows, up is cached. The problem is that `joinEager` cannot be used as a subquery because it fetches and caches the table schema, the first time a new table is encountered.
