### ISSUE TITLE
patchAndFetchById using withSchema

### ISSUE THREAD

**Issue by cbritton** [Vincit/objection.js#76]
Using postgres, I have a table called item in a schema called 'test'.  Adding a new row works fine with this construct:

>    const item = yield Item
>          .query()
>          .withSchema('test')
>          .insert({name: 'data', description: 'test info'});
>    console.log(item);

Updating the row using this code:

>   try {
>      const itemUpdated = yield Item
>          .query()
>          .withSchema('test')
>          .patchAndFetchById(item.id, {name: 'test item'});
>  } catch(err) {
>      console.log(err);
>  }

I checked the results in the database and the update is successful, however, the fetch is failing with this error:

>{ [error: select * from "item" where "item"."id" = $1 - relation "item" does not exist]
>  name: 'error',
>  length: 96,
>  severity: 'ERROR',
>  code: '42P01',
>  detail: undefined,
>  hint: undefined,
>  position: '15',
>  internalPosition: undefined,
>  internalQuery: undefined,
>  where: undefined,
>  schema: undefined,
>  table: undefined,
>  column: undefined,
>  dataType: undefined,
>  constraint: undefined,
>  file: 'parse_relation.c',
>  line: '1156',
>  routine: 'parserOpenTable' }

I'm not sure if the schema name is being passed into the subsequent patchAndFetchById call.  Is there something else I need to provide?

**Comment by koskimas** [comment]
There are many query methods that actually create multiple queries, and of course `patchAndFetchById` is one of them. `withSchema` only works correctly for single-query methods. I don't know why I'm only realising this now, but this is a bug. Why would anyone ever want to use `withSchema` so that it only affects the first query. 

There may be something that I don't remember now that makes this difficult, since I have thought about this before and decided not to set the schema for all queries. I'll think this through again and if I cannot come up with good reasons, I'll fix `withSchema`.

There is a workaround though using [query context](http://vincit.github.io/objection.js/#context):

```js
const itemUpdated = yield Item
  .query()
  .context({
    onBuild: builder => builder.withSchema('test')
  })
  .patchAndFetchById(item.id, {name: 'test item'});
```

To fix the `withSchema` method you can [implement your own query builder](http://vincit.github.io/objection.js/#custom-query-builder):

```js
const QueryBuilder = require('objection').QueryBuilder;

class MyQueryBuilder extends QueryBuilder {
  withSchema(schema) {
    return this.context({onBuild: builder => builder.withSchema('test')});
  }
}

// Instance of this is created when you call `query()` or `$query()`.
objection.Model.QueryBuilder = MyQueryBuilder;
// Instance of this is created when you call `$relatedQuery()`.
objection.Model.RelatedQueryBuilder = MyQueryBuilder;
```

**Comment by koskimas** [comment]
I'll soon release the 0.5.0-alpha.0 version that has the updated `withSchema` method that passes the schema to all internal queries. You can install it using npm install objection@next
