### ISSUE TITLE
Fields set in $beforeInsert are ignored by jsonSchema validation

### ISSUE THREAD

**Issue by Feld0** [Vincit/objection.js#77]
I'm using `$beforeInsert` in my models to set a few fields automatically (`id` and timestamps) when creating a model but the JSON Schema validation rejects my call to `{Model}.query().insert({})` when the schema expects those fields to be present.

Both JSON schema validation and this mechanism of automatically setting fields are documented, so it seems they should play well together.

**Comment by koskimas** [comment]
So you have something like `required: ['id', 'createdAt']` in the `jsonSchema`? Are the fields really "required" since you generate them on insert? Isn't the correct fix here just to remove those properties from the `required` list?

Let's think what it means for validation if you don't mark those as required:

 * insert: Nothing since you generate them
 * update: There is no validation error if the values are missing on update. Isn't this desired? When do you really want to update `id` or `createdAt` timestamp?

In jsonSchema there is a difference between setting a value to `null` and omitting it. You can still validate that `id` and `createdAt` cannot be set to null using the `type` field in jsonSchema.

Having said all that, there may be similar cases where validation before `$beforeInsert` is a bad thing and I can't think of any reason why we couldn't just move the validateion after the `$beforeInsert` call. I'll see if se could just move it without breaking anything.

**Comment by Feld0** [comment]
Yeah - I included these fields in `required` in `jsonSchema` with the idea that they'd be checked for before the model is saved to the database. If my code that generates the ID's and timestamps somehow failed or didn't run, the validation wouldn't let it through because I'd be trying to insert invalid data.

I might be misunderstanding the semantics of required fields in the jsonSchema - I saw this as a means to validate data before writing it to the database whereas what you describe, @koskimas, sounds more like validating user input.

You're right that `id` and `created_at` won't be getting updated on a regular basis. :smiley: Ensuring they're not null might be more appropriate for my use case than setting them to "required". I'll try that!

**Comment by koskimas** [comment]
`jsonSchema` validation in objection is designed with input validation in mind. I thought about moving the validation after `$beforeInsert` and `$beforeUpdate` methods, but I'm afraid people are doing things in those methods assuming the input has already been validated. Moving the validation would be a breaking change and I'm not sure which place is better for it. I wont change anything yet, but I'll leave this issue open.

**Comment by elhigu** [comment]
@Feld0 I'll add my 5cents about this.

Your DB already has schema which should already validate that timestamp is set correctly. So if your timestamp was not generated correctly DB will fail the query? 

So current flow is  Input -> jsonSchema validation -> $beforeInsert -> DB schema validation -> all good row stored.

If you put jsonSchema validation just before DB schema validation, the validation done by jsonSchema would be just duplicate (with less features) of the validations that DB schema already does...

**Comment by thetutlage** [comment]
@Feld0 jsonSchema validation has to be the first step, so that you can make use of `$beforeInsert` with confidence without adding multiple `if and else`.

**Comment by koskimas** [comment]
I'll have to agree with @elhigu and @thetutlage.
