### ISSUE TITLE
Request "instanceOf" in JsonSchema typescript definitions.

### ISSUE THREAD

**Issue by TsvetomirGeorgiev** [Vincit/objection.js#794]
Hello guys,

First - great work at supporting this project !!!

I have a request. Can you please include type definition for ```instanceOf``` to the ```JsonSchema``` interface? Something like this should work:

```
interface JsonSchema {
  ...
  instanceOf: string | string[];
}
```

I'm currently struggling with validation of date fields and I could be missing something in the documentation. My date fields would instances of Date once loaded from the database, but most of the time would be coming from the request as date-time strings. In the model I'm defining them as 
```
dateField: string | Date
```
Later in my code if I need to modifiy them I make the nessesary checks. However, in order for this to work properly I'm adding the follwing json schema: 

```
dateField: { oneOf: [{ type: 'string', format: 'date-time' }, { instanceOf: 'Date' }] }
```
And as the ```instaceOf``` is missing in the JsonSchema interface I'm getting TS errors.

Also, can you guys please share some insights of how are you dealing with dates.

Thanks !

**Comment by newhouse** [comment]
@TsvetomirGeorgiev Are you using the `pg` driver for your knex connections? If so, you probably want to check out this issue https://github.com/Vincit/objection.js/issues/663 and in particular this comment https://github.com/Vincit/objection.js/issues/663#issuecomment-351678734

I also was experiencing this "inconsistent" behavior, and the solution was to choose which way I wanted to always deal with dates (`string` vs `Date`), adjust those `pg` settings if necessary (i.e. if you decide to go with `string`) and then consistently code using the chosen type in all of your model dealings.

**Comment by TsvetomirGeorgiev** [comment]
Thank you, @newhouse , for the insight. I'm actually doing something similar with another project which uses ```bigints``` for primary keys without the need for it. And because of that my primary keys were returned as strings.. I'll probably go for always strings and cast when actually needed. 

In this case, I would probably not use the ```instanceOf``` validator. Should I just close the issue or? The library already supports it and it would be a minor change.

**Comment by newhouse** [comment]
You're very welcome, of course.
I contribute, but I'm not a maintainer, but if I had to guess I don't think that your original request is likely to be incorporated. You could wait until a maintainer chimes in to see what they think. Your call.

**Comment by mordof** [comment]
@koskimas  `instanceof` isn't part of json schema itself. Nor does `ajv` support it out of the box.

It's a feature provided by `ajv-keywords` for additional capability: https://github.com/epoberezkin/ajv-keywords#instanceof

I think it only makes sense to add `instanceof` to the json schema typings if ajv became a locked-in validator, and `ajv-keywords` was included. Otherwise, a type would be added to the schema which actually isn't valid under other circumstances.

With the decision to remove dependencies for v2, this also becomes more complicated. Will Ajv become an optional dependency? would ajv-keywords also be an optional dependency? How would the types for json schema handle optional dependencies/special functionality for those cases.

A possibility: What if JsonSchema were set up in a way that developers could extend the definition? Right now with the capability to modify the validator, developers can already tie in `ajv-keywords` themselves. The only problem left in that case is the JsonSchema types - I think it'd make sense for the types to be changed/messed with in some way since the part making use of it also can be changed.
Not sure exactly how the types would look like for that yet.

**Comment by koskimas** [comment]
Yep, not part of the json schema, so won't be added.
