### ISSUE TITLE
Multi-tenancy recipe results in infinite open connections

### ISSUE THREAD

**Issue by JoaoCnh** [Vincit/objection.js#803]
I am trying to use the same recipe provided in the docs for multi-tenancy.

When each tenant has a different database I have to connect to that specific one.
But after a simple findById query the connection does not close. If I keep hitting refresh I keep seeing the connection number go up. 

Only when I shut the server down the number drops completely or when I call knex.destroy(); after the query.

Has anyone got this problem?

**Comment by koskimas** [comment]
The multi-tenancy example isn't a complete example. For example, there is no implementation for `getDatabaseForRequest`. Without knowing how you implemented that, there's no way for anyone to help you. Could you share the code? You need to cache the knex connections in that function so that you don't create a new one for each request.

**Comment by JoaoCnh** [comment]
getDatabaseForRequest returns a brand new knex object correctly configured. I've already checked a million times. Even if I cache it wouldn't it maintain always 1 connection open at all times for every request?

Basically the same problem

**Comment by koskimas** [comment]
If you always return the same knex instance for the same tenant, then you have `tenanats.length` connections and not the number of requests. I don't understand your problem.
