### ISSUE TITLE
ensureModelArray is prematurely returned if undefined is given to an insert query

### ISSUE THREAD

**Issue by jkantr** [Vincit/objection.js#862]
https://github.com/Vincit/objection.js/blob/master/lib/model/Model.js#L639

Which means `ensureModel()` never gets called, which means an instance of the Model is never created. Which means that validation never takes place. Which means that `User.query().insert(undefined)` resolves to... null. Which is sort of a weird thing to get back from `User.query().insert(foo)` when one might expect a ValidationError if `foo` is undefined.

Am I missing anything? :(

**Comment by koskimas** [comment]
`insert(undefined)` and `insert([])` mean "insert nothing" in objection. Maybe a better way to handle this would be to throw an error, but it has been like this since the first versions of objection. Because of this, there is probably code relying on this behaviour and changing this would be a breaking change requiring a major version bump. Since you are the first person to bring this up as an issue, I don't think we should change the behaviour. You just have to live with it.

**Comment by jkantr** [comment]
Fair :) but I think we should consider documenting it as a footgun. 

Again, insert() does *not* insert nothing. Insert({}) properly triggers jsonSchema validation and throws if there are 'required' fields. Insert() does not. A model instance is never made and the schema never checked. My issue isn't "it inserts nothing", but rather, it fails to validate required fields (which is what "inserts nothing" would suggest).

The documentation is unclear to me that validation doesn't happen if you insert() (nor any lifecycle hooks, like $beforeInsert)

At the minimal I think it being documented is necessary. Better however would be a "strict mode"  model flag that would make insert() behave like insert({}). Would you be open to a PR that introduces this safety mechanism?

**Comment by koskimas** [comment]
You're right. I'd be happy to merge a PR!
