### ISSUE TITLE
knexSnakeCaseMappers fails to work when using stream interface and pg

### ISSUE THREAD

**Issue by jkantr** [Vincit/objection.js#864]
Not exactly sure where to file this. Using `knexSnakeCaseMappers` works fine, even using the knex object itself and not the Objection api. However, when using `pg` and the `.stream()` interface, the data comes back with unmapped fields. Can you confirm that this is `knex`'s `wrapIdentifier` API misbehaving?

**Comment by koskimas** [comment]
Try to write your own mappers to see if they get called.

**Comment by koskimas** [comment]
Closing this because objection doesn't have a streaming API and knexSnakeCaseMappers is only designed to work with objection. This is probably a bug in knex anyway. @jkantr If you do find out that the mappers are called, but knexSnakeCaseMappers fails to do the conversion, I can try to fix it. Post your findings here.
