### ISSUE TITLE
How to add fields in join table of many-to-many relations?

### ISSUE THREAD

**Issue by afm-sayem** [Vincit/objection.js#87]
I want to save relation specific information(i.e. the role a person played in a movie) in the join table. When defining many-to-many relations in the model, can I specify any additional property that can be passed when the relation is created?

**Comment by koskimas** [comment]
There is no easy way, but you can do this:

1. Create a model for the join table.
2. Pass the model to the relation definition in the relationMappings using [`join.through.modelClass`](http://vincit.github.io/objection.js/#relationmappings)
3. Use [query context](http://vincit.github.io/objection.js/#context) feature cleverly :smile:

The third step means something like this:

```js
class JoinTableModel extends Model {
  $beforeInsert(context) {
    if (context.role) {
      this.role = context.role;
    }
  }
}

someModel
  .$relatedQuery('theManyToManyRelation')
  .context({role: 'theRoleForTheJoinRow'})
  .insert({...});
```

So the query context is also passed to the join row insertion. Since we defined a model for the join table, its `$beforeInsert` gets called and the context is passed to it.

How awful does this sound? :smile:

**Comment by afm-sayem** [comment]
Neat! :smiley: 

Not sure how do I fetch this data, though. How would I query `Person` model to get the `Movie` along with her `role` in the movie?

**Comment by koskimas** [comment]
I would just use a join. The first example only works on 0.5.0-alpha.X and newer versions. `MoviePerson` is the join table in the examples:

```js
Person
  .query()
  .eager('movies')
  .filterEager('movies', builder => {
    builder
      .join('MoviePerson', 'MoviePerson.movieId', 'Movie.id')
      .select('Movie.*', 'MoviePerson.role as role');
  });
```

With objection 0.4.X (and newer) you can do this:

```js
Person
  .query()
  .eager('movies(joinRole)', {
    joinRole: builder => {
      builder
        .join('MoviePerson', 'MoviePerson.movieId', 'Movie.id')
        .select('Movie.*', 'MoviePerson.role as role');
    }
  });
```

Or if you already have the person fetched (works on all versions):

```js
person
  .$relatedQuery('movies')
  .join('MoviePerson', 'MoviePerson.movieId', 'Movie.id')
  .select('Movie.*', 'MoviePerson.role as role');
```

**Comment by afm-sayem** [comment]
0.5 one looks neat! time for an upgrade :camel:

**Comment by elhigu** [comment]
@afm-sayem you can start using latest features already by installing "objection@next" :tada:

**Comment by afm-sayem** [comment]
cool!
