### ISSUE TITLE
How to retrieve sql queries

### ISSUE THREAD

**Issue by vickpalomo** [Vincit/objection.js#888]
How can I get the sql queries made during the update or insertion of a graph?

**Comment by koskimas** [comment]
The most reliable way to do it is to use knex hooks. You need to override your model's `query` method to add the hook. Something like this:

```js
class BaseModel extends Model {
  static query(...args) {
    return super.query(...args).onBuildKnex((knexQueryBuilder, builder) => {
      knexQueryBuilder.on('query', queryData => {
        // queryData contains the sql (not really sure in which format. I've never used this).
        // Now you can do what you want with the query. One option is to save it to the builder's
        // context.
        builder.context().queries.push(queryData);
      });
    });
  }
}
```

And then instead of inheriting your models from `Model` inherit them from `BaseModel`.

```js
class Person extends BaseModel {
  ...
}
```

Now you can do something like:

```js
const queries = [];
await Person
  .query()
  .mergeContext({ queries })
  .insertGraph(graph);
```

This is just an example that demonstrates the possible tools to do it. It's probably not the best way to write it, but you should be able to get it done using these features. I didn't run the code, there may be typos.
