### ISSUE TITLE
Forcing use of transactions

### ISSUE THREAD

**Issue by sebbarg** [Vincit/objection.js#901]
Say I have a model that updates some other table in its $afterInsert() method. If that code for whatever reason throws an exception, I want it to roll back the originating database insert. I can do that if I remember to start the query() with a transaction. So far so good.

Say I forget to put that transaction in place. Is it possible (i.e. not too much of a hack) to force using a transaction in $beforeInsert() or is it simply too late (or just not supported)?

Somehing along these lines:

```javascript
async $beforeInsert(queryContext) {
  const trx = queryContext.transaction;
  if (typeof trx.commit !== 'function' || typeof trx.rollback !== 'function') {
    queryContext.transaction = await transaction.start(queryContext.transaction);
  }

  // ...
}

async $afterInsert(queryContext) {
  // queryContext.transaction is now an actual transaction

  // ...
}
```

**Comment by koskimas** [comment]
Starting a transacrtion on the fly will cause more problems than it solves. Just consider an eager query that suddenly starts multiple nested transactions for the created queries. Not good.

Why not just use something like this:

```js
async $beforeInsert(queryContext) {
  const trx = queryContext.transaction;
  if (typeof trx.commit !== 'function' || typeof trx.rollback !== 'function') {
    throw new Error('transaction needed');
  }
}
```

which would get caught in the tests immediately and would force you to start a transaction explicitly? Unfortunately that's the best way to detect if `queryContext.transaction` is actually a transaction since knex doesn't provide a `isTransaction` or similar.

**Comment by sebbarg** [comment]
I kind of feared it wasn't a very good idea ;) I wanted a way keep the "dependency" logic contained within the Model, preferably without having to wrap the query().insert() stuff. But it is not a big deal - thanks! And thanks for this project, it is a joy to use :)
