### ISSUE TITLE
DefinitelyTyped

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#929]
Hi,

Following [message about types](https://github.com/Vincit/objection.js/pull/255) of @mceachen, current advice is a little different from the original message:

> 1. bundling with your npm package, or
> 2. publishing to the @types organization on npm.
> If your package is written in TypeScript then the first approach is favored.
> ...
> If your package is not written in TypeScript then the second is the preferred approach.

Is there any plan to publish typings on DefinitelyTyped?

Kind Regards,

**Comment by koskimas** [comment]
What will we gain by publishing to DefinitelyTyped?

**Comment by ozum** [comment]
It is related to conventions of typescript users. TypeScript's encouraged way to use non-typescript npm modules is installing typings from @types. (Even a definition cannot be found, error messages suggest to install @types/some-lib)

```
$ npm install some-library @types/some-library
```

Even I use `objection` in my JS projects, for TS, I missed that it has well developed type definitions. I started to write my half baked and erroneous definitions, then I realized its type definitions.

Another gain would be that some developers may choose libraries written in TS or having type definitions available and first place they look is DefinitelyTyped repo.

**Comment by mceachen** [comment]
I don't see a value-add here--DT is great if the module owner doesn't want to be bothered by typings, but the objection team has been welcome to them. Keeping the types close to the source facilitates easier versioning and better, more coherent PRs.

More recently, I've seen very popular projects, like [vue](https://medium.com/the-vue-point/upcoming-typescript-changes-in-vue-2-5-e9bd7e2ecf08), migrate _from_ DT (I think mostly due to a lack of PR quality). I've personally witnessed broken types (and subsequently spurious compilation errors) due to well-meaning but broken nonetheless DT PRs.

In general, the most successful DT projects have pretty simple APIs that are "set and forget"--the intricate ones (like objection) might do well by keeping the API expertise "in house."

**Comment by mceachen** [comment]
@ozum I think better documentation around objection's TypeScript support would have fixed the issue here, which is that you didn't know the types were there already, right? I'm sure @koskimas would be amenable to any documentation suggestions you'd come up with to fix this.

**Comment by ozum** [comment]
@mceachen, yes you are right, my first concern was that I missed that type definitions are there, which is no problem for me further, because I know now.

Second concern is for other developers, that they may miss too and for that, I have three documentation suggestions if appropriate:

1. A mention in description: An SQL-friendly ORM for Node.js and TypeScript
1. A bullet in "What objection.js gives you" section (README and API doc)
1. Examples for TypeScript in API doc like `ESNext` examples.

Finally, my last concern is for visibility and discoverability of `objection` library and support from community of TS. OTH, @mceachen mentioned some valid reasons not to put in DT. If I were you, I put there, but every developer work different and has their own way, so considering pros and cons is up to you.

Kind Regards,

**Comment by koskimas** [comment]
I have no opinion about this, but I'll go with @mceachen's. @ozum About your documentation suggestions:

1. Nope. Node.js is a platform, Typescript is a programming language. That sentence would either imply node.js and typescript are comparable, or that the only language you can use is typescript.

2. Good idea, let's add them.

3. A shit ton of work. Feel free to create PR's for those, but I won't be writing them. If you do create a PR, note that we are moving away from the current documentation site and all documentation updates should made against the `new-docs` branch and the markdown files in `newDoc` folder instead of `doc`.
