### ISSUE TITLE
Access old values in beforeUpdate ?

### ISSUE THREAD

**Issue by getvega** [Vincit/objection.js#94]
Given a model 

```
export default class User extends Model {
    static tableName = 'users';
    async $beforeValidate() {
        console.log('beforeValidate', this, arguments);
    }
    async $afterValidate() {
        console.log('afterValidate', this, arguments);
    }
    async $beforeUpdate() {
        console.log('beforeUpdate', this, arguments);
    }
    async $afterUpdate() {
        console.log('afterUpdate', this, arguments);
    }
}

// then
const user = await User.query().insert({ a: 1 });
await user.$query().patch({ a: 2 });
```

Seems like I never have the old value `{ a: 1 }` in `this`or `json`. Is it possible?

**Comment by koskimas** [comment]
queries started using `$query()` method are a bit confusing. You would expect that calling:

```js
user.$query().patch({a: 2})
```

would call `$beforeUpdate` with `this` being the callee object before the update, but actually `this` is the patch object itself. This is because you often want to do stuff like this in the `$beforeUpdate`:

```js
$beforeUpdate() {
  this.updatedAt = new Date()
}
```

Now if `this` was the old object, and not the patch object, `updatedAt` would not get updated in the db. This makes more sense with the static `query()` method where there is no "old state".

What is the use-case here? Why do you need the old values in the `$beforeUpdate`?

**Comment by getvega** [comment]
I guess this is related to https://github.com/Vincit/objection.js/issues/81

I understand the implementation here but my usecase is close to that simplified one : 

```
const user = ...;
// set a status
user.$query().patch({ status: 'DELETED' });

// if status is different from the previous one, set deletedAt on the patch
$beforeUpdate(previous) {
  if (this.status === 'DELETED' && previous.status !== this.status) {
    this.deletedAt = new Date()
  }
}
```

With such a hook handling those dates on the whole lifecycle would be easy : NO STATUS => VALIDATED (`validatedAt`) => DELETED (`deletedAt`)

But maybe that's because we're used to ActiveRecord impls...

**Comment by bs1180** [comment]
Just to chime in with another potential use case - the afterUpdate would be handy for application-level auditing (eg. logging the before and after states, and which user performed it). There are other ways to achieve though.
