### ISSUE TITLE
Replacing tv4 with a faster validator

### ISSUE THREAD

**Issue by pesho** [Vincit/objection.js#95]
Is there a particular reason why `tv4` is used as the JSON-schema validator? Its performance seems horrible, according to [json-schema-benchmark](https://github.com/ebdrup/json-schema-benchmark) and other similar benchmarks. Can it be replaced with e.g. [ajv](https://github.com/epoberezkin/ajv) or [is-my-json-valid](https://github.com/mafintosh/is-my-json-valid)?

**Comment by koskimas** [comment]
When I selected `tv4` it was the fastest JSON-schema validator on the market. Things seem to have changed :smile:.

Some of the faster validators seem to generate code based on the schema. This process is really slow since the generate code needs to be compiled and optimized by V8. These validators are only fast when the schema doesn't change (the validator doesn't have to be "recompiled"). 

In objection.js it is possible to modify the `jsonSchema` in the `$beforeValidate` method. Since this is allowed we would need to either check if the schema has changed after each `$beforeValidate` call or recompile the validator each time. Both would probably be slower than just using `tv4`.

The possibility to modify `jsonSchema` in `$beforeValidate` may be more of a bug than a feature, and I don't even know if anyone is using it. So we could consider changing this behaviour so that the `jsonSchema` would never change.

Do you actually have a real-life case where the validation performance is a bottleneck? I have never seen such a case. The validation is only run on insert and update and those are usually rare operations and the DB IO is the bottleneck.

If the validation performance is really a bottleneck and you can find a validator that works faster with the above restrictions in mind, I'd be happy to start using that one.

**Comment by koskimas** [comment]
Forgot to mention that you can change the validator for your models by overriding [`$validate`](https://github.com/Vincit/objection.js/blob/master/src/model/ModelBase.js#L156) method. You just need to honor the flags in the `options` object since they are used internally.
